/* Generated by F* Custard extraction. Do not edit. */
#ifndef __CBORNONDET_H
#define __CBORNONDET_H

#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>

/* The sole inhabited erased value (section 5.1).  A distinct typedef rather
than void, so that it can be stored in a variable and returned like any
other value.  Guarded because two generated headers may meet in one
translation unit (section 42.2): this is a fixed name for a fixed type,
so two spellings of it are the same spelling. */
#ifndef CUSTARD_UNIT_DEFINED
#define CUSTARD_UNIT_DEFINED
typedef uint8_t custard_unit;
#endif
#ifdef __cplusplus
extern "C" {
#endif

typedef struct cbor_int_s cbor_int;
typedef struct Pulse_Lib_Slice_slice__uint8_s Pulse_Lib_Slice_slice__uint8;
typedef struct cbor_string_s cbor_string;
typedef struct CBOR_Spec_Raw_Base_raw_uint64_s CBOR_Spec_Raw_Base_raw_uint64;
typedef struct cbor_serialized_s cbor_serialized;
typedef struct cbor_tagged_s cbor_tagged;
typedef struct cbor_array_s cbor_array;
typedef struct cbor_map_entry_s cbor_map_entry;
typedef struct cbor_map_s cbor_map;
typedef struct cbor_raw_s cbor_raw;
typedef struct Pulse_Lib_Slice_slice__cbor_map_entry_s Pulse_Lib_Slice_slice__cbor_map_entry;
typedef struct Pulse_Lib_Slice_slice__cbor_raw_s Pulse_Lib_Slice_slice__cbor_raw;
typedef struct CBOR_Pulse_Raw_Iterator_Base_cbor_raw_serialized_iterator_s CBOR_Pulse_Raw_Iterator_Base_cbor_raw_serialized_iterator;
typedef struct CBOR_Pulse_Raw_Iterator_cbor_raw_iterator__cbor_raw_s CBOR_Pulse_Raw_Iterator_cbor_raw_iterator__cbor_raw;
typedef struct CBOR_Pulse_Raw_Iterator_cbor_raw_iterator__cbor_map_entry_s CBOR_Pulse_Raw_Iterator_cbor_raw_iterator__cbor_map_entry;
typedef struct FStar_Pervasives_Native_tuple2__slice_uint8_slice_uint8_s FStar_Pervasives_Native_tuple2__slice_uint8_slice_uint8;
typedef struct CBOR_Spec_Raw_EverParse_initial_byte_t_s CBOR_Spec_Raw_EverParse_initial_byte_t;
typedef struct CBOR_Spec_Raw_EverParse_long_argument_s CBOR_Spec_Raw_EverParse_long_argument;
typedef struct Prims_dtuple2__initial_byte_t_long_argument_s Prims_dtuple2__initial_byte_t_long_argument;
typedef struct FStar_Pervasives_Native_option__bool_s FStar_Pervasives_Native_option__bool;
typedef struct FStar_Pervasives_Native_option__uintsize_s FStar_Pervasives_Native_option__uintsize;
typedef struct FStar_Pervasives_Native_option__with_perm_slice_cbor_raw_s FStar_Pervasives_Native_option__with_perm_slice_cbor_raw;
typedef struct FStar_Pervasives_Native_option__with_perm_slice_cbor_map_entry_s FStar_Pervasives_Native_option__with_perm_slice_cbor_map_entry;
typedef struct FStar_Pervasives_Native_tuple2__slice_cbor_raw_slice_cbor_raw_s FStar_Pervasives_Native_tuple2__slice_cbor_raw_slice_cbor_raw;
typedef struct FStar_Pervasives_Native_tuple2__slice_cbor_map_entry_slice_cbor_map_entry_s FStar_Pervasives_Native_tuple2__slice_cbor_map_entry_slice_cbor_map_entry;
typedef struct FStar_Pervasives_Native_tuple2__cbor_raw_cbor_raw_s FStar_Pervasives_Native_tuple2__cbor_raw_cbor_raw;
typedef struct FStar_Pervasives_Native_option__cbor_raw_s FStar_Pervasives_Native_option__cbor_raw;
typedef struct CBOR_Pulse_API_Base_cbor_map_get_multiple_entry_t__cbor_raw_s CBOR_Pulse_API_Base_cbor_map_get_multiple_entry_t__cbor_raw;
typedef struct Pulse_Lib_Slice_slice__cbor_map_get_multiple_entry_t_cbor_raw_s Pulse_Lib_Slice_slice__cbor_map_get_multiple_entry_t_cbor_raw;

struct cbor_int_s {
  uint8_t cbor_int_type;
  uint8_t cbor_int_size;
  uint64_t cbor_int_value;
};
struct Pulse_Lib_Slice_slice__uint8_s {
  uint8_t *elt;
  size_t len;
};
struct cbor_string_s {
  uint8_t cbor_string_type;
  uint8_t cbor_string_size;
  Pulse_Lib_Slice_slice__uint8 cbor_string_ptr;
};
struct CBOR_Spec_Raw_Base_raw_uint64_s {
  uint8_t size;
  uint64_t value;
};
struct cbor_serialized_s {
  CBOR_Spec_Raw_Base_raw_uint64 cbor_serialized_header;
  Pulse_Lib_Slice_slice__uint8 cbor_serialized_payload;
};
struct cbor_tagged_s {
  CBOR_Spec_Raw_Base_raw_uint64 cbor_tagged_tag;
  cbor_raw *cbor_tagged_ptr;
};
struct Pulse_Lib_Slice_slice__cbor_raw_s {
  cbor_raw *elt;
  size_t len;
};
struct cbor_array_s {
  uint8_t cbor_array_length_size;
  Pulse_Lib_Slice_slice__cbor_raw cbor_array_ptr;
};
struct Pulse_Lib_Slice_slice__cbor_map_entry_s {
  cbor_map_entry *elt;
  size_t len;
};
struct cbor_map_s {
  uint8_t cbor_map_length_size;
  Pulse_Lib_Slice_slice__cbor_map_entry cbor_map_ptr;
};
enum cbor_raw_tags {
  CBOR_CASE_INT,
  CBOR_CASE_SIMPLE,
  CBOR_CASE_STRING,
  CBOR_CASE_TAGGED,
  CBOR_CASE_ARRAY,
  CBOR_CASE_MAP,
  CBOR_CASE_SERIALIZED_TAGGED,
  CBOR_CASE_SERIALIZED_ARRAY,
  CBOR_CASE_SERIALIZED_MAP
};
struct cbor_raw_s {
  enum cbor_raw_tags tag;
  union {
    struct {
      cbor_int v;
    } CBOR_Pulse_Raw_Type_CBOR_Case_Int;
    struct {
      uint8_t v;
    } CBOR_Pulse_Raw_Type_CBOR_Case_Simple;
    struct {
      cbor_string v;
    } CBOR_Pulse_Raw_Type_CBOR_Case_String;
    struct {
      cbor_tagged v;
    } CBOR_Pulse_Raw_Type_CBOR_Case_Tagged;
    struct {
      cbor_array v;
    } CBOR_Pulse_Raw_Type_CBOR_Case_Array;
    struct {
      cbor_map v;
    } CBOR_Pulse_Raw_Type_CBOR_Case_Map;
    struct {
      cbor_serialized v;
    } CBOR_Pulse_Raw_Type_CBOR_Case_Serialized_Tagged;
    struct {
      cbor_serialized v;
    } CBOR_Pulse_Raw_Type_CBOR_Case_Serialized_Array;
    struct {
      cbor_serialized v;
    } CBOR_Pulse_Raw_Type_CBOR_Case_Serialized_Map;
  } val;
};
struct cbor_map_entry_s {
  cbor_raw cbor_map_entry_key;
  cbor_raw cbor_map_entry_value;
};
typedef cbor_raw cbor_nondet_t;
struct CBOR_Pulse_Raw_Iterator_Base_cbor_raw_serialized_iterator_s {
  Pulse_Lib_Slice_slice__uint8 s;
  uint64_t len;
};
enum CBOR_Pulse_Raw_Iterator_cbor_raw_iterator__cbor_raw_tags {
  CBOR_PULSE_RAW_ITERATOR_CBOR_RAW_ITERATOR_SLICE__CBOR_RAW,
  CBOR_PULSE_RAW_ITERATOR_CBOR_RAW_ITERATOR_SERIALIZED__CBOR_RAW
};
struct CBOR_Pulse_Raw_Iterator_cbor_raw_iterator__cbor_raw_s {
  enum CBOR_Pulse_Raw_Iterator_cbor_raw_iterator__cbor_raw_tags tag;
  union {
    struct {
      Pulse_Lib_Slice_slice__cbor_raw _0;
    } CBOR_Pulse_Raw_Iterator_CBOR_Raw_Iterator_Slice__cbor_raw;
    struct {
      CBOR_Pulse_Raw_Iterator_Base_cbor_raw_serialized_iterator _0;
    } CBOR_Pulse_Raw_Iterator_CBOR_Raw_Iterator_Serialized__cbor_raw;
  } val;
};
typedef CBOR_Pulse_Raw_Iterator_cbor_raw_iterator__cbor_raw cbor_nondet_array_iterator_t;
enum CBOR_Pulse_Raw_Iterator_cbor_raw_iterator__cbor_map_entry_tags {
  CBOR_PULSE_RAW_ITERATOR_CBOR_RAW_ITERATOR_SLICE__CBOR_MAP_ENTRY,
  CBOR_PULSE_RAW_ITERATOR_CBOR_RAW_ITERATOR_SERIALIZED__CBOR_MAP_ENTRY
};
struct CBOR_Pulse_Raw_Iterator_cbor_raw_iterator__cbor_map_entry_s {
  enum CBOR_Pulse_Raw_Iterator_cbor_raw_iterator__cbor_map_entry_tags tag;
  union {
    struct {
      Pulse_Lib_Slice_slice__cbor_map_entry _0;
    } CBOR_Pulse_Raw_Iterator_CBOR_Raw_Iterator_Slice__cbor_map_entry;
    struct {
      CBOR_Pulse_Raw_Iterator_Base_cbor_raw_serialized_iterator _0;
    } CBOR_Pulse_Raw_Iterator_CBOR_Raw_Iterator_Serialized__cbor_map_entry;
  } val;
};
typedef CBOR_Pulse_Raw_Iterator_cbor_raw_iterator__cbor_map_entry cbor_nondet_map_iterator_t;
typedef cbor_map_entry cbor_nondet_map_entry_t;
struct FStar_Pervasives_Native_tuple2__slice_uint8_slice_uint8_s {
  Pulse_Lib_Slice_slice__uint8 _1;
  Pulse_Lib_Slice_slice__uint8 _2;
};
struct CBOR_Spec_Raw_EverParse_initial_byte_t_s {
  uint8_t major_type;
  uint8_t additional_info;
};
enum CBOR_Spec_Raw_EverParse_long_argument_tags {
  CBOR_SPEC_RAW_EVERPARSE_LONGARGUMENTSIMPLEVALUE,
  CBOR_SPEC_RAW_EVERPARSE_LONGARGUMENTU8,
  CBOR_SPEC_RAW_EVERPARSE_LONGARGUMENTU16,
  CBOR_SPEC_RAW_EVERPARSE_LONGARGUMENTU32,
  CBOR_SPEC_RAW_EVERPARSE_LONGARGUMENTU64,
  CBOR_SPEC_RAW_EVERPARSE_LONGARGUMENTOTHER
};
struct CBOR_Spec_Raw_EverParse_long_argument_s {
  enum CBOR_Spec_Raw_EverParse_long_argument_tags tag;
  union {
    struct {
      uint8_t v;
    } CBOR_Spec_Raw_EverParse_LongArgumentSimpleValue;
    struct {
      uint8_t v;
    } CBOR_Spec_Raw_EverParse_LongArgumentU8;
    struct {
      uint16_t v;
    } CBOR_Spec_Raw_EverParse_LongArgumentU16;
    struct {
      uint32_t v;
    } CBOR_Spec_Raw_EverParse_LongArgumentU32;
    struct {
      uint64_t v;
    } CBOR_Spec_Raw_EverParse_LongArgumentU64;
  } val;
};
struct Prims_dtuple2__initial_byte_t_long_argument_s {
  CBOR_Spec_Raw_EverParse_initial_byte_t _1;
  CBOR_Spec_Raw_EverParse_long_argument _2;
};
enum FStar_Pervasives_Native_option__bool_tags {
  FSTAR_PERVASIVES_NATIVE_NONE__BOOL,
  FSTAR_PERVASIVES_NATIVE_SOME__BOOL
};
struct FStar_Pervasives_Native_option__bool_s {
  enum FStar_Pervasives_Native_option__bool_tags tag;
  union {
    struct {
      bool v;
    } FStar_Pervasives_Native_Some__bool;
  } val;
};
enum FStar_Pervasives_Native_option__uintsize_tags {
  FSTAR_PERVASIVES_NATIVE_NONE__UINTSIZE,
  FSTAR_PERVASIVES_NATIVE_SOME__UINTSIZE
};
struct FStar_Pervasives_Native_option__uintsize_s {
  enum FStar_Pervasives_Native_option__uintsize_tags tag;
  union {
    struct {
      size_t v;
    } FStar_Pervasives_Native_Some__uintsize;
  } val;
};
enum FStar_Pervasives_Native_option__with_perm_slice_cbor_raw_tags {
  FSTAR_PERVASIVES_NATIVE_NONE__WITH_PERM_SLICE_CBOR_RAW,
  FSTAR_PERVASIVES_NATIVE_SOME__WITH_PERM_SLICE_CBOR_RAW
};
struct FStar_Pervasives_Native_option__with_perm_slice_cbor_raw_s {
  enum FStar_Pervasives_Native_option__with_perm_slice_cbor_raw_tags tag;
  union {
    struct {
      Pulse_Lib_Slice_slice__cbor_raw v;
    } FStar_Pervasives_Native_Some__with_perm_slice_cbor_raw;
  } val;
};
enum FStar_Pervasives_Native_option__with_perm_slice_cbor_map_entry_tags {
  FSTAR_PERVASIVES_NATIVE_NONE__WITH_PERM_SLICE_CBOR_MAP_ENTRY,
  FSTAR_PERVASIVES_NATIVE_SOME__WITH_PERM_SLICE_CBOR_MAP_ENTRY
};
struct FStar_Pervasives_Native_option__with_perm_slice_cbor_map_entry_s {
  enum FStar_Pervasives_Native_option__with_perm_slice_cbor_map_entry_tags tag;
  union {
    struct {
      Pulse_Lib_Slice_slice__cbor_map_entry v;
    } FStar_Pervasives_Native_Some__with_perm_slice_cbor_map_entry;
  } val;
};
struct FStar_Pervasives_Native_tuple2__slice_cbor_raw_slice_cbor_raw_s {
  Pulse_Lib_Slice_slice__cbor_raw _1;
  Pulse_Lib_Slice_slice__cbor_raw _2;
};
struct FStar_Pervasives_Native_tuple2__slice_cbor_map_entry_slice_cbor_map_entry_s {
  Pulse_Lib_Slice_slice__cbor_map_entry _1;
  Pulse_Lib_Slice_slice__cbor_map_entry _2;
};
struct FStar_Pervasives_Native_tuple2__cbor_raw_cbor_raw_s {
  cbor_raw _1;
  cbor_raw _2;
};
enum FStar_Pervasives_Native_option__cbor_raw_tags {
  FSTAR_PERVASIVES_NATIVE_NONE__CBOR_RAW,
  FSTAR_PERVASIVES_NATIVE_SOME__CBOR_RAW
};
struct FStar_Pervasives_Native_option__cbor_raw_s {
  enum FStar_Pervasives_Native_option__cbor_raw_tags tag;
  union {
    struct {
      cbor_raw v;
    } FStar_Pervasives_Native_Some__cbor_raw;
  } val;
};
struct CBOR_Pulse_API_Base_cbor_map_get_multiple_entry_t__cbor_raw_s {
  cbor_raw key;
  cbor_raw value;
  bool found;
};
typedef CBOR_Pulse_API_Base_cbor_map_get_multiple_entry_t__cbor_raw cbor_nondet_map_get_multiple_entry_t;
struct Pulse_Lib_Slice_slice__cbor_map_get_multiple_entry_t_cbor_raw_s {
  CBOR_Pulse_API_Base_cbor_map_get_multiple_entry_t__cbor_raw *elt;
  size_t len;
};

#define CBOR_MAJOR_TYPE_SIMPLE_VALUE (7U)
#define CBOR_MAJOR_TYPE_UINT64 (0U)
#define CBOR_MAJOR_TYPE_NEG_INT64 (1U)
#define CBOR_MAJOR_TYPE_BYTE_STRING (2U)
#define CBOR_MAJOR_TYPE_TEXT_STRING (3U)
#define CBOR_MAJOR_TYPE_ARRAY (4U)
#define CBOR_MAJOR_TYPE_MAP (5U)
#define CBOR_MAJOR_TYPE_TAGGED (6U)
#define MIN_SIMPLE_VALUE_LONG_ARGUMENT (32U)
#define MAX_SIMPLE_VALUE_ADDITIONAL_INFO (23U)
bool cbor_nondet_parse(bool check_map_key_bound, size_t map_key_bound, uint8_t **pinput, size_t *plen, cbor_raw *dest);
size_t cbor_nondet_size(cbor_raw x, size_t bound);
size_t cbor_nondet_serialize(cbor_raw x, uint8_t *output, size_t len);
uint8_t cbor_nondet_major_type(cbor_raw x);
bool cbor_nondet_read_simple_value(cbor_raw x, uint8_t *dest);
bool cbor_nondet_read_uint64(cbor_raw x, uint64_t *dest);
bool cbor_nondet_read_int64(cbor_raw x, int64_t *dest);
bool cbor_nondet_get_string(cbor_raw x, uint8_t **dest, uint64_t *dlen);
bool cbor_nondet_get_byte_string(cbor_raw x, uint8_t **dest, uint64_t *dlen);
bool cbor_nondet_get_text_string(cbor_raw x, uint8_t **dest, uint64_t *dlen);
bool cbor_nondet_get_tagged(cbor_raw x, cbor_raw *dest, uint64_t *dtag);
bool cbor_nondet_get_array_length(cbor_raw x, uint64_t *dest);
bool cbor_nondet_array_iterator_start(cbor_raw x, CBOR_Pulse_Raw_Iterator_cbor_raw_iterator__cbor_raw *dest);
bool cbor_nondet_array_iterator_is_empty(CBOR_Pulse_Raw_Iterator_cbor_raw_iterator__cbor_raw x);
uint64_t cbor_nondet_array_iterator_length(CBOR_Pulse_Raw_Iterator_cbor_raw_iterator__cbor_raw x);
bool cbor_nondet_array_iterator_next(CBOR_Pulse_Raw_Iterator_cbor_raw_iterator__cbor_raw *x, cbor_raw *dest);
CBOR_Pulse_Raw_Iterator_cbor_raw_iterator__cbor_raw cbor_nondet_array_iterator_truncate(CBOR_Pulse_Raw_Iterator_cbor_raw_iterator__cbor_raw x, uint64_t len);
bool cbor_nondet_get_array_item(cbor_raw x, uint64_t i, cbor_raw *dest);
bool cbor_nondet_get_map_length(cbor_raw x, uint64_t *dest);
bool cbor_nondet_map_iterator_start(cbor_raw x, CBOR_Pulse_Raw_Iterator_cbor_raw_iterator__cbor_map_entry *dest);
bool cbor_nondet_map_iterator_is_empty(CBOR_Pulse_Raw_Iterator_cbor_raw_iterator__cbor_map_entry x);
cbor_raw cbor_nondet_map_entry_key(cbor_map_entry x);
cbor_raw cbor_nondet_map_entry_value(cbor_map_entry x);
bool cbor_nondet_map_iterator_next(CBOR_Pulse_Raw_Iterator_cbor_raw_iterator__cbor_map_entry *x, cbor_raw *dest_key, cbor_raw *dest_value);
bool cbor_nondet_equal(cbor_raw x1, cbor_raw x2);
bool cbor_nondet_map_get(cbor_raw x, cbor_raw k, cbor_raw *dest);
bool cbor_nondet_mk_simple_value(uint8_t v, cbor_raw *dest);
cbor_raw cbor_nondet_mk_uint64(uint64_t v);
cbor_raw cbor_nondet_mk_neg_int64(uint64_t v);
cbor_raw cbor_nondet_mk_int64(int64_t v);
bool cbor_nondet_mk_byte_string(uint8_t *a, uint64_t len, cbor_raw *dest);
bool cbor_nondet_mk_text_string(uint8_t *a, uint64_t len, cbor_raw *dest);
bool cbor_nondet_mk_tagged(uint64_t tag, cbor_raw *r, cbor_raw *dest);
bool cbor_nondet_mk_array(cbor_raw *a, uint64_t len, cbor_raw *dest);
cbor_map_entry cbor_nondet_mk_map_entry(cbor_raw xk, cbor_raw xv);
bool cbor_nondet_mk_map(cbor_map_entry *a, uint64_t len, cbor_raw *dest);
bool cbor_nondet_map_get_multiple(cbor_raw map, CBOR_Pulse_API_Base_cbor_map_get_multiple_entry_t__cbor_raw *dest, size_t len);


#ifdef __cplusplus
}
#endif
#endif

