EVERPARSE_HOME ?= $(realpath ../..)
EVERPARSE_SRC_PATH ?= $(EVERPARSE_HOME)/src
include $(EVERPARSE_SRC_PATH)/windows.Makefile

FSTAR_EXE ?= fstar.exe
LOWPARSE_HOME ?= $(EVERPARSE_SRC_PATH)/lowparse

include $(EVERPARSE_SRC_PATH)/karamel.Makefile
include $(EVERPARSE_SRC_PATH)/fstar.Makefile

export LOWPARSE_HOME

FSTAR_OPTIONS += --odir krml --cache_dir cache --cache_checked_modules \
		--already_cached +Prims,+FStar,+LowStar,+C,+Spec.Loops,+LowParse \
		--include $(LOWPARSE_HOME) --cmi \
		--ext 'optimize_let_vc=false'

FSTAR = $(FSTAR_EXE) $(FSTAR_OPTIONS)

HEADERS = $(addprefix -add-include ,'"krml/internal/compat.h"')

KRML = $(KRML_EXE) \
	 -fstar $(FSTAR_EXE) \
	 -ccopt "-O3" -ccopt "-ffast-math" \
	 -drop 'FStar.Tactics.\*' -drop FStar.Tactics -drop 'FStar.Reflection.\*' \
	 -tmpdir out \
	 -bundle 'LowParse.\*' \
	 $(HEADERS) \
	 -warn-error -9

QD = $(EVERPARSE_SRC_PATH)/../bin/qd.exe
RFC = Test.rfc
