EVERPARSE_HOME ?= $(realpath ../..)
EVERPARSE_SRC_PATH ?= $(EVERPARSE_HOME)/src

FSTAR_EXE ?= fstar.exe
KRML_HOME ?= ../../../karamel
LOWPARSE_HOME ?= $(EVERPARSE_HOME)/src/lowparse

include $(EVERPARSE_SRC_PATH)/fstar.Makefile

export LOWPARSE_HOME
export KRML_HOME
export EVERPARSE_HOME

FSTAR_OPTIONS += --odir krml --cache_dir cache --cache_checked_modules \
		--already_cached +Prims,+FStar,+LowStar,+C,+Spec.Loops,+LowParse \
		--include $(LOWPARSE_HOME) --include $(KRML_HOME)/krmllib --include $(KRML_HOME)/krmllib/obj --cmi \
		--ext 'optimize_let_vc=false'

FSTAR = $(FSTAR_EXE) $(FSTAR_OPTIONS)

HEADERS = $(addprefix -add-include ,'"krml/internal/compat.h"')

KRML = $(KRML_HOME)/krml \
	 -fstar $(FSTAR_EXE) \
	 -ccopt "-Ofast" \
	 -drop 'FStar.Tactics.\*' -drop FStar.Tactics -drop 'FStar.Reflection.\*' \
	 -tmpdir out \
	 -bundle 'LowParse.\*' \
	 $(HEADERS) \
	 -warn-error -9

QD = $(EVERPARSE_HOME)/bin/qd.exe
RFC = Test.rfc
