#!/usr/bin/env python3
"""Generate the 3D Low*/Pulse differential test driver.

Emits a dispatch table over every generated entrypoint so that one driver can
(a) fuzz, using the reported error field name as a progress signal, and
(b) replay a fixed corpus and print a behavioural trace.

The same driver source is compiled against both backends.
"""
import re
import sys
import os
import glob

SIG_RE = re.compile(r'^BOOLEAN\s+(\w+)\s*\((.*?)\);', re.S | re.M)


def parse_params(s):
    out = []
    for raw in s.split(','):
        raw = raw.strip()
        if not raw:
            continue
        m = re.match(r'^(.*?)(\**)\s*(\w+)$', raw.replace('\n', ' ').strip())
        ty, stars, name = m.group(1).strip(), m.group(2), m.group(3)
        if ty.endswith('*'):
            stars = ty[len(ty.rstrip('*')):] + stars
            ty = ty.rstrip('*').strip()
        out.append((ty + stars, name))
    return out


def collect(dirname):
    entries, skipped = [], []
    for hdr in sorted(glob.glob(os.path.join(dirname, '*Wrapper.h'))):
        text = open(hdr).read()
        mod = os.path.basename(hdr)[:-len('Wrapper.h')]
        for m in SIG_RE.finditer(text):
            params = parse_params(m.group(2))
            if not buffer_abi(params):
                skipped.append(m.group(1))
                continue
            entries.append((mod, m.group(1), params))
    return entries, skipped


SCALAR = {'uint8_t', 'uint16_t', 'uint32_t', 'uint64_t', 'BOOLEAN'}
OUTPTR = {'uint8_t*': 'uint8_t', 'uint16_t*': 'uint16_t',
          'uint32_t*': 'uint32_t', 'uint64_t*': 'uint64_t',
          'BOOLEAN*': 'BOOLEAN'}


def buffer_abi(params):
    """True for the `buffer` input-stream ABI, which is the only one this
    harness can drive. The `extern` and `static` backends instead take an
    opaque EVERPARSE_INPUT_STREAM_BASE that only the client can construct."""
    tail = [ty for ty, _ in params[-2:]]
    return tail == ['uint8_t*', 'uint32_t']


def gen(entries, out):
    w = out.write
    w('/* GENERATED by gen_diff.py -- do not edit. */\n')
    w('#include "harness.h"\n')
    for m in sorted({m for m, _, _ in entries}):
        w('#include "%sWrapper.h"\n' % m)
    w('\n/* Per-module error hooks feed the shared trace. */\n')
    for m in sorted({m for m, _, _ in entries}):
        w('void %sEverParseError(const char *t, const char *f, const char *r)'
          ' { hx_error(t, f, r); }\n' % m)
    w('\n')

    for mod, fn, params in entries:
        body = params[:-2]
        w('static BOOLEAN call_%s(const uint64_t *A, uint8_t *buf, uint32_t len, char *d) {\n' % fn)
        args, post, na, ncb = [], [], 0, 0
        for ty, name in body:
            if ty in SCALAR:
                w('  %s a_%s = (%s)A[%d];\n' % (ty, name, ty, na))
                args.append('a_' + name)
                post.append(('in', 'a_' + name))
                na += 1
            elif ty in OUTPTR:
                base = OUTPTR[ty]
                w('  %s o_%s = (%s)0xABCDEF0123456789ull;\n' % (base, name, base))
                args.append('&o_' + name)
                post.append(('out', 'o_' + name))
            elif ty == 'uint8_t**':
                w('  uint8_t *o_%s = NULL;\n' % name)
                args.append('&o_' + name)
                post.append(('ptr', 'o_' + name))
            elif ty == 'EVERPARSE_COPY_BUFFER_T':
                w('  hx_cb_t cb_%s; hx_cb_init(&cb_%s, %d);\n' % (name, name, ncb))
                args.append('&cb_' + name)
                post.append(('cb', 'cb_' + name))
                ncb += 1
            elif ty.endswith('*'):
                # An out-parameter of a type the test defines itself: an output
                # type, or an external typedef such as iter's OUT_T. We cannot
                # interpret it, but both backends are handed the same
                # declaration, so comparing the raw bytes afterwards is exactly
                # the right check.
                #
                # Zero, not a poison pattern: these structs may hold pointers
                # that the test's own external API dereferences, and a
                # well-behaved client hands over a freshly zeroed object.
                base = ty[:-1].strip()
                w('  %s o_%s; memset(&o_%s, 0, sizeof o_%s);\n'
                  % (base, name, name, name))
                args.append('&o_' + name)
                post.append(('raw', 'o_' + name))
            else:
                raise SystemExit('unhandled type %r in %s' % (ty, fn))
        w('  (void)A;\n')
        w('  BOOLEAN r = %s(%s);\n' % (fn, ', '.join(args + ['buf', 'len'])))
        w('  if (d) { int n = 0;\n')
        for kind, var in post:
            if kind == 'in':
                w('    n += sprintf(d + n, "|in.%s=%%s", hx_u64((uint64_t)%s));\n' % (var, var))
            elif kind == 'out':
                w('    n += sprintf(d + n, "|%s=%%s", hx_u64((uint64_t)%s));\n' % (var, var))
            elif kind == 'ptr':
                w('    n += sprintf(d + n, "|%s=%%s", hx_off(%s, buf, len));\n' % (var, var))
            elif kind == 'cb':
                w('    n += sprintf(d + n, "|%s=%%s", hx_cb_show(&%s));\n' % (var, var))
            elif kind == 'raw':
                w('    n += sprintf(d + n, "|%s=%%s", hx_bytes(&%s, sizeof %s));\n'
                  % (var, var, var))
        w('    d[n] = 0; }\n')
        w('  return r;\n}\n\n')

    w('const hx_entry_t hx_entries[] = {\n')
    for mod, fn, params in entries:
        nscal = sum(1 for ty, _ in params[:-2] if ty in SCALAR)
        w('  { "%s", call_%s, %d },\n' % (fn, fn, nscal))
    w('};\n')
    w('const int hx_nentries = %d;\n' % len(entries))


if __name__ == '__main__':
    entries, skipped = collect(sys.argv[1])
    if not entries:
        sys.exit('%s: no entrypoint with the buffer ABI' % sys.argv[1])
    sys.stderr.write('%d entrypoints%s\n' %
                     (len(entries),
                      ', %d skipped (non-buffer ABI): %s' %
                      (len(skipped), ' '.join(skipped)) if skipped else ''))
    with open(sys.argv[2], 'w') as f:
        gen(entries, f)
