#!/usr/bin/env python3
"""Regenerate seeds.inc, the solver-derived seed corpus for the fuzzer.

Some entrypoints cannot be reached by search at all. Arithmetic's `_Check` is
thirteen consecutive UINT32 fields each pinned to an exact value by a
refinement, so the chance of a mutator ever producing one accepted input is
nil, and the entrypoint contributed no cross-backend evidence: every case it
ran ended in the same first-field rejection. A constant dictionary does not
help either, because the values that have to be planted are computed from
earlier fields rather than written in the .3d.

EverParse already solves exactly this problem for its own test suite, with
`3d --z3_test`, which asks Z3 for inputs that drive a grammar down a chosen
branch. This script reuses that: it runs the witness generator over the
entrypoints the fuzzer cannot reach, keeps the witnesses that were accepted,
and writes them out as a C table for the harness to seed its corpus with.

The result is checked in, so neither Z3 nor this script is needed to build or
run the differential test -- which matters because the generator takes minutes
and is not available in every configuration. Rerun it only when one of the
grammars below changes:

    python3 gen_seeds.py seeds.inc

Entrypoints are listed here only if the generator actually terminates on them.
It does not support probes (`Specialize6._SRI` fails with "unsupported
argument type"), and it does not finish in reasonable time on the larger
grammars (`ELF._ELF`, `TAtMost._T`). Those stay out; the dictionary in
gen_diff.py is what carries them.
"""
import os
import re
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
TESTS = os.path.dirname(HERE)

# (.3d file, the type to solve for, the driver entrypoint it seeds)
TARGETS = [
    ('Arithmetic.3d', 'Arithmetic._Check', 'ArithmeticCheckCheck'),
    ('Arithmetic.3d', 'Arithmetic._Test3', 'ArithmeticCheckTest3'),
    ('ELFTestGen.3d', 'ELFTestGen._ELFTestGen', 'ElftestGenCheckElftestGen'),
]

WITNESSES = '10'
BRANCH_DEPTH = '4'
TIMEOUT = 600

# The generated harness prints each witness and then the verdict the validator
# actually reached on it.
WIT_RE = re.compile(
    r'uint8_t (witness\d+)_0\[(\d+)\] = \{([^}]*)\};.*?\n'
    r'\s*//[^\n]*\1\[0\]\.buf[^\n]*// (ACCEPTED|REJECTED)')


def witnesses(home, src, ty):
    with tempfile.TemporaryDirectory() as d:
        p = subprocess.run(
            [os.path.join(home, 'bin', '3d.exe'),
             '--z3_executable', os.environ.get('Z3', 'z3'),
             '--batch', '--odir', d, os.path.join(TESTS, src),
             '--z3_test', ty,
             '--z3_witnesses', WITNESSES,
             '--z3_branch_depth', BRANCH_DEPTH],
            capture_output=True, text=True, timeout=TIMEOUT)
        out = p.stdout + p.stderr
    found, seen = [], set()
    for m in WIT_RE.finditer(out):
        if m.group(4) != 'ACCEPTED':
            continue
        b = tuple(int(x) for x in m.group(3).split(','))
        if len(b) != int(m.group(2)):
            sys.exit('%s: witness length does not match its declaration' % ty)
        if b not in seen:
            seen.add(b)
            found.append(b)
    if not found:
        sys.exit('%s: the generator produced no accepted witness; it must '
                 'have failed. Output follows.\n%s' % (ty, out))
    return found


def main(dest):
    home = os.environ.get('EVERPARSE_HOME')
    if not home:
        sys.exit('EVERPARSE_HOME is not set')
    chunks, table, maxlen = [], [], 0
    for src, ty, entry in TARGETS:
        ws = witnesses(home, src, ty)
        sys.stderr.write('%s: %d accepted witnesses\n' % (ty, len(ws)))
        for i, b in enumerate(ws):
            name = 'seed_%s_%d' % (entry, i)
            maxlen = max(maxlen, len(b))
            chunks.append('static const uint8_t %s[] = {%s};\n'
                          % (name, ', '.join(str(x) for x in b)))
            table.append('  { "%s", %d, %s },\n' % (entry, len(b), name))
    with open(dest, 'w') as f:
        f.write('/* GENERATED by gen_seeds.py -- do not edit.\n'
                '   Inputs that `3d --z3_test` proved a validator accepts, for\n'
                '   the entrypoints no amount of fuzzing can reach. See\n'
                '   gen_seeds.py for how to regenerate this file. */\n')
        f.write('#if %d > HX_MAXLEN\n'
                '#error "a seed is longer than HX_MAXLEN"\n'
                '#endif\n\n' % maxlen)
        f.writelines(chunks)
        f.write('\nstatic const hx_seed_t hx_seeds[] = {\n')
        f.writelines(table)
        f.write('};\n')
    sys.stderr.write('%s: %d seeds, longest %d bytes\n'
                     % (dest, len(table), maxlen))


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, 'seeds.inc'))
