#!/usr/bin/env python3
"""Generate the 3D Low*/Pulse differential test driver.

Emits a dispatch table over every generated entrypoint so that one driver can
(a) fuzz, using the reported error field name as a progress signal, and
(b) replay a fixed corpus and print a behavioural trace.

The same driver source is compiled against both backends.
"""
import re
import sys
import os
import glob

SIG_RE = re.compile(r'^BOOLEAN\s+(\w+)\s*\((.*?)\);', re.S | re.M)


def parse_params(s):
    out = []
    for raw in s.split(','):
        raw = raw.strip()
        if not raw:
            continue
        m = re.match(r'^(.*?)(\**)\s*(\w+)$', raw.replace('\n', ' ').strip())
        ty, stars, name = m.group(1).strip(), m.group(2), m.group(3)
        if ty.endswith('*'):
            stars = ty[len(ty.rstrip('*')):] + stars
            ty = ty.rstrip('*').strip()
        out.append((ty + stars, name))
    return out


def collect(dirname):
    entries = []
    for hdr in sorted(glob.glob(os.path.join(dirname, '*Wrapper.h'))):
        text = open(hdr).read()
        mod = os.path.basename(hdr)[:-len('Wrapper.h')]
        for m in SIG_RE.finditer(text):
            entries.append((mod, m.group(1), parse_params(m.group(2))))
    return entries


SCALAR = {'uint8_t', 'uint16_t', 'uint32_t', 'uint64_t', 'BOOLEAN'}
OUTPTR = {'uint8_t*': 'uint8_t', 'uint16_t*': 'uint16_t',
          'uint32_t*': 'uint32_t', 'uint64_t*': 'uint64_t'}


def gen(entries, out):
    w = out.write
    w('/* GENERATED by gen_diff.py -- do not edit. */\n')
    w('#include "harness.h"\n')
    for m in sorted({m for m, _, _ in entries}):
        w('#include "%sWrapper.h"\n' % m)
    w('\n/* Per-module error hooks feed the shared trace. */\n')
    for m in sorted({m for m, _, _ in entries}):
        w('void %sEverParseError(const char *t, const char *f, const char *r)'
          ' { hx_error(t, f, r); }\n' % m)
    w('\n')

    for mod, fn, params in entries:
        body = params[:-2]
        w('static BOOLEAN call_%s(const uint64_t *A, uint8_t *buf, uint32_t len, char *d) {\n' % fn)
        args, post, na, ncb = [], [], 0, 0
        for ty, name in body:
            if ty in SCALAR:
                w('  %s a_%s = (%s)A[%d];\n' % (ty, name, ty, na))
                args.append('a_' + name)
                post.append(('in', 'a_' + name))
                na += 1
            elif ty in OUTPTR:
                base = OUTPTR[ty]
                w('  %s o_%s = (%s)0xABCDEF0123456789ull;\n' % (base, name, base))
                args.append('&o_' + name)
                post.append(('out', 'o_' + name))
            elif ty == 'uint8_t**':
                w('  uint8_t *o_%s = NULL;\n' % name)
                args.append('&o_' + name)
                post.append(('ptr', 'o_' + name))
            elif ty == 'EVERPARSE_COPY_BUFFER_T':
                w('  hx_cb_t cb_%s; hx_cb_init(&cb_%s, %d);\n' % (name, name, ncb))
                args.append('&cb_' + name)
                post.append(('cb', 'cb_' + name))
                ncb += 1
            else:
                raise SystemExit('unhandled type %r in %s' % (ty, fn))
        w('  (void)A;\n')
        w('  BOOLEAN r = %s(%s);\n' % (fn, ', '.join(args + ['buf', 'len'])))
        w('  if (d) { int n = 0;\n')
        for kind, var in post:
            if kind == 'in':
                w('    n += sprintf(d + n, "|in.%s=%%s", hx_u64((uint64_t)%s));\n' % (var, var))
            elif kind == 'out':
                w('    n += sprintf(d + n, "|%s=%%s", hx_u64((uint64_t)%s));\n' % (var, var))
            elif kind == 'ptr':
                w('    n += sprintf(d + n, "|%s=%%s", hx_off(%s, buf, len));\n' % (var, var))
            elif kind == 'cb':
                w('    n += sprintf(d + n, "|%s=%%s", hx_cb_show(&%s));\n' % (var, var))
        w('    d[n] = 0; }\n')
        w('  return r;\n}\n\n')

    w('const hx_entry_t hx_entries[] = {\n')
    for mod, fn, params in entries:
        nscal = sum(1 for ty, _ in params[:-2] if ty in SCALAR)
        w('  { "%s", call_%s, %d },\n' % (fn, fn, nscal))
    w('};\n')
    w('const int hx_nentries = %d;\n' % len(entries))


if __name__ == '__main__':
    entries = collect(sys.argv[1])
    sys.stderr.write('%d entrypoints\n' % len(entries))
    with open(sys.argv[2], 'w') as f:
        gen(entries, f)
