#!/usr/bin/env python3
"""Generate the 3D Low*/Pulse differential test driver.

Emits a dispatch table over every generated entrypoint so that one driver can
(a) fuzz, using the reported error field name as a progress signal, and
(b) replay a fixed corpus and print a behavioural trace.

The same driver source is compiled against both backends.
"""
import re
import sys
import os
import glob

SIG_RE = re.compile(r'^BOOLEAN\s+(\w+)\s*\((.*?)\);', re.S | re.M)


def parse_params(s):
    out = []
    for raw in s.split(','):
        raw = raw.strip()
        if not raw:
            continue
        m = re.match(r'^(.*?)(\**)\s*(\w+)$', raw.replace('\n', ' ').strip())
        ty, stars, name = m.group(1).strip(), m.group(2), m.group(3)
        if ty.endswith('*'):
            stars = ty[len(ty.rstrip('*')):] + stars
            ty = ty.rstrip('*').strip()
        out.append((ty + stars, name))
    return out


def collect(dirname):
    entries, skipped = [], []
    for hdr in sorted(glob.glob(os.path.join(dirname, '*Wrapper.h'))):
        text = open(hdr).read()
        mod = os.path.basename(hdr)[:-len('Wrapper.h')]
        for m in SIG_RE.finditer(text):
            params = parse_params(m.group(2))
            if not buffer_abi(params):
                skipped.append(m.group(1))
                continue
            entries.append((mod, m.group(1), params))
    return entries, skipped


# Must match HX_NARGS in harness.h.
NARGS = 8

SCALAR = {'uint8_t', 'uint16_t', 'uint32_t', 'uint64_t', 'BOOLEAN'}
OUTPTR = {'uint8_t*': 'uint8_t', 'uint16_t*': 'uint16_t',
          'uint32_t*': 'uint32_t', 'uint64_t*': 'uint64_t',
          'BOOLEAN*': 'BOOLEAN'}


LIT_RE = re.compile(r'0[xX][0-9A-Fa-f]+|\b[0-9]+\b')


def dictionary(outdir, mod):
    """Every integer literal written in the module's .3d specification.

    A blind mutator cannot guess a magic number: ELF's `e_ident` has to start
    with 0x7f 'E' 'L' 'F', and Enumerations' tag has to be one of three values,
    so the odds of a random byte string ever reaching past the first field are
    negligible and those entrypoints contributed no cross-backend evidence at
    all. The literals in the .3d are exactly the values the validator compares
    against, which makes them the dictionary a fuzzer needs.

    Taken from the .3d rather than from generated code because the interpreter
    backend compiles constants away into a grammar data structure -- ELF.c and
    ELF.fst between them retain none of the magic -- and because the .3d is the
    one input both backends are generated from, so the dictionary cannot
    accidentally differ between them."""
    # 3D derives the module name from the file name by dropping underscores
    # and recapitalising, so Test_Synthetic1.3d becomes TestSynthetic1 and
    # ELFTestGen.3d becomes ElftestGen. Match on the normalised name, or those
    # modules silently get no dictionary at all.
    key = mod.replace('_', '').lower()
    root = os.path.dirname(os.path.abspath(outdir))
    found = [f for f in sorted(glob.glob(os.path.join(root, '**', '*.3d'),
                                         recursive=True))
             if os.path.basename(f)[:-3].replace('_', '').lower() == key]
    if not found:
        return []
    # In order of first appearance, not sorted: a multi-byte magic number is
    # written one literal per byte in field order, so laying the dictionary
    # down end to end reproduces it verbatim.
    vals = []
    seen = set()
    for line in open(found[0], errors='replace'):
        line = line.split('//')[0]
        for m in LIT_RE.finditer(line):
            v = int(m.group(0), 0)
            if 2 <= v < (1 << 64) and v not in seen:
                seen.add(v)         # 0 and 1 are already in INTERESTING
                vals.append(v)
    return vals


def buffer_abi(params):
    """True for the `buffer` input-stream ABI, which is the only one this
    harness can drive. The `extern` and `static` backends instead take an
    opaque EVERPARSE_INPUT_STREAM_BASE that only the client can construct."""
    tail = [ty for ty, _ in params[-2:]]
    return tail == ['uint8_t*', 'uint32_t']


def gen(entries, out, srcdir):
    w = out.write
    w('/* GENERATED by gen_diff.py -- do not edit. */\n')
    w('#include "harness.h"\n')
    for m in sorted({m for m, _, _ in entries}):
        w('#include "%sWrapper.h"\n' % m)
    w('\n/* Per-module error hooks feed the shared trace. */\n')
    for m in sorted({m for m, _, _ in entries}):
        w('void %sEverParseError(const char *t, const char *f, const char *r)'
          ' { hx_error(t, f, r); }\n' % m)
    w('\n')

    for mod, fn, params in entries:
        body = params[:-2]
        nout = sum(1 for ty, _ in body if ty in OUTPTR)
        nscal = sum(1 for ty, _ in body if ty in SCALAR)
        if nscal + nout > NARGS:
            raise SystemExit(
                '%s: %d scalar args + %d out-parameters exceed HX_NARGS=%d; '
                'raise HX_NARGS in harness.h' % (fn, nscal, nout, NARGS))
        w('static BOOLEAN call_%s(const uint64_t *A, uint8_t *buf, uint32_t len, char *d) {\n' % fn)
        args, post, na, ncb, no = [], [], 0, 0, 0
        for ty, name in body:
            if ty in SCALAR:
                w('  %s a_%s = (%s)A[%d];\n' % (ty, name, ty, na))
                args.append('a_' + name)
                post.append(('in', 'a_' + name))
                na += 1
            elif ty in OUTPTR:
                # Seeded from the fuzzer-controlled arguments rather than from
                # a fixed poison value. A `mutable` 3D parameter is an in/out
                # accumulator that the grammar may *read*, so a constant seed
                # can leave an entrypoint unsatisfiable by construction:
                # ActAndCheck's `C` validates only when the accumulator ends at
                # 0 and its `A` action can only increase it, so with the old
                # 0xABCDEF0123456789 seed `C` was never once accepted.
                #
                # Taken from the top of A[] while scalars are taken from the
                # bottom, so that adding an out-parameter does not renumber the
                # scalar arguments; the check above keeps the two from meeting.
                base = OUTPTR[ty]
                w('  %s i_%s = (%s)A[%d];\n' % (base, name, base, NARGS - 1 - no))
                w('  %s o_%s = i_%s;\n' % (base, name, name))
                args.append('&o_' + name)
                post.append(('out', 'o_' + name, 'i_' + name))
                no += 1
            elif ty == 'uint8_t**':
                w('  uint8_t *o_%s = NULL;\n' % name)
                args.append('&o_' + name)
                post.append(('ptr', 'o_' + name))
            elif ty == 'EVERPARSE_COPY_BUFFER_T':
                w('  hx_cb_t cb_%s; hx_cb_init(&cb_%s, %d);\n' % (name, name, ncb))
                args.append('&cb_' + name)
                post.append(('cb', 'cb_' + name))
                ncb += 1
            elif ty.endswith('*'):
                # An out-parameter of a type the test defines itself: an output
                # type, or an external typedef such as iter's OUT_T. We cannot
                # interpret it, but both backends are handed the same
                # declaration, so comparing the raw bytes afterwards is exactly
                # the right check.
                #
                # Zero, not a poison pattern: these structs may hold pointers
                # that the test's own external API dereferences, and a
                # well-behaved client hands over a freshly zeroed object.
                base = ty[:-1].strip()
                w('  %s o_%s; memset(&o_%s, 0, sizeof o_%s);\n'
                  % (base, name, name, name))
                args.append('&o_' + name)
                post.append(('raw', 'o_' + name))
            else:
                raise SystemExit('unhandled type %r in %s' % (ty, fn))
        w('  (void)A;\n')
        w('  BOOLEAN r = %s(%s);\n' % (fn, ', '.join(args + ['buf', 'len'])))
        w('  if (d) { int n = 0;\n')
        for entry in post:
            kind, var = entry[0], entry[1]
            if kind == 'in':
                w('    n += sprintf(d + n, "|in.%s=%%s", hx_u64((uint64_t)%s));\n' % (var, var))
            elif kind == 'out':
                # The seed is part of the observation: an out-parameter the
                # validator leaves untouched only means something next to what
                # it started as.
                w('    n += sprintf(d + n, "|%s.in=%%s", hx_u64((uint64_t)%s));\n'
                  % (var, entry[2]))
                w('    n += sprintf(d + n, "|%s=%%s", hx_u64((uint64_t)%s));\n' % (var, var))
            elif kind == 'ptr':
                w('    n += sprintf(d + n, "|%s=%%s", hx_off(%s, buf, len));\n' % (var, var))
            elif kind == 'cb':
                w('    n += sprintf(d + n, "|%s=%%s", hx_cb_show(&%s));\n' % (var, var))
            elif kind == 'raw':
                w('    n += sprintf(d + n, "|%s=%%s", hx_bytes(&%s, sizeof %s));\n'
                  % (var, var, var))
        w('    d[n] = 0; }\n')
        w('  return r;\n}\n\n')

    dicts = {}
    for mod in sorted({m for m, _, _ in entries}):
        d = dictionary(srcdir, mod)
        if d:
            dicts[mod] = d
            w('static const uint64_t dict_%s[] = {%s};\n'
              % (mod, ', '.join('%dull' % v for v in d)))
    w('\n')

    w('const hx_entry_t hx_entries[] = {\n')
    for mod, fn, params in entries:
        nscal = sum(1 for ty, _ in params[:-2] if ty in SCALAR)
        if mod in dicts:
            w('  { "%s", call_%s, %d, dict_%s, %d },\n'
              % (fn, fn, nscal, mod, len(dicts[mod])))
        else:
            w('  { "%s", call_%s, %d, NULL, 0 },\n' % (fn, fn, nscal))
    w('};\n')
    w('const int hx_nentries = %d;\n' % len(entries))


def cross_check(adir, aentries, bdir):
    """The whole method rests on one driver being valid against both backends,
    so the two must expose exactly the same entrypoints with exactly the same
    signatures. When they do not -- usually because a .3d was added on one
    side and the other tree was not kept in step -- say so here, rather than
    leaving it to surface as an undefined reference at link time."""
    bentries, _ = collect(bdir)
    a = {fn: params for _, fn, params in aentries}
    b = {fn: params for _, fn, params in bentries}
    problems = []
    for fn in sorted(set(a) - set(b)):
        problems.append('  %s: only in %s' % (fn, adir))
    for fn in sorted(set(b) - set(a)):
        problems.append('  %s: only in %s' % (fn, bdir))
    for fn in sorted(set(a) & set(b)):
        if a[fn] != b[fn]:
            problems.append('  %s: signatures differ\n    %s\n    %s'
                            % (fn, a[fn], b[fn]))
    if problems:
        sys.exit('pulse-diff: the two test trees have drifted apart:\n%s\n'
                 'The .3d sources under src/3d/tests and '
                 'share/everparse/tests/3d are meant to match; update the one '
                 'that is behind and regenerate.' % '\n'.join(problems))


if __name__ == '__main__':
    entries, skipped = collect(sys.argv[1])
    if not entries:
        sys.exit('%s: no entrypoint with the buffer ABI' % sys.argv[1])
    if len(sys.argv) > 3:
        cross_check(sys.argv[1], entries, sys.argv[3])
    sys.stderr.write('%d entrypoints%s\n' %
                     (len(entries),
                      ', %d skipped (non-buffer ABI): %s' %
                      (len(skipped), ' '.join(skipped)) if skipped else ''))
    with open(sys.argv[2], 'w') as f:
        gen(entries, f, sys.argv[1])
