module EverParse3d.InputStream.Static
open Pulse.Lib.Pervasives
#lang-pulse

(* The [static] backend.

   In Low*, `static` is not a separate F* development at all: `Batch.ml` maps
   "static" to "extern" for the F*/krml include directory, and the two backends
   differ *only* by the C linkage of the five primitives declared in
   `EverParse.h` (`EverParseHas`, `EverParseRead`, `EverParsePeep`,
   `EverParseSkip`, `EverParseEmpty` are `extern` in one and `static [inline]`
   in the other).

   Here the two backends must nevertheless be distinct F* modules, because each
   backend owns its own `[@@CMacro] assume val error_handler_macro`, which the
   3D frontend passes to `validate_with_error_handler`. So this module is a thin
   re-export of the `extern` instance, with its own error handler macro.

   One caveat, found when first extracting these backends to C. Under `--pulse`
   EverParse.h is generated by KaRaMeL rather than shipped by the prelude, and
   KaRaMeL emits a plain `extern` declaration for every assumed primitive. The
   `static [inline]` linkage that is the whole of the Low* difference therefore
   does not currently reach the C level: `static` links exactly like `extern`.
   Recovering it would need a way to ask KaRaMeL for a static-header declaration
   of an assumed val. Keeping the backends separate here means that, if such a
   mechanism appears, only this module has to change. *)

module E = EverParse3d.InputStream.Extern
module I = EverParse3d.InputStream.Base
module Common = EverParse3d.Actions.Common
module AB = EverParse3d.Actions.Base
open EverParse3d.State

inline_for_extraction
noextract
let base_t = E.base_t
inline_for_extraction
noextract
let len_t = E.len_t
inline_for_extraction
noextract
let pos_t = E.pos_t

noextract
inline_for_extraction
instance input_stream_static : I.input_stream_inst base_t len_t pos_t =
  E.input_stream_extern

(* The error handler used when 3d is invoked with `--use_error_handler_macro`.
   Each backend provides its own; the 3D frontend passes the one matching the
   selected `--input_stream` to `validate_with_error_handler`. *)
[@@CMacro]
assume val error_handler_macro : Common.error_handler #base_t #len_t #pos_t

(* `field_ptr_after` is available here for the same reason it is available in
   `extern`: it rests on the client's Peep primitive, which both backends
   provide. Re-exported rather than redefined, so that the two backends share
   one assumed primitive. *)
noextract
inline_for_extraction
let ___PUINT8 = E.___PUINT8

[@@Common.specialize_backend]
noextract
inline_for_extraction
let field_ptr_after
: option (AB.field_ptr_after_t base_t len_t pos_t #input_stream_static ___PUINT8)
= E.field_ptr_after

[@@Common.specialize_backend]
noextract
inline_for_extraction
let field_ptr_after_with_setter (extra_state: state_dict)
: option (AB.field_ptr_after_setter_t base_t len_t pos_t #input_stream_static extra_state ___PUINT8)
= E.field_ptr_after_with_setter extra_state

(* No `copy_buffer` instance: probing is unavailable for the `static` backend,
   as in Low*. *)
