all: verify

EVERPARSE_SRC_PATH = $(realpath ../../src)
ALREADY_CACHED := *,-ArithParse,

include $(EVERPARSE_SRC_PATH)/everparse.Makefile
include $(EVERPARSE_SRC_PATH)/pulse.Makefile
include $(EVERPARSE_SRC_PATH)/common.Makefile
