#ifndef __EVERPARSESTREAM
#define __EVERPARSESTREAM

#include <stddef.h>
#include <stdint.h>
#include "EverParsePulseEndianness.h"

/* A client-provided input stream for `3d --pulse --input_stream static`.

   `static` and `extern` are one F* development, so they ask the client for the
   same primitives:

     BOOLEAN  EverParseStreamHasAt(base, off, n)
     BOOLEAN  EverParseStreamHas(base, n)
     void     EverParseStreamReadBytes(base, n, dst)
     void     EverParseStreamSkip(base, n)
     size_t   EverParseStreamEmpty(base)
     size_t   EverParseStreamGetPosition(base)
     BOOLEAN  EverParseFieldPtrAfterImpl(sz, out, base)

   The last one backs the field_ptr_after action, which `buffer` does not have.

   Note on `static` under --pulse. In Low* the two backends differ in the C
   linkage of these primitives: the prelude ships a hand-written EverParse.h
   per backend, and the `static` one declares them `static inline` so the
   compiler sees each stream operation at every validator call site. Under
   --pulse EverParse.h is generated by KaRaMeL, which emits a plain `extern`
   declaration for every assumed primitive, so that distinction does not
   currently reach the C level and `static` links exactly like `extern`. The two
   remain separate F* modules because each owns its own error_handler_macro,
   which is what the 3D frontend selects on. Recovering the Low* behaviour would
   need a way to ask KaRaMeL for a static-header declaration of an assumed val.

   Unlike Low*, the stream tracks its own position (the validator takes only the
   stream object, and the generated wrapper recovers the parsed size with
   EverParseStreamGetPosition), byte counts are size_t, and ReadBytes always
   copies rather than returning a possibly-aliasing pointer. */

struct es_cell {
  uint8_t * buf;
  size_t len;
  struct es_cell * next;
};

struct EVERPARSE_INPUT_STREAM_BASE_s {
  struct es_cell * head;
  size_t consumed;
};

typedef struct EVERPARSE_INPUT_STREAM_BASE_s * EVERPARSE_INPUT_STREAM_BASE;

EVERPARSE_INPUT_STREAM_BASE EverParseCreate(void);

int EverParsePush(EVERPARSE_INPUT_STREAM_BASE x, uint8_t * buf, size_t len);

uint8_t *EverParseStreamPeep(EVERPARSE_INPUT_STREAM_BASE x, size_t n);

// dummy type, it is not used
typedef int EVERPARSE_EXTRA_T;

void EverParseHandleError(EVERPARSE_EXTRA_T _dummy, uint64_t parsedSize, const char *typename, const char *fieldname, const char *reason, uint64_t error_code);
void EverParseRetreat(EVERPARSE_EXTRA_T _dummy, EVERPARSE_INPUT_STREAM_BASE base, uint64_t parsedSize);

#endif // __EVERPARSESTREAM
