# Echoes the list of all KRML files from $(EXAMPLE).depend file

ifndef EXAMPLE
  $(error EXAMPLE must be defined.)
endif

all: echo-krml-files

include $(EXAMPLE).depend

echo-krml-files:
	echo EX_$(EXAMPLE)_KRML_FILES = $(filter-out $(EXCLUDE_KRML_FILES), $(ALL_KRML_FILES)) >> .depend
	echo $(EXAMPLE)/a.out: EXAMPLE_KRML_FILES = '$$(EX_$(EXAMPLE)_KRML_FILES)' >> .depend
	echo $(EXAMPLE)/a.out: '$$(EX_$(EXAMPLE)_KRML_FILES)' >> .depend
	echo $(EXAMPLE)/a.out: EXAMPLE = $(EXAMPLE) >> .depend
