all: verify

EVERCBOR_SRC_PATH = $(realpath ../..)
INCLUDE_PATHS += $(realpath ..) $(EVERCBOR_SRC_PATH)/lowparse

include $(EVERCBOR_SRC_PATH)/everparse.Makefile
include $(EVERCBOR_SRC_PATH)/common.Makefile
