(*
 Autogenerated by Thrift Compiler (0.22.0)

 DO NOT EDIT UNLESS YOU ARE SURE YOU KNOW WHAT YOU ARE DOING
*)

open Thrift
module Type : 
sig
  type t = 
    | BOOLEAN
    | INT32
    | INT64
    | INT96
    | FLOAT
    | DOUBLE
    | BYTE_ARRAY
    | FIXED_LEN_BYTE_ARRAY
  val to_i : t -> Int32.t
  val of_i : Int32.t -> t
end
module ConvertedType : 
sig
  type t = 
    | UTF8
    | MAP
    | MAP_KEY_VALUE
    | LIST
    | ENUM
    | DECIMAL
    | DATE
    | TIME_MILLIS
    | TIME_MICROS
    | TIMESTAMP_MILLIS
    | TIMESTAMP_MICROS
    | UINT_8
    | UINT_16
    | UINT_32
    | UINT_64
    | INT_8
    | INT_16
    | INT_32
    | INT_64
    | JSON
    | BSON
    | INTERVAL
  val to_i : t -> Int32.t
  val of_i : Int32.t -> t
end
module FieldRepetitionType : 
sig
  type t = 
    | REQUIRED
    | OPTIONAL
    | REPEATED
  val to_i : t -> Int32.t
  val of_i : Int32.t -> t
end
module EdgeInterpolationAlgorithm : 
sig
  type t = 
    | SPHERICAL
    | VINCENTY
    | THOMAS
    | ANDOYER
    | KARNEY
  val to_i : t -> Int32.t
  val of_i : Int32.t -> t
end
module Encoding : 
sig
  type t = 
    | PLAIN
    | PLAIN_DICTIONARY
    | RLE
    | BIT_PACKED
    | DELTA_BINARY_PACKED
    | DELTA_LENGTH_BYTE_ARRAY
    | DELTA_BYTE_ARRAY
    | RLE_DICTIONARY
    | BYTE_STREAM_SPLIT
  val to_i : t -> Int32.t
  val of_i : Int32.t -> t
end
module CompressionCodec : 
sig
  type t = 
    | UNCOMPRESSED
    | SNAPPY
    | GZIP
    | LZO
    | BROTLI
    | LZ4
    | ZSTD
    | LZ4_RAW
  val to_i : t -> Int32.t
  val of_i : Int32.t -> t
end
module PageType : 
sig
  type t = 
    | DATA_PAGE
    | INDEX_PAGE
    | DICTIONARY_PAGE
    | DATA_PAGE_V2
  val to_i : t -> Int32.t
  val of_i : Int32.t -> t
end
module BoundaryOrder : 
sig
  type t = 
    | UNORDERED
    | ASCENDING
    | DESCENDING
  val to_i : t -> Int32.t
  val of_i : Int32.t -> t
end
class sizeStatistics :
object ('a)
  method get_unencoded_byte_array_data_bytes : Int64.t option
  method grab_unencoded_byte_array_data_bytes : Int64.t
  method set_unencoded_byte_array_data_bytes : Int64.t -> unit
  method unset_unencoded_byte_array_data_bytes : unit
  method reset_unencoded_byte_array_data_bytes : unit
  method get_repetition_level_histogram : Int64.t list option
  method grab_repetition_level_histogram : Int64.t list
  method set_repetition_level_histogram : Int64.t list -> unit
  method unset_repetition_level_histogram : unit
  method reset_repetition_level_histogram : unit
  method get_definition_level_histogram : Int64.t list option
  method grab_definition_level_histogram : Int64.t list
  method set_definition_level_histogram : Int64.t list -> unit
  method unset_definition_level_histogram : unit
  method reset_definition_level_histogram : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_sizeStatistics : Protocol.t -> sizeStatistics
class boundingBox :
object ('a)
  method get_xmin : float option
  method grab_xmin : float
  method set_xmin : float -> unit
  method unset_xmin : unit
  method reset_xmin : unit
  method get_xmax : float option
  method grab_xmax : float
  method set_xmax : float -> unit
  method unset_xmax : unit
  method reset_xmax : unit
  method get_ymin : float option
  method grab_ymin : float
  method set_ymin : float -> unit
  method unset_ymin : unit
  method reset_ymin : unit
  method get_ymax : float option
  method grab_ymax : float
  method set_ymax : float -> unit
  method unset_ymax : unit
  method reset_ymax : unit
  method get_zmin : float option
  method grab_zmin : float
  method set_zmin : float -> unit
  method unset_zmin : unit
  method reset_zmin : unit
  method get_zmax : float option
  method grab_zmax : float
  method set_zmax : float -> unit
  method unset_zmax : unit
  method reset_zmax : unit
  method get_mmin : float option
  method grab_mmin : float
  method set_mmin : float -> unit
  method unset_mmin : unit
  method reset_mmin : unit
  method get_mmax : float option
  method grab_mmax : float
  method set_mmax : float -> unit
  method unset_mmax : unit
  method reset_mmax : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_boundingBox : Protocol.t -> boundingBox
class geospatialStatistics :
object ('a)
  method get_bbox : boundingBox option
  method grab_bbox : boundingBox
  method set_bbox : boundingBox -> unit
  method unset_bbox : unit
  method reset_bbox : unit
  method get_geospatial_types : Int32.t list option
  method grab_geospatial_types : Int32.t list
  method set_geospatial_types : Int32.t list -> unit
  method unset_geospatial_types : unit
  method reset_geospatial_types : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_geospatialStatistics : Protocol.t -> geospatialStatistics
class statistics :
object ('a)
  method get_max : string option
  method grab_max : string
  method set_max : string -> unit
  method unset_max : unit
  method reset_max : unit
  method get_min : string option
  method grab_min : string
  method set_min : string -> unit
  method unset_min : unit
  method reset_min : unit
  method get_null_count : Int64.t option
  method grab_null_count : Int64.t
  method set_null_count : Int64.t -> unit
  method unset_null_count : unit
  method reset_null_count : unit
  method get_distinct_count : Int64.t option
  method grab_distinct_count : Int64.t
  method set_distinct_count : Int64.t -> unit
  method unset_distinct_count : unit
  method reset_distinct_count : unit
  method get_max_value : string option
  method grab_max_value : string
  method set_max_value : string -> unit
  method unset_max_value : unit
  method reset_max_value : unit
  method get_min_value : string option
  method grab_min_value : string
  method set_min_value : string -> unit
  method unset_min_value : unit
  method reset_min_value : unit
  method get_is_max_value_exact : bool option
  method grab_is_max_value_exact : bool
  method set_is_max_value_exact : bool -> unit
  method unset_is_max_value_exact : unit
  method reset_is_max_value_exact : unit
  method get_is_min_value_exact : bool option
  method grab_is_min_value_exact : bool
  method set_is_min_value_exact : bool -> unit
  method unset_is_min_value_exact : unit
  method reset_is_min_value_exact : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_statistics : Protocol.t -> statistics
class stringType :
object ('a)
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_stringType : Protocol.t -> stringType
class uUIDType :
object ('a)
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_uUIDType : Protocol.t -> uUIDType
class mapType :
object ('a)
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_mapType : Protocol.t -> mapType
class listType :
object ('a)
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_listType : Protocol.t -> listType
class enumType :
object ('a)
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_enumType : Protocol.t -> enumType
class dateType :
object ('a)
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_dateType : Protocol.t -> dateType
class float16Type :
object ('a)
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_float16Type : Protocol.t -> float16Type
class nullType :
object ('a)
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_nullType : Protocol.t -> nullType
class decimalType :
object ('a)
  method get_scale : Int32.t option
  method grab_scale : Int32.t
  method set_scale : Int32.t -> unit
  method unset_scale : unit
  method reset_scale : unit
  method get_precision : Int32.t option
  method grab_precision : Int32.t
  method set_precision : Int32.t -> unit
  method unset_precision : unit
  method reset_precision : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_decimalType : Protocol.t -> decimalType
class milliSeconds :
object ('a)
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_milliSeconds : Protocol.t -> milliSeconds
class microSeconds :
object ('a)
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_microSeconds : Protocol.t -> microSeconds
class nanoSeconds :
object ('a)
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_nanoSeconds : Protocol.t -> nanoSeconds
class timeUnit :
object ('a)
  method get_mILLIS : milliSeconds option
  method grab_mILLIS : milliSeconds
  method set_mILLIS : milliSeconds -> unit
  method unset_mILLIS : unit
  method reset_mILLIS : unit
  method get_mICROS : microSeconds option
  method grab_mICROS : microSeconds
  method set_mICROS : microSeconds -> unit
  method unset_mICROS : unit
  method reset_mICROS : unit
  method get_nANOS : nanoSeconds option
  method grab_nANOS : nanoSeconds
  method set_nANOS : nanoSeconds -> unit
  method unset_nANOS : unit
  method reset_nANOS : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_timeUnit : Protocol.t -> timeUnit
class timestampType :
object ('a)
  method get_isAdjustedToUTC : bool option
  method grab_isAdjustedToUTC : bool
  method set_isAdjustedToUTC : bool -> unit
  method unset_isAdjustedToUTC : unit
  method reset_isAdjustedToUTC : unit
  method get_unit : timeUnit option
  method grab_unit : timeUnit
  method set_unit : timeUnit -> unit
  method unset_unit : unit
  method reset_unit : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_timestampType : Protocol.t -> timestampType
class timeType :
object ('a)
  method get_isAdjustedToUTC : bool option
  method grab_isAdjustedToUTC : bool
  method set_isAdjustedToUTC : bool -> unit
  method unset_isAdjustedToUTC : unit
  method reset_isAdjustedToUTC : unit
  method get_unit : timeUnit option
  method grab_unit : timeUnit
  method set_unit : timeUnit -> unit
  method unset_unit : unit
  method reset_unit : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_timeType : Protocol.t -> timeType
class intType :
object ('a)
  method get_bitWidth : int option
  method grab_bitWidth : int
  method set_bitWidth : int -> unit
  method unset_bitWidth : unit
  method reset_bitWidth : unit
  method get_isSigned : bool option
  method grab_isSigned : bool
  method set_isSigned : bool -> unit
  method unset_isSigned : unit
  method reset_isSigned : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_intType : Protocol.t -> intType
class jsonType :
object ('a)
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_jsonType : Protocol.t -> jsonType
class bsonType :
object ('a)
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_bsonType : Protocol.t -> bsonType
class variantType :
object ('a)
  method get_specification_version : int option
  method grab_specification_version : int
  method set_specification_version : int -> unit
  method unset_specification_version : unit
  method reset_specification_version : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_variantType : Protocol.t -> variantType
class geometryType :
object ('a)
  method get_crs : string option
  method grab_crs : string
  method set_crs : string -> unit
  method unset_crs : unit
  method reset_crs : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_geometryType : Protocol.t -> geometryType
class geographyType :
object ('a)
  method get_crs : string option
  method grab_crs : string
  method set_crs : string -> unit
  method unset_crs : unit
  method reset_crs : unit
  method get_algorithm : EdgeInterpolationAlgorithm.t option
  method grab_algorithm : EdgeInterpolationAlgorithm.t
  method set_algorithm : EdgeInterpolationAlgorithm.t -> unit
  method unset_algorithm : unit
  method reset_algorithm : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_geographyType : Protocol.t -> geographyType
class logicalType :
object ('a)
  method get_sTRING : stringType option
  method grab_sTRING : stringType
  method set_sTRING : stringType -> unit
  method unset_sTRING : unit
  method reset_sTRING : unit
  method get_mAP : mapType option
  method grab_mAP : mapType
  method set_mAP : mapType -> unit
  method unset_mAP : unit
  method reset_mAP : unit
  method get_lIST : listType option
  method grab_lIST : listType
  method set_lIST : listType -> unit
  method unset_lIST : unit
  method reset_lIST : unit
  method get_eNUM : enumType option
  method grab_eNUM : enumType
  method set_eNUM : enumType -> unit
  method unset_eNUM : unit
  method reset_eNUM : unit
  method get_dECIMAL : decimalType option
  method grab_dECIMAL : decimalType
  method set_dECIMAL : decimalType -> unit
  method unset_dECIMAL : unit
  method reset_dECIMAL : unit
  method get_dATE : dateType option
  method grab_dATE : dateType
  method set_dATE : dateType -> unit
  method unset_dATE : unit
  method reset_dATE : unit
  method get_tIME : timeType option
  method grab_tIME : timeType
  method set_tIME : timeType -> unit
  method unset_tIME : unit
  method reset_tIME : unit
  method get_tIMESTAMP : timestampType option
  method grab_tIMESTAMP : timestampType
  method set_tIMESTAMP : timestampType -> unit
  method unset_tIMESTAMP : unit
  method reset_tIMESTAMP : unit
  method get_iNTEGER : intType option
  method grab_iNTEGER : intType
  method set_iNTEGER : intType -> unit
  method unset_iNTEGER : unit
  method reset_iNTEGER : unit
  method get_uNKNOWN : nullType option
  method grab_uNKNOWN : nullType
  method set_uNKNOWN : nullType -> unit
  method unset_uNKNOWN : unit
  method reset_uNKNOWN : unit
  method get_jSON : jsonType option
  method grab_jSON : jsonType
  method set_jSON : jsonType -> unit
  method unset_jSON : unit
  method reset_jSON : unit
  method get_bSON : bsonType option
  method grab_bSON : bsonType
  method set_bSON : bsonType -> unit
  method unset_bSON : unit
  method reset_bSON : unit
  method get_uUID : uUIDType option
  method grab_uUID : uUIDType
  method set_uUID : uUIDType -> unit
  method unset_uUID : unit
  method reset_uUID : unit
  method get_fLOAT16 : float16Type option
  method grab_fLOAT16 : float16Type
  method set_fLOAT16 : float16Type -> unit
  method unset_fLOAT16 : unit
  method reset_fLOAT16 : unit
  method get_vARIANT : variantType option
  method grab_vARIANT : variantType
  method set_vARIANT : variantType -> unit
  method unset_vARIANT : unit
  method reset_vARIANT : unit
  method get_gEOMETRY : geometryType option
  method grab_gEOMETRY : geometryType
  method set_gEOMETRY : geometryType -> unit
  method unset_gEOMETRY : unit
  method reset_gEOMETRY : unit
  method get_gEOGRAPHY : geographyType option
  method grab_gEOGRAPHY : geographyType
  method set_gEOGRAPHY : geographyType -> unit
  method unset_gEOGRAPHY : unit
  method reset_gEOGRAPHY : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_logicalType : Protocol.t -> logicalType
class schemaElement :
object ('a)
  method get_type : Type.t option
  method grab_type : Type.t
  method set_type : Type.t -> unit
  method unset_type : unit
  method reset_type : unit
  method get_type_length : Int32.t option
  method grab_type_length : Int32.t
  method set_type_length : Int32.t -> unit
  method unset_type_length : unit
  method reset_type_length : unit
  method get_repetition_type : FieldRepetitionType.t option
  method grab_repetition_type : FieldRepetitionType.t
  method set_repetition_type : FieldRepetitionType.t -> unit
  method unset_repetition_type : unit
  method reset_repetition_type : unit
  method get_name : string option
  method grab_name : string
  method set_name : string -> unit
  method unset_name : unit
  method reset_name : unit
  method get_num_children : Int32.t option
  method grab_num_children : Int32.t
  method set_num_children : Int32.t -> unit
  method unset_num_children : unit
  method reset_num_children : unit
  method get_converted_type : ConvertedType.t option
  method grab_converted_type : ConvertedType.t
  method set_converted_type : ConvertedType.t -> unit
  method unset_converted_type : unit
  method reset_converted_type : unit
  method get_scale : Int32.t option
  method grab_scale : Int32.t
  method set_scale : Int32.t -> unit
  method unset_scale : unit
  method reset_scale : unit
  method get_precision : Int32.t option
  method grab_precision : Int32.t
  method set_precision : Int32.t -> unit
  method unset_precision : unit
  method reset_precision : unit
  method get_field_id : Int32.t option
  method grab_field_id : Int32.t
  method set_field_id : Int32.t -> unit
  method unset_field_id : unit
  method reset_field_id : unit
  method get_logicalType : logicalType option
  method grab_logicalType : logicalType
  method set_logicalType : logicalType -> unit
  method unset_logicalType : unit
  method reset_logicalType : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_schemaElement : Protocol.t -> schemaElement
class dataPageHeader :
object ('a)
  method get_num_values : Int32.t option
  method grab_num_values : Int32.t
  method set_num_values : Int32.t -> unit
  method unset_num_values : unit
  method reset_num_values : unit
  method get_encoding : Encoding.t option
  method grab_encoding : Encoding.t
  method set_encoding : Encoding.t -> unit
  method unset_encoding : unit
  method reset_encoding : unit
  method get_definition_level_encoding : Encoding.t option
  method grab_definition_level_encoding : Encoding.t
  method set_definition_level_encoding : Encoding.t -> unit
  method unset_definition_level_encoding : unit
  method reset_definition_level_encoding : unit
  method get_repetition_level_encoding : Encoding.t option
  method grab_repetition_level_encoding : Encoding.t
  method set_repetition_level_encoding : Encoding.t -> unit
  method unset_repetition_level_encoding : unit
  method reset_repetition_level_encoding : unit
  method get_statistics : statistics option
  method grab_statistics : statistics
  method set_statistics : statistics -> unit
  method unset_statistics : unit
  method reset_statistics : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_dataPageHeader : Protocol.t -> dataPageHeader
class indexPageHeader :
object ('a)
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_indexPageHeader : Protocol.t -> indexPageHeader
class dictionaryPageHeader :
object ('a)
  method get_num_values : Int32.t option
  method grab_num_values : Int32.t
  method set_num_values : Int32.t -> unit
  method unset_num_values : unit
  method reset_num_values : unit
  method get_encoding : Encoding.t option
  method grab_encoding : Encoding.t
  method set_encoding : Encoding.t -> unit
  method unset_encoding : unit
  method reset_encoding : unit
  method get_is_sorted : bool option
  method grab_is_sorted : bool
  method set_is_sorted : bool -> unit
  method unset_is_sorted : unit
  method reset_is_sorted : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_dictionaryPageHeader : Protocol.t -> dictionaryPageHeader
class dataPageHeaderV2 :
object ('a)
  method get_num_values : Int32.t option
  method grab_num_values : Int32.t
  method set_num_values : Int32.t -> unit
  method unset_num_values : unit
  method reset_num_values : unit
  method get_num_nulls : Int32.t option
  method grab_num_nulls : Int32.t
  method set_num_nulls : Int32.t -> unit
  method unset_num_nulls : unit
  method reset_num_nulls : unit
  method get_num_rows : Int32.t option
  method grab_num_rows : Int32.t
  method set_num_rows : Int32.t -> unit
  method unset_num_rows : unit
  method reset_num_rows : unit
  method get_encoding : Encoding.t option
  method grab_encoding : Encoding.t
  method set_encoding : Encoding.t -> unit
  method unset_encoding : unit
  method reset_encoding : unit
  method get_definition_levels_byte_length : Int32.t option
  method grab_definition_levels_byte_length : Int32.t
  method set_definition_levels_byte_length : Int32.t -> unit
  method unset_definition_levels_byte_length : unit
  method reset_definition_levels_byte_length : unit
  method get_repetition_levels_byte_length : Int32.t option
  method grab_repetition_levels_byte_length : Int32.t
  method set_repetition_levels_byte_length : Int32.t -> unit
  method unset_repetition_levels_byte_length : unit
  method reset_repetition_levels_byte_length : unit
  method get_is_compressed : bool option
  method grab_is_compressed : bool
  method set_is_compressed : bool -> unit
  method reset_is_compressed : unit
  method get_statistics : statistics option
  method grab_statistics : statistics
  method set_statistics : statistics -> unit
  method unset_statistics : unit
  method reset_statistics : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_dataPageHeaderV2 : Protocol.t -> dataPageHeaderV2
class splitBlockAlgorithm :
object ('a)
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_splitBlockAlgorithm : Protocol.t -> splitBlockAlgorithm
class bloomFilterAlgorithm :
object ('a)
  method get_bLOCK : splitBlockAlgorithm option
  method grab_bLOCK : splitBlockAlgorithm
  method set_bLOCK : splitBlockAlgorithm -> unit
  method unset_bLOCK : unit
  method reset_bLOCK : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_bloomFilterAlgorithm : Protocol.t -> bloomFilterAlgorithm
class xxHash :
object ('a)
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_xxHash : Protocol.t -> xxHash
class bloomFilterHash :
object ('a)
  method get_xXHASH : xxHash option
  method grab_xXHASH : xxHash
  method set_xXHASH : xxHash -> unit
  method unset_xXHASH : unit
  method reset_xXHASH : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_bloomFilterHash : Protocol.t -> bloomFilterHash
class uncompressed :
object ('a)
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_uncompressed : Protocol.t -> uncompressed
class bloomFilterCompression :
object ('a)
  method get_uNCOMPRESSED : uncompressed option
  method grab_uNCOMPRESSED : uncompressed
  method set_uNCOMPRESSED : uncompressed -> unit
  method unset_uNCOMPRESSED : unit
  method reset_uNCOMPRESSED : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_bloomFilterCompression : Protocol.t -> bloomFilterCompression
class bloomFilterHeader :
object ('a)
  method get_numBytes : Int32.t option
  method grab_numBytes : Int32.t
  method set_numBytes : Int32.t -> unit
  method unset_numBytes : unit
  method reset_numBytes : unit
  method get_algorithm : bloomFilterAlgorithm option
  method grab_algorithm : bloomFilterAlgorithm
  method set_algorithm : bloomFilterAlgorithm -> unit
  method unset_algorithm : unit
  method reset_algorithm : unit
  method get_hash : bloomFilterHash option
  method grab_hash : bloomFilterHash
  method set_hash : bloomFilterHash -> unit
  method unset_hash : unit
  method reset_hash : unit
  method get_compression : bloomFilterCompression option
  method grab_compression : bloomFilterCompression
  method set_compression : bloomFilterCompression -> unit
  method unset_compression : unit
  method reset_compression : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_bloomFilterHeader : Protocol.t -> bloomFilterHeader
class pageHeader :
object ('a)
  method get_type : PageType.t option
  method grab_type : PageType.t
  method set_type : PageType.t -> unit
  method unset_type : unit
  method reset_type : unit
  method get_uncompressed_page_size : Int32.t option
  method grab_uncompressed_page_size : Int32.t
  method set_uncompressed_page_size : Int32.t -> unit
  method unset_uncompressed_page_size : unit
  method reset_uncompressed_page_size : unit
  method get_compressed_page_size : Int32.t option
  method grab_compressed_page_size : Int32.t
  method set_compressed_page_size : Int32.t -> unit
  method unset_compressed_page_size : unit
  method reset_compressed_page_size : unit
  method get_crc : Int32.t option
  method grab_crc : Int32.t
  method set_crc : Int32.t -> unit
  method unset_crc : unit
  method reset_crc : unit
  method get_data_page_header : dataPageHeader option
  method grab_data_page_header : dataPageHeader
  method set_data_page_header : dataPageHeader -> unit
  method unset_data_page_header : unit
  method reset_data_page_header : unit
  method get_index_page_header : indexPageHeader option
  method grab_index_page_header : indexPageHeader
  method set_index_page_header : indexPageHeader -> unit
  method unset_index_page_header : unit
  method reset_index_page_header : unit
  method get_dictionary_page_header : dictionaryPageHeader option
  method grab_dictionary_page_header : dictionaryPageHeader
  method set_dictionary_page_header : dictionaryPageHeader -> unit
  method unset_dictionary_page_header : unit
  method reset_dictionary_page_header : unit
  method get_data_page_header_v2 : dataPageHeaderV2 option
  method grab_data_page_header_v2 : dataPageHeaderV2
  method set_data_page_header_v2 : dataPageHeaderV2 -> unit
  method unset_data_page_header_v2 : unit
  method reset_data_page_header_v2 : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_pageHeader : Protocol.t -> pageHeader
class keyValue :
object ('a)
  method get_key : string option
  method grab_key : string
  method set_key : string -> unit
  method unset_key : unit
  method reset_key : unit
  method get_value : string option
  method grab_value : string
  method set_value : string -> unit
  method unset_value : unit
  method reset_value : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_keyValue : Protocol.t -> keyValue
class sortingColumn :
object ('a)
  method get_column_idx : Int32.t option
  method grab_column_idx : Int32.t
  method set_column_idx : Int32.t -> unit
  method unset_column_idx : unit
  method reset_column_idx : unit
  method get_descending : bool option
  method grab_descending : bool
  method set_descending : bool -> unit
  method unset_descending : unit
  method reset_descending : unit
  method get_nulls_first : bool option
  method grab_nulls_first : bool
  method set_nulls_first : bool -> unit
  method unset_nulls_first : unit
  method reset_nulls_first : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_sortingColumn : Protocol.t -> sortingColumn
class pageEncodingStats :
object ('a)
  method get_page_type : PageType.t option
  method grab_page_type : PageType.t
  method set_page_type : PageType.t -> unit
  method unset_page_type : unit
  method reset_page_type : unit
  method get_encoding : Encoding.t option
  method grab_encoding : Encoding.t
  method set_encoding : Encoding.t -> unit
  method unset_encoding : unit
  method reset_encoding : unit
  method get_count : Int32.t option
  method grab_count : Int32.t
  method set_count : Int32.t -> unit
  method unset_count : unit
  method reset_count : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_pageEncodingStats : Protocol.t -> pageEncodingStats
class columnMetaData :
object ('a)
  method get_type : Type.t option
  method grab_type : Type.t
  method set_type : Type.t -> unit
  method unset_type : unit
  method reset_type : unit
  method get_encodings : Encoding.t list option
  method grab_encodings : Encoding.t list
  method set_encodings : Encoding.t list -> unit
  method unset_encodings : unit
  method reset_encodings : unit
  method get_path_in_schema : string list option
  method grab_path_in_schema : string list
  method set_path_in_schema : string list -> unit
  method unset_path_in_schema : unit
  method reset_path_in_schema : unit
  method get_codec : CompressionCodec.t option
  method grab_codec : CompressionCodec.t
  method set_codec : CompressionCodec.t -> unit
  method unset_codec : unit
  method reset_codec : unit
  method get_num_values : Int64.t option
  method grab_num_values : Int64.t
  method set_num_values : Int64.t -> unit
  method unset_num_values : unit
  method reset_num_values : unit
  method get_total_uncompressed_size : Int64.t option
  method grab_total_uncompressed_size : Int64.t
  method set_total_uncompressed_size : Int64.t -> unit
  method unset_total_uncompressed_size : unit
  method reset_total_uncompressed_size : unit
  method get_total_compressed_size : Int64.t option
  method grab_total_compressed_size : Int64.t
  method set_total_compressed_size : Int64.t -> unit
  method unset_total_compressed_size : unit
  method reset_total_compressed_size : unit
  method get_key_value_metadata : keyValue list option
  method grab_key_value_metadata : keyValue list
  method set_key_value_metadata : keyValue list -> unit
  method unset_key_value_metadata : unit
  method reset_key_value_metadata : unit
  method get_data_page_offset : Int64.t option
  method grab_data_page_offset : Int64.t
  method set_data_page_offset : Int64.t -> unit
  method unset_data_page_offset : unit
  method reset_data_page_offset : unit
  method get_index_page_offset : Int64.t option
  method grab_index_page_offset : Int64.t
  method set_index_page_offset : Int64.t -> unit
  method unset_index_page_offset : unit
  method reset_index_page_offset : unit
  method get_dictionary_page_offset : Int64.t option
  method grab_dictionary_page_offset : Int64.t
  method set_dictionary_page_offset : Int64.t -> unit
  method unset_dictionary_page_offset : unit
  method reset_dictionary_page_offset : unit
  method get_statistics : statistics option
  method grab_statistics : statistics
  method set_statistics : statistics -> unit
  method unset_statistics : unit
  method reset_statistics : unit
  method get_encoding_stats : pageEncodingStats list option
  method grab_encoding_stats : pageEncodingStats list
  method set_encoding_stats : pageEncodingStats list -> unit
  method unset_encoding_stats : unit
  method reset_encoding_stats : unit
  method get_bloom_filter_offset : Int64.t option
  method grab_bloom_filter_offset : Int64.t
  method set_bloom_filter_offset : Int64.t -> unit
  method unset_bloom_filter_offset : unit
  method reset_bloom_filter_offset : unit
  method get_bloom_filter_length : Int32.t option
  method grab_bloom_filter_length : Int32.t
  method set_bloom_filter_length : Int32.t -> unit
  method unset_bloom_filter_length : unit
  method reset_bloom_filter_length : unit
  method get_size_statistics : sizeStatistics option
  method grab_size_statistics : sizeStatistics
  method set_size_statistics : sizeStatistics -> unit
  method unset_size_statistics : unit
  method reset_size_statistics : unit
  method get_geospatial_statistics : geospatialStatistics option
  method grab_geospatial_statistics : geospatialStatistics
  method set_geospatial_statistics : geospatialStatistics -> unit
  method unset_geospatial_statistics : unit
  method reset_geospatial_statistics : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_columnMetaData : Protocol.t -> columnMetaData
class encryptionWithFooterKey :
object ('a)
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_encryptionWithFooterKey : Protocol.t -> encryptionWithFooterKey
class encryptionWithColumnKey :
object ('a)
  method get_path_in_schema : string list option
  method grab_path_in_schema : string list
  method set_path_in_schema : string list -> unit
  method unset_path_in_schema : unit
  method reset_path_in_schema : unit
  method get_key_metadata : string option
  method grab_key_metadata : string
  method set_key_metadata : string -> unit
  method unset_key_metadata : unit
  method reset_key_metadata : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_encryptionWithColumnKey : Protocol.t -> encryptionWithColumnKey
class columnCryptoMetaData :
object ('a)
  method get_eNCRYPTION_WITH_FOOTER_KEY : encryptionWithFooterKey option
  method grab_eNCRYPTION_WITH_FOOTER_KEY : encryptionWithFooterKey
  method set_eNCRYPTION_WITH_FOOTER_KEY : encryptionWithFooterKey -> unit
  method unset_eNCRYPTION_WITH_FOOTER_KEY : unit
  method reset_eNCRYPTION_WITH_FOOTER_KEY : unit
  method get_eNCRYPTION_WITH_COLUMN_KEY : encryptionWithColumnKey option
  method grab_eNCRYPTION_WITH_COLUMN_KEY : encryptionWithColumnKey
  method set_eNCRYPTION_WITH_COLUMN_KEY : encryptionWithColumnKey -> unit
  method unset_eNCRYPTION_WITH_COLUMN_KEY : unit
  method reset_eNCRYPTION_WITH_COLUMN_KEY : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_columnCryptoMetaData : Protocol.t -> columnCryptoMetaData
class columnChunk :
object ('a)
  method get_file_path : string option
  method grab_file_path : string
  method set_file_path : string -> unit
  method unset_file_path : unit
  method reset_file_path : unit
  method get_file_offset : Int64.t option
  method grab_file_offset : Int64.t
  method set_file_offset : Int64.t -> unit
  method reset_file_offset : unit
  method get_meta_data : columnMetaData option
  method grab_meta_data : columnMetaData
  method set_meta_data : columnMetaData -> unit
  method unset_meta_data : unit
  method reset_meta_data : unit
  method get_offset_index_offset : Int64.t option
  method grab_offset_index_offset : Int64.t
  method set_offset_index_offset : Int64.t -> unit
  method unset_offset_index_offset : unit
  method reset_offset_index_offset : unit
  method get_offset_index_length : Int32.t option
  method grab_offset_index_length : Int32.t
  method set_offset_index_length : Int32.t -> unit
  method unset_offset_index_length : unit
  method reset_offset_index_length : unit
  method get_column_index_offset : Int64.t option
  method grab_column_index_offset : Int64.t
  method set_column_index_offset : Int64.t -> unit
  method unset_column_index_offset : unit
  method reset_column_index_offset : unit
  method get_column_index_length : Int32.t option
  method grab_column_index_length : Int32.t
  method set_column_index_length : Int32.t -> unit
  method unset_column_index_length : unit
  method reset_column_index_length : unit
  method get_crypto_metadata : columnCryptoMetaData option
  method grab_crypto_metadata : columnCryptoMetaData
  method set_crypto_metadata : columnCryptoMetaData -> unit
  method unset_crypto_metadata : unit
  method reset_crypto_metadata : unit
  method get_encrypted_column_metadata : string option
  method grab_encrypted_column_metadata : string
  method set_encrypted_column_metadata : string -> unit
  method unset_encrypted_column_metadata : unit
  method reset_encrypted_column_metadata : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_columnChunk : Protocol.t -> columnChunk
class rowGroup :
object ('a)
  method get_columns : columnChunk list option
  method grab_columns : columnChunk list
  method set_columns : columnChunk list -> unit
  method unset_columns : unit
  method reset_columns : unit
  method get_total_byte_size : Int64.t option
  method grab_total_byte_size : Int64.t
  method set_total_byte_size : Int64.t -> unit
  method unset_total_byte_size : unit
  method reset_total_byte_size : unit
  method get_num_rows : Int64.t option
  method grab_num_rows : Int64.t
  method set_num_rows : Int64.t -> unit
  method unset_num_rows : unit
  method reset_num_rows : unit
  method get_sorting_columns : sortingColumn list option
  method grab_sorting_columns : sortingColumn list
  method set_sorting_columns : sortingColumn list -> unit
  method unset_sorting_columns : unit
  method reset_sorting_columns : unit
  method get_file_offset : Int64.t option
  method grab_file_offset : Int64.t
  method set_file_offset : Int64.t -> unit
  method unset_file_offset : unit
  method reset_file_offset : unit
  method get_total_compressed_size : Int64.t option
  method grab_total_compressed_size : Int64.t
  method set_total_compressed_size : Int64.t -> unit
  method unset_total_compressed_size : unit
  method reset_total_compressed_size : unit
  method get_ordinal : int option
  method grab_ordinal : int
  method set_ordinal : int -> unit
  method unset_ordinal : unit
  method reset_ordinal : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_rowGroup : Protocol.t -> rowGroup
class typeDefinedOrder :
object ('a)
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_typeDefinedOrder : Protocol.t -> typeDefinedOrder
class columnOrder :
object ('a)
  method get_tYPE_ORDER : typeDefinedOrder option
  method grab_tYPE_ORDER : typeDefinedOrder
  method set_tYPE_ORDER : typeDefinedOrder -> unit
  method unset_tYPE_ORDER : unit
  method reset_tYPE_ORDER : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_columnOrder : Protocol.t -> columnOrder
class pageLocation :
object ('a)
  method get_offset : Int64.t option
  method grab_offset : Int64.t
  method set_offset : Int64.t -> unit
  method unset_offset : unit
  method reset_offset : unit
  method get_compressed_page_size : Int32.t option
  method grab_compressed_page_size : Int32.t
  method set_compressed_page_size : Int32.t -> unit
  method unset_compressed_page_size : unit
  method reset_compressed_page_size : unit
  method get_first_row_index : Int64.t option
  method grab_first_row_index : Int64.t
  method set_first_row_index : Int64.t -> unit
  method unset_first_row_index : unit
  method reset_first_row_index : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_pageLocation : Protocol.t -> pageLocation
class offsetIndex :
object ('a)
  method get_page_locations : pageLocation list option
  method grab_page_locations : pageLocation list
  method set_page_locations : pageLocation list -> unit
  method unset_page_locations : unit
  method reset_page_locations : unit
  method get_unencoded_byte_array_data_bytes : Int64.t list option
  method grab_unencoded_byte_array_data_bytes : Int64.t list
  method set_unencoded_byte_array_data_bytes : Int64.t list -> unit
  method unset_unencoded_byte_array_data_bytes : unit
  method reset_unencoded_byte_array_data_bytes : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_offsetIndex : Protocol.t -> offsetIndex
class columnIndex :
object ('a)
  method get_null_pages : bool list option
  method grab_null_pages : bool list
  method set_null_pages : bool list -> unit
  method unset_null_pages : unit
  method reset_null_pages : unit
  method get_min_values : string list option
  method grab_min_values : string list
  method set_min_values : string list -> unit
  method unset_min_values : unit
  method reset_min_values : unit
  method get_max_values : string list option
  method grab_max_values : string list
  method set_max_values : string list -> unit
  method unset_max_values : unit
  method reset_max_values : unit
  method get_boundary_order : BoundaryOrder.t option
  method grab_boundary_order : BoundaryOrder.t
  method set_boundary_order : BoundaryOrder.t -> unit
  method unset_boundary_order : unit
  method reset_boundary_order : unit
  method get_null_counts : Int64.t list option
  method grab_null_counts : Int64.t list
  method set_null_counts : Int64.t list -> unit
  method unset_null_counts : unit
  method reset_null_counts : unit
  method get_repetition_level_histograms : Int64.t list option
  method grab_repetition_level_histograms : Int64.t list
  method set_repetition_level_histograms : Int64.t list -> unit
  method unset_repetition_level_histograms : unit
  method reset_repetition_level_histograms : unit
  method get_definition_level_histograms : Int64.t list option
  method grab_definition_level_histograms : Int64.t list
  method set_definition_level_histograms : Int64.t list -> unit
  method unset_definition_level_histograms : unit
  method reset_definition_level_histograms : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_columnIndex : Protocol.t -> columnIndex
class aesGcmV1 :
object ('a)
  method get_aad_prefix : string option
  method grab_aad_prefix : string
  method set_aad_prefix : string -> unit
  method unset_aad_prefix : unit
  method reset_aad_prefix : unit
  method get_aad_file_unique : string option
  method grab_aad_file_unique : string
  method set_aad_file_unique : string -> unit
  method unset_aad_file_unique : unit
  method reset_aad_file_unique : unit
  method get_supply_aad_prefix : bool option
  method grab_supply_aad_prefix : bool
  method set_supply_aad_prefix : bool -> unit
  method unset_supply_aad_prefix : unit
  method reset_supply_aad_prefix : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_aesGcmV1 : Protocol.t -> aesGcmV1
class aesGcmCtrV1 :
object ('a)
  method get_aad_prefix : string option
  method grab_aad_prefix : string
  method set_aad_prefix : string -> unit
  method unset_aad_prefix : unit
  method reset_aad_prefix : unit
  method get_aad_file_unique : string option
  method grab_aad_file_unique : string
  method set_aad_file_unique : string -> unit
  method unset_aad_file_unique : unit
  method reset_aad_file_unique : unit
  method get_supply_aad_prefix : bool option
  method grab_supply_aad_prefix : bool
  method set_supply_aad_prefix : bool -> unit
  method unset_supply_aad_prefix : unit
  method reset_supply_aad_prefix : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_aesGcmCtrV1 : Protocol.t -> aesGcmCtrV1
class encryptionAlgorithm :
object ('a)
  method get_aES_GCM_V1 : aesGcmV1 option
  method grab_aES_GCM_V1 : aesGcmV1
  method set_aES_GCM_V1 : aesGcmV1 -> unit
  method unset_aES_GCM_V1 : unit
  method reset_aES_GCM_V1 : unit
  method get_aES_GCM_CTR_V1 : aesGcmCtrV1 option
  method grab_aES_GCM_CTR_V1 : aesGcmCtrV1
  method set_aES_GCM_CTR_V1 : aesGcmCtrV1 -> unit
  method unset_aES_GCM_CTR_V1 : unit
  method reset_aES_GCM_CTR_V1 : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_encryptionAlgorithm : Protocol.t -> encryptionAlgorithm
class fileMetaData :
object ('a)
  method get_version : Int32.t option
  method grab_version : Int32.t
  method set_version : Int32.t -> unit
  method unset_version : unit
  method reset_version : unit
  method get_schema : schemaElement list option
  method grab_schema : schemaElement list
  method set_schema : schemaElement list -> unit
  method unset_schema : unit
  method reset_schema : unit
  method get_num_rows : Int64.t option
  method grab_num_rows : Int64.t
  method set_num_rows : Int64.t -> unit
  method unset_num_rows : unit
  method reset_num_rows : unit
  method get_row_groups : rowGroup list option
  method grab_row_groups : rowGroup list
  method set_row_groups : rowGroup list -> unit
  method unset_row_groups : unit
  method reset_row_groups : unit
  method get_key_value_metadata : keyValue list option
  method grab_key_value_metadata : keyValue list
  method set_key_value_metadata : keyValue list -> unit
  method unset_key_value_metadata : unit
  method reset_key_value_metadata : unit
  method get_created_by : string option
  method grab_created_by : string
  method set_created_by : string -> unit
  method unset_created_by : unit
  method reset_created_by : unit
  method get_column_orders : columnOrder list option
  method grab_column_orders : columnOrder list
  method set_column_orders : columnOrder list -> unit
  method unset_column_orders : unit
  method reset_column_orders : unit
  method get_encryption_algorithm : encryptionAlgorithm option
  method grab_encryption_algorithm : encryptionAlgorithm
  method set_encryption_algorithm : encryptionAlgorithm -> unit
  method unset_encryption_algorithm : unit
  method reset_encryption_algorithm : unit
  method get_footer_signing_key_metadata : string option
  method grab_footer_signing_key_metadata : string
  method set_footer_signing_key_metadata : string -> unit
  method unset_footer_signing_key_metadata : unit
  method reset_footer_signing_key_metadata : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_fileMetaData : Protocol.t -> fileMetaData
class fileCryptoMetaData :
object ('a)
  method get_encryption_algorithm : encryptionAlgorithm option
  method grab_encryption_algorithm : encryptionAlgorithm
  method set_encryption_algorithm : encryptionAlgorithm -> unit
  method unset_encryption_algorithm : unit
  method reset_encryption_algorithm : unit
  method get_key_metadata : string option
  method grab_key_metadata : string
  method set_key_metadata : string -> unit
  method unset_key_metadata : unit
  method reset_key_metadata : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_fileCryptoMetaData : Protocol.t -> fileCryptoMetaData
