all: verify

EVERCBOR_SRC_PATH = $(realpath ../../..)
INCLUDE_PATHS += $(realpath ..) $(realpath ../..)
ALREADY_CACHED := *,-CBOR.Pulse.Raw,

include $(EVERCBOR_SRC_PATH)/pulse.Makefile
include $(EVERCBOR_SRC_PATH)/common.Makefile
