

#ifndef COSE_Format_H
#define COSE_Format_H

#include "krmllib.h"

#include "CBORDetAPI.h"
#include "CBORDetType.h"

bool COSE_Format_validate_bool(cbor_det_t c);

typedef bool COSE_Format_evercddl_bool_ugly;

typedef bool COSE_Format_evercddl_bool;

bool COSE_Format_evercddl_bool_right(bool x1);

bool COSE_Format_evercddl_bool_left(bool x4);

/**
Parser for evercddl_bool
*/
bool COSE_Format_parse_bool(cbor_det_t c);

typedef struct Pulse_Lib_Slice_slice__uint8_t_s
{
  uint8_t *elt;
  size_t len;
}
Pulse_Lib_Slice_slice__uint8_t;

typedef enum { FStar_Pervasives_Native_None, FStar_Pervasives_Native_Some }
FStar_Pervasives_Native_option__size_t_tags;

/**
Serializer for evercddl_bool
*/
size_t COSE_Format_serialize_bool(bool c, Pulse_Lib_Slice_slice__uint8_t out);

typedef struct
FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t_s
{
  Pulse_Lib_Slice_slice__uint8_t _1;
  Pulse_Lib_Slice_slice__uint8_t _2;
}
FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t;

typedef struct FStar_Pervasives_Native_tuple2__bool_Pulse_Lib_Slice_slice__uint8_t_s
{
  bool _1;
  Pulse_Lib_Slice_slice__uint8_t _2;
}
FStar_Pervasives_Native_tuple2__bool_Pulse_Lib_Slice_slice__uint8_t;

typedef struct
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__bool_Pulse_Lib_Slice_slice__uint8_t_s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  FStar_Pervasives_Native_tuple2__bool_Pulse_Lib_Slice_slice__uint8_t v;
}
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__bool_Pulse_Lib_Slice_slice__uint8_t;

typedef struct
FStar_Pervasives_Native_tuple2__CBOR_Pulse_API_Det_Type_cbor_det_t_Pulse_Lib_Slice_slice__uint8_t_s
{
  cbor_det_t _1;
  Pulse_Lib_Slice_slice__uint8_t _2;
}
FStar_Pervasives_Native_tuple2__CBOR_Pulse_API_Det_Type_cbor_det_t_Pulse_Lib_Slice_slice__uint8_t;

typedef struct
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__CBOR_Pulse_API_Det_Type_cbor_det_t_Pulse_Lib_Slice_slice__uint8_t_s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  FStar_Pervasives_Native_tuple2__CBOR_Pulse_API_Det_Type_cbor_det_t_Pulse_Lib_Slice_slice__uint8_t
  v;
}
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__CBOR_Pulse_API_Det_Type_cbor_det_t_Pulse_Lib_Slice_slice__uint8_t;

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__bool_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_bool(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_everparsenomatch(cbor_det_t c);

void COSE_Format_everparsenomatch_right(void);

/**
Parser for everparsenomatch
*/
void COSE_Format_parse_everparsenomatch(cbor_det_t c);

/**
Serializer for everparsenomatch
*/
size_t COSE_Format_serialize_everparsenomatch(Pulse_Lib_Slice_slice__uint8_t out);

typedef struct
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2_____Pulse_Lib_Slice_slice__uint8_t_s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  Pulse_Lib_Slice_slice__uint8_t v;
}
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2_____Pulse_Lib_Slice_slice__uint8_t;

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2_____Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_everparsenomatch(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_any(cbor_det_t c);

typedef cbor_det_t COSE_Format_any_ugly;

typedef cbor_det_t COSE_Format_any;

cbor_det_t COSE_Format_any_right(cbor_det_t x1);

cbor_det_t COSE_Format_any_left(cbor_det_t x4);

/**
Parser for any
*/
cbor_det_t COSE_Format_parse_any(cbor_det_t c);

/**
Serializer for any
*/
size_t COSE_Format_serialize_any(cbor_det_t c, Pulse_Lib_Slice_slice__uint8_t out);

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__CBOR_Pulse_API_Det_Type_cbor_det_t_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_any(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_undefined(cbor_det_t c);

void COSE_Format_undefined_right(void);

/**
Parser for undefined
*/
void COSE_Format_parse_undefined(cbor_det_t c);

/**
Serializer for undefined
*/
size_t COSE_Format_serialize_undefined(Pulse_Lib_Slice_slice__uint8_t out);

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2_____Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_undefined(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_nil(cbor_det_t c);

void COSE_Format_nil_right(void);

/**
Parser for nil
*/
void COSE_Format_parse_nil(cbor_det_t c);

/**
Serializer for nil
*/
size_t COSE_Format_serialize_nil(Pulse_Lib_Slice_slice__uint8_t out);

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2_____Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_nil(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_null(cbor_det_t c);

void COSE_Format_evercddl_null_right(void);

void COSE_Format_evercddl_null_left(void);

/**
Parser for evercddl_null
*/
void COSE_Format_parse_null(cbor_det_t c);

/**
Serializer for evercddl_null
*/
size_t COSE_Format_serialize_null(Pulse_Lib_Slice_slice__uint8_t out);

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2_____Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_null(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_true(cbor_det_t c);

void COSE_Format_evercddl_true_right(void);

/**
Parser for evercddl_true
*/
void COSE_Format_parse_true(cbor_det_t c);

/**
Serializer for evercddl_true
*/
size_t COSE_Format_serialize_true(Pulse_Lib_Slice_slice__uint8_t out);

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2_____Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_true(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_false(cbor_det_t c);

void COSE_Format_evercddl_false_right(void);

/**
Parser for evercddl_false
*/
void COSE_Format_parse_false(cbor_det_t c);

/**
Serializer for evercddl_false
*/
size_t COSE_Format_serialize_false(Pulse_Lib_Slice_slice__uint8_t out);

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2_____Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_false(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_tstr(cbor_det_t c);

typedef Pulse_Lib_Slice_slice__uint8_t COSE_Format_tstr_ugly;

typedef Pulse_Lib_Slice_slice__uint8_t COSE_Format_tstr;

Pulse_Lib_Slice_slice__uint8_t COSE_Format_tstr_right(Pulse_Lib_Slice_slice__uint8_t x1);

Pulse_Lib_Slice_slice__uint8_t COSE_Format_tstr_left(Pulse_Lib_Slice_slice__uint8_t x4);

/**
Parser for tstr
*/
Pulse_Lib_Slice_slice__uint8_t COSE_Format_parse_tstr(cbor_det_t c);

/**
Serializer for tstr
*/
size_t
COSE_Format_serialize_tstr(
  Pulse_Lib_Slice_slice__uint8_t c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t_s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t
  v;
}
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t;

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_tstr(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_bstr(cbor_det_t c);

typedef Pulse_Lib_Slice_slice__uint8_t COSE_Format_bstr_ugly;

typedef Pulse_Lib_Slice_slice__uint8_t COSE_Format_bstr;

Pulse_Lib_Slice_slice__uint8_t COSE_Format_bstr_right(Pulse_Lib_Slice_slice__uint8_t x1);

Pulse_Lib_Slice_slice__uint8_t COSE_Format_bstr_left(Pulse_Lib_Slice_slice__uint8_t x4);

/**
Parser for bstr
*/
Pulse_Lib_Slice_slice__uint8_t COSE_Format_parse_bstr(cbor_det_t c);

/**
Serializer for bstr
*/
size_t
COSE_Format_serialize_bstr(
  Pulse_Lib_Slice_slice__uint8_t c,
  Pulse_Lib_Slice_slice__uint8_t out
);

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_bstr(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_bytes(cbor_det_t c);

typedef Pulse_Lib_Slice_slice__uint8_t COSE_Format_bytes_ugly;

typedef Pulse_Lib_Slice_slice__uint8_t COSE_Format_bytes;

Pulse_Lib_Slice_slice__uint8_t COSE_Format_bytes_right(Pulse_Lib_Slice_slice__uint8_t x1);

Pulse_Lib_Slice_slice__uint8_t COSE_Format_bytes_left(Pulse_Lib_Slice_slice__uint8_t x4);

/**
Parser for bytes
*/
Pulse_Lib_Slice_slice__uint8_t COSE_Format_parse_bytes(cbor_det_t c);

/**
Serializer for bytes
*/
size_t
COSE_Format_serialize_bytes(
  Pulse_Lib_Slice_slice__uint8_t c,
  Pulse_Lib_Slice_slice__uint8_t out
);

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_bytes(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_text(cbor_det_t c);

typedef Pulse_Lib_Slice_slice__uint8_t COSE_Format_text_ugly;

typedef Pulse_Lib_Slice_slice__uint8_t COSE_Format_text;

Pulse_Lib_Slice_slice__uint8_t COSE_Format_text_right(Pulse_Lib_Slice_slice__uint8_t x1);

Pulse_Lib_Slice_slice__uint8_t COSE_Format_text_left(Pulse_Lib_Slice_slice__uint8_t x4);

/**
Parser for text
*/
Pulse_Lib_Slice_slice__uint8_t COSE_Format_parse_text(cbor_det_t c);

/**
Serializer for text
*/
size_t
COSE_Format_serialize_text(
  Pulse_Lib_Slice_slice__uint8_t c,
  Pulse_Lib_Slice_slice__uint8_t out
);

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_text(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_nint(cbor_det_t c);

typedef uint64_t COSE_Format_nint_ugly;

typedef uint64_t COSE_Format_nint;

uint64_t COSE_Format_nint_right(uint64_t x1);

uint64_t COSE_Format_nint_left(uint64_t x4);

/**
Parser for nint
*/
uint64_t COSE_Format_parse_nint(cbor_det_t c);

/**
Serializer for nint
*/
size_t COSE_Format_serialize_nint(uint64_t c, Pulse_Lib_Slice_slice__uint8_t out);

typedef struct FStar_Pervasives_Native_tuple2__uint64_t_Pulse_Lib_Slice_slice__uint8_t_s
{
  uint64_t _1;
  Pulse_Lib_Slice_slice__uint8_t _2;
}
FStar_Pervasives_Native_tuple2__uint64_t_Pulse_Lib_Slice_slice__uint8_t;

typedef struct
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__uint64_t_Pulse_Lib_Slice_slice__uint8_t_s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  FStar_Pervasives_Native_tuple2__uint64_t_Pulse_Lib_Slice_slice__uint8_t v;
}
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__uint64_t_Pulse_Lib_Slice_slice__uint8_t;

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__uint64_t_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_nint(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_uint(cbor_det_t c);

typedef uint64_t COSE_Format_evercddl_uint_ugly;

typedef uint64_t COSE_Format_evercddl_uint;

uint64_t COSE_Format_evercddl_uint_right(uint64_t x1);

uint64_t COSE_Format_evercddl_uint_left(uint64_t x4);

/**
Parser for evercddl_uint
*/
uint64_t COSE_Format_parse_uint(cbor_det_t c);

/**
Serializer for evercddl_uint
*/
size_t COSE_Format_serialize_uint(uint64_t c, Pulse_Lib_Slice_slice__uint8_t out);

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__uint64_t_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_uint(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_int(cbor_det_t c);

typedef enum { COSE_Format_Inl, COSE_Format_Inr } COSE_Format_evercddl_int_ugly_tags;

typedef struct COSE_Format_evercddl_int_ugly_s
{
  COSE_Format_evercddl_int_ugly_tags tag;
  union {
    uint64_t case_Inl;
    uint64_t case_Inr;
  }
  ;
}
COSE_Format_evercddl_int_ugly;

typedef enum { COSE_Format_Mkevercddl_int0, COSE_Format_Mkevercddl_int1 }
COSE_Format_evercddl_int_tags;

typedef struct COSE_Format_evercddl_int_s
{
  COSE_Format_evercddl_int_tags tag;
  union {
    uint64_t case_Mkevercddl_int0;
    uint64_t case_Mkevercddl_int1;
  }
  ;
}
COSE_Format_evercddl_int;

COSE_Format_evercddl_int COSE_Format_evercddl_int_right(COSE_Format_evercddl_int_ugly x2);

COSE_Format_evercddl_int_ugly COSE_Format_evercddl_int_left(COSE_Format_evercddl_int x8);

/**
Parser for evercddl_int
*/
COSE_Format_evercddl_int COSE_Format_parse_int(cbor_det_t c);

/**
Serializer for evercddl_int
*/
size_t
COSE_Format_serialize_int(COSE_Format_evercddl_int c, Pulse_Lib_Slice_slice__uint8_t out);

typedef struct
FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_int_Pulse_Lib_Slice_slice__uint8_t_s
{
  COSE_Format_evercddl_int _1;
  Pulse_Lib_Slice_slice__uint8_t _2;
}
FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_int_Pulse_Lib_Slice_slice__uint8_t;

typedef struct
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_int_Pulse_Lib_Slice_slice__uint8_t_s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_int_Pulse_Lib_Slice_slice__uint8_t v;
}
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_int_Pulse_Lib_Slice_slice__uint8_t;

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_int_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_int(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_cborany(cbor_det_t c);

typedef cbor_det_t COSE_Format_cborany_ugly;

typedef cbor_det_t COSE_Format_cborany;

cbor_det_t COSE_Format_cborany_right(cbor_det_t x1);

cbor_det_t COSE_Format_cborany_left(cbor_det_t x4);

/**
Parser for cborany
*/
cbor_det_t COSE_Format_parse_cborany(cbor_det_t c);

/**
Serializer for cborany
*/
size_t COSE_Format_serialize_cborany(cbor_det_t c, Pulse_Lib_Slice_slice__uint8_t out);

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__CBOR_Pulse_API_Det_Type_cbor_det_t_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_cborany(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_mimemessage(cbor_det_t c);

typedef Pulse_Lib_Slice_slice__uint8_t COSE_Format_mimemessage_ugly;

typedef Pulse_Lib_Slice_slice__uint8_t COSE_Format_mimemessage;

Pulse_Lib_Slice_slice__uint8_t
COSE_Format_mimemessage_right(Pulse_Lib_Slice_slice__uint8_t x1);

Pulse_Lib_Slice_slice__uint8_t COSE_Format_mimemessage_left(Pulse_Lib_Slice_slice__uint8_t x4);

/**
Parser for mimemessage
*/
Pulse_Lib_Slice_slice__uint8_t COSE_Format_parse_mimemessage(cbor_det_t c);

/**
Serializer for mimemessage
*/
size_t
COSE_Format_serialize_mimemessage(
  Pulse_Lib_Slice_slice__uint8_t c,
  Pulse_Lib_Slice_slice__uint8_t out
);

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_mimemessage(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_regexp(cbor_det_t c);

typedef Pulse_Lib_Slice_slice__uint8_t COSE_Format_regexp_ugly;

typedef Pulse_Lib_Slice_slice__uint8_t COSE_Format_regexp;

Pulse_Lib_Slice_slice__uint8_t COSE_Format_regexp_right(Pulse_Lib_Slice_slice__uint8_t x1);

Pulse_Lib_Slice_slice__uint8_t COSE_Format_regexp_left(Pulse_Lib_Slice_slice__uint8_t x4);

/**
Parser for regexp
*/
Pulse_Lib_Slice_slice__uint8_t COSE_Format_parse_regexp(cbor_det_t c);

/**
Serializer for regexp
*/
size_t
COSE_Format_serialize_regexp(
  Pulse_Lib_Slice_slice__uint8_t c,
  Pulse_Lib_Slice_slice__uint8_t out
);

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_regexp(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_b64legacy(cbor_det_t c);

typedef Pulse_Lib_Slice_slice__uint8_t COSE_Format_b64legacy_ugly;

typedef Pulse_Lib_Slice_slice__uint8_t COSE_Format_b64legacy;

Pulse_Lib_Slice_slice__uint8_t COSE_Format_b64legacy_right(Pulse_Lib_Slice_slice__uint8_t x1);

Pulse_Lib_Slice_slice__uint8_t COSE_Format_b64legacy_left(Pulse_Lib_Slice_slice__uint8_t x4);

/**
Parser for b64legacy
*/
Pulse_Lib_Slice_slice__uint8_t COSE_Format_parse_b64legacy(cbor_det_t c);

/**
Serializer for b64legacy
*/
size_t
COSE_Format_serialize_b64legacy(
  Pulse_Lib_Slice_slice__uint8_t c,
  Pulse_Lib_Slice_slice__uint8_t out
);

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_b64legacy(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_b64url(cbor_det_t c);

typedef Pulse_Lib_Slice_slice__uint8_t COSE_Format_b64url_ugly;

typedef Pulse_Lib_Slice_slice__uint8_t COSE_Format_b64url;

Pulse_Lib_Slice_slice__uint8_t COSE_Format_b64url_right(Pulse_Lib_Slice_slice__uint8_t x1);

Pulse_Lib_Slice_slice__uint8_t COSE_Format_b64url_left(Pulse_Lib_Slice_slice__uint8_t x4);

/**
Parser for b64url
*/
Pulse_Lib_Slice_slice__uint8_t COSE_Format_parse_b64url(cbor_det_t c);

/**
Serializer for b64url
*/
size_t
COSE_Format_serialize_b64url(
  Pulse_Lib_Slice_slice__uint8_t c,
  Pulse_Lib_Slice_slice__uint8_t out
);

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_b64url(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_uri(cbor_det_t c);

typedef Pulse_Lib_Slice_slice__uint8_t COSE_Format_uri_ugly;

typedef Pulse_Lib_Slice_slice__uint8_t COSE_Format_uri;

Pulse_Lib_Slice_slice__uint8_t COSE_Format_uri_right(Pulse_Lib_Slice_slice__uint8_t x1);

Pulse_Lib_Slice_slice__uint8_t COSE_Format_uri_left(Pulse_Lib_Slice_slice__uint8_t x4);

/**
Parser for uri
*/
Pulse_Lib_Slice_slice__uint8_t COSE_Format_parse_uri(cbor_det_t c);

/**
Serializer for uri
*/
size_t
COSE_Format_serialize_uri(Pulse_Lib_Slice_slice__uint8_t c, Pulse_Lib_Slice_slice__uint8_t out);

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_uri(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_encodedcbor(cbor_det_t c);

typedef Pulse_Lib_Slice_slice__uint8_t COSE_Format_encodedcbor_ugly;

typedef Pulse_Lib_Slice_slice__uint8_t COSE_Format_encodedcbor;

Pulse_Lib_Slice_slice__uint8_t
COSE_Format_encodedcbor_right(Pulse_Lib_Slice_slice__uint8_t x1);

Pulse_Lib_Slice_slice__uint8_t COSE_Format_encodedcbor_left(Pulse_Lib_Slice_slice__uint8_t x4);

/**
Parser for encodedcbor
*/
Pulse_Lib_Slice_slice__uint8_t COSE_Format_parse_encodedcbor(cbor_det_t c);

/**
Serializer for encodedcbor
*/
size_t
COSE_Format_serialize_encodedcbor(
  Pulse_Lib_Slice_slice__uint8_t c,
  Pulse_Lib_Slice_slice__uint8_t out
);

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_encodedcbor(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_eb16(cbor_det_t c);

typedef cbor_det_t COSE_Format_eb16_ugly;

typedef cbor_det_t COSE_Format_eb16;

cbor_det_t COSE_Format_eb16_right(cbor_det_t x1);

cbor_det_t COSE_Format_eb16_left(cbor_det_t x4);

/**
Parser for eb16
*/
cbor_det_t COSE_Format_parse_eb16(cbor_det_t c);

/**
Serializer for eb16
*/
size_t COSE_Format_serialize_eb16(cbor_det_t c, Pulse_Lib_Slice_slice__uint8_t out);

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__CBOR_Pulse_API_Det_Type_cbor_det_t_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_eb16(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_eb64legacy(cbor_det_t c);

typedef cbor_det_t COSE_Format_eb64legacy_ugly;

typedef cbor_det_t COSE_Format_eb64legacy;

cbor_det_t COSE_Format_eb64legacy_right(cbor_det_t x1);

cbor_det_t COSE_Format_eb64legacy_left(cbor_det_t x4);

/**
Parser for eb64legacy
*/
cbor_det_t COSE_Format_parse_eb64legacy(cbor_det_t c);

/**
Serializer for eb64legacy
*/
size_t COSE_Format_serialize_eb64legacy(cbor_det_t c, Pulse_Lib_Slice_slice__uint8_t out);

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__CBOR_Pulse_API_Det_Type_cbor_det_t_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_eb64legacy(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_eb64url(cbor_det_t c);

typedef cbor_det_t COSE_Format_eb64url_ugly;

typedef cbor_det_t COSE_Format_eb64url;

cbor_det_t COSE_Format_eb64url_right(cbor_det_t x1);

cbor_det_t COSE_Format_eb64url_left(cbor_det_t x4);

/**
Parser for eb64url
*/
cbor_det_t COSE_Format_parse_eb64url(cbor_det_t c);

/**
Serializer for eb64url
*/
size_t COSE_Format_serialize_eb64url(cbor_det_t c, Pulse_Lib_Slice_slice__uint8_t out);

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__CBOR_Pulse_API_Det_Type_cbor_det_t_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_eb64url(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_number(cbor_det_t c);

typedef COSE_Format_evercddl_int COSE_Format_number_ugly;

typedef COSE_Format_evercddl_int COSE_Format_number;

COSE_Format_evercddl_int COSE_Format_number_right(COSE_Format_evercddl_int x1);

COSE_Format_evercddl_int COSE_Format_number_left(COSE_Format_evercddl_int x4);

/**
Parser for number
*/
COSE_Format_evercddl_int COSE_Format_parse_number(cbor_det_t c);

/**
Serializer for number
*/
size_t
COSE_Format_serialize_number(COSE_Format_evercddl_int c, Pulse_Lib_Slice_slice__uint8_t out);

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_int_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_number(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_tdate(cbor_det_t c);

typedef Pulse_Lib_Slice_slice__uint8_t COSE_Format_tdate_ugly;

typedef Pulse_Lib_Slice_slice__uint8_t COSE_Format_tdate;

Pulse_Lib_Slice_slice__uint8_t COSE_Format_tdate_right(Pulse_Lib_Slice_slice__uint8_t x1);

Pulse_Lib_Slice_slice__uint8_t COSE_Format_tdate_left(Pulse_Lib_Slice_slice__uint8_t x4);

/**
Parser for tdate
*/
Pulse_Lib_Slice_slice__uint8_t COSE_Format_parse_tdate(cbor_det_t c);

/**
Serializer for tdate
*/
size_t
COSE_Format_serialize_tdate(
  Pulse_Lib_Slice_slice__uint8_t c,
  Pulse_Lib_Slice_slice__uint8_t out
);

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_tdate(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_values(cbor_det_t c);

typedef cbor_det_t COSE_Format_values_ugly;

typedef cbor_det_t COSE_Format_values;

cbor_det_t COSE_Format_values_right(cbor_det_t x1);

cbor_det_t COSE_Format_values_left(cbor_det_t x4);

/**
Parser for values
*/
cbor_det_t COSE_Format_parse_values(cbor_det_t c);

/**
Serializer for values
*/
size_t COSE_Format_serialize_values(cbor_det_t c, Pulse_Lib_Slice_slice__uint8_t out);

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__CBOR_Pulse_API_Det_Type_cbor_det_t_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_values(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_evercddl_label(cbor_det_t c);

typedef struct COSE_Format_evercddl_label_ugly_s
{
  COSE_Format_evercddl_int_ugly_tags tag;
  union {
    COSE_Format_evercddl_int case_Inl;
    Pulse_Lib_Slice_slice__uint8_t case_Inr;
  }
  ;
}
COSE_Format_evercddl_label_ugly;

typedef enum { COSE_Format_Mkevercddl_label0, COSE_Format_Mkevercddl_label1 }
COSE_Format_evercddl_label_tags;

typedef struct COSE_Format_evercddl_label_s
{
  COSE_Format_evercddl_label_tags tag;
  union {
    COSE_Format_evercddl_int case_Mkevercddl_label0;
    Pulse_Lib_Slice_slice__uint8_t case_Mkevercddl_label1;
  }
  ;
}
COSE_Format_evercddl_label;

COSE_Format_evercddl_label
COSE_Format_evercddl_label_right(COSE_Format_evercddl_label_ugly x2);

COSE_Format_evercddl_label_ugly COSE_Format_evercddl_label_left(COSE_Format_evercddl_label x8);

/**
Parser for evercddl_label
*/
COSE_Format_evercddl_label COSE_Format_parse_evercddl_label(cbor_det_t c);

/**
Serializer for evercddl_label
*/
size_t
COSE_Format_serialize_evercddl_label(
  COSE_Format_evercddl_label c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct
FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_label_Pulse_Lib_Slice_slice__uint8_t_s
{
  COSE_Format_evercddl_label _1;
  Pulse_Lib_Slice_slice__uint8_t _2;
}
FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_label_Pulse_Lib_Slice_slice__uint8_t;

typedef struct
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_label_Pulse_Lib_Slice_slice__uint8_t_s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_label_Pulse_Lib_Slice_slice__uint8_t v;
}
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_label_Pulse_Lib_Slice_slice__uint8_t;

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_label_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_evercddl_label(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_aux_env29_validate_1(cbor_det_array_iterator_t *pi);

typedef struct COSE_Format_aux_env29_type_1_ugly_s
{
  COSE_Format_evercddl_int_ugly_tags tag;
  union {
    Pulse_Lib_Slice_slice__uint8_t case_Inl;
    COSE_Format_evercddl_int case_Inr;
  }
  ;
}
COSE_Format_aux_env29_type_1_ugly;

typedef enum { COSE_Format_Mkaux_env29_type_10, COSE_Format_Mkaux_env29_type_11 }
COSE_Format_aux_env29_type_1_tags;

typedef struct COSE_Format_aux_env29_type_1_s
{
  COSE_Format_aux_env29_type_1_tags tag;
  union {
    Pulse_Lib_Slice_slice__uint8_t case_Mkaux_env29_type_10;
    COSE_Format_evercddl_int case_Mkaux_env29_type_11;
  }
  ;
}
COSE_Format_aux_env29_type_1;

COSE_Format_aux_env29_type_1
COSE_Format_aux_env29_type_1_right(COSE_Format_aux_env29_type_1_ugly x2);

COSE_Format_aux_env29_type_1_ugly
COSE_Format_aux_env29_type_1_left(COSE_Format_aux_env29_type_1 x8);

/**
Parser for aux_env29_type_1
*/
COSE_Format_aux_env29_type_1 COSE_Format_aux_env29_parse_1(cbor_det_array_iterator_t c);

/**
Serializer for aux_env29_type_1
*/
bool
COSE_Format_aux_env29_serialize_1(
  COSE_Format_aux_env29_type_1 c,
  Pulse_Lib_Slice_slice__uint8_t out,
  uint64_t *out_count,
  size_t *out_size
);

bool COSE_Format_aux_env29_map_constraint_2(cbor_det_map_entry_t x);

bool COSE_Format_validate_cose_key_generic(cbor_det_t c);

typedef struct FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t_s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  Pulse_Lib_Slice_slice__uint8_t v;
}
FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t;

typedef struct
FStar_Pervasives_Native_tuple2__COSE_Format_aux_env29_type_1_ugly_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t_s
{
  COSE_Format_aux_env29_type_1_ugly _1;
  FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t _2;
}
FStar_Pervasives_Native_tuple2__COSE_Format_aux_env29_type_1_ugly_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t;

typedef struct FStar_Pervasives_Native_option__COSE_Format_aux_env29_type_1_ugly_s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  COSE_Format_aux_env29_type_1_ugly v;
}
FStar_Pervasives_Native_option__COSE_Format_aux_env29_type_1_ugly;

typedef struct
FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__COSE_Format_aux_env29_type_1_ugly_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option__COSE_Format_aux_env29_type_1_ugly_s
{
  FStar_Pervasives_Native_tuple2__COSE_Format_aux_env29_type_1_ugly_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t
  _1;
  FStar_Pervasives_Native_option__COSE_Format_aux_env29_type_1_ugly _2;
}
FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__COSE_Format_aux_env29_type_1_ugly_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option__COSE_Format_aux_env29_type_1_ugly;

typedef struct Pulse_Lib_Slice_slice__COSE_Format_aux_env29_type_1_s
{
  COSE_Format_aux_env29_type_1 *elt;
  size_t len;
}
Pulse_Lib_Slice_slice__COSE_Format_aux_env29_type_1;

typedef struct
CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env29_type_1_s
{
  cbor_det_array_iterator_t cddl_array_iterator_contents;
  bool (*cddl_array_iterator_impl_validate)(cbor_det_array_iterator_t *x0);
  COSE_Format_aux_env29_type_1 (*cddl_array_iterator_impl_parse)(cbor_det_array_iterator_t x0);
}
CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env29_type_1;

typedef struct
FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_aux_env29_type_1_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env29_type_1_s
{
  COSE_Format_evercddl_int_ugly_tags tag;
  union {
    Pulse_Lib_Slice_slice__COSE_Format_aux_env29_type_1 case_Inl;
    CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env29_type_1
    case_Inr;
  }
  ;
}
FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_aux_env29_type_1_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env29_type_1;

typedef struct
FStar_Pervasives_Native_option__FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_aux_env29_type_1_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env29_type_1_s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_aux_env29_type_1_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env29_type_1
  v;
}
FStar_Pervasives_Native_option__FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_aux_env29_type_1_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env29_type_1;

typedef struct
FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__COSE_Format_aux_env29_type_1_ugly_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option__COSE_Format_aux_env29_type_1_ugly_FStar_Pervasives_Native_option__FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_aux_env29_type_1_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env29_type_1_s
{
  FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__COSE_Format_aux_env29_type_1_ugly_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option__COSE_Format_aux_env29_type_1_ugly
  _1;
  FStar_Pervasives_Native_option__FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_aux_env29_type_1_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env29_type_1
  _2;
}
FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__COSE_Format_aux_env29_type_1_ugly_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option__COSE_Format_aux_env29_type_1_ugly_FStar_Pervasives_Native_option__FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_aux_env29_type_1_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env29_type_1;

typedef struct
FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__COSE_Format_aux_env29_type_1_ugly_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option__COSE_Format_aux_env29_type_1_ugly_FStar_Pervasives_Native_option__FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_aux_env29_type_1_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env29_type_1_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t_s
{
  FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__COSE_Format_aux_env29_type_1_ugly_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option__COSE_Format_aux_env29_type_1_ugly_FStar_Pervasives_Native_option__FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_aux_env29_type_1_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env29_type_1
  _1;
  FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t _2;
}
FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__COSE_Format_aux_env29_type_1_ugly_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option__COSE_Format_aux_env29_type_1_ugly_FStar_Pervasives_Native_option__FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_aux_env29_type_1_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env29_type_1_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t;

typedef struct
FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t_s
FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t;

typedef struct
Pulse_Lib_Slice_slice__FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t_s
{
  FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t
  *elt;
  size_t len;
}
Pulse_Lib_Slice_slice__FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t;

typedef struct
CDDL_Pulse_Parse_MapGroup_map_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_t_CBOR_Pulse_API_Det_Type_cbor_det_map_entry_t_CBOR_Pulse_API_Det_Type_cbor_det_map_iterator_t_COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t_s
{
  cbor_det_map_iterator_t cddl_map_iterator_contents;
  bool (*cddl_map_iterator_impl_validate1)(cbor_det_t x0);
  COSE_Format_evercddl_label (*cddl_map_iterator_impl_parse1)(cbor_det_t x0);
  bool (*cddl_map_iterator_impl_validate_ex)(cbor_det_map_entry_t x0);
  bool (*cddl_map_iterator_impl_validate2)(cbor_det_t x0);
  cbor_det_t (*cddl_map_iterator_impl_parse2)(cbor_det_t x0);
}
CDDL_Pulse_Parse_MapGroup_map_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_t_CBOR_Pulse_API_Det_Type_cbor_det_map_entry_t_CBOR_Pulse_API_Det_Type_cbor_det_map_iterator_t_COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t;

typedef struct
FStar_Pervasives_either__Pulse_Lib_Slice_slice__FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t_CDDL_Pulse_Parse_MapGroup_map_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_t_CBOR_Pulse_API_Det_Type_cbor_det_map_entry_t_CBOR_Pulse_API_Det_Type_cbor_det_map_iterator_t_COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t_s
{
  COSE_Format_evercddl_int_ugly_tags tag;
  union {
    Pulse_Lib_Slice_slice__FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t
    case_Inl;
    CDDL_Pulse_Parse_MapGroup_map_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_t_CBOR_Pulse_API_Det_Type_cbor_det_map_entry_t_CBOR_Pulse_API_Det_Type_cbor_det_map_iterator_t_COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t
    case_Inr;
  }
  ;
}
FStar_Pervasives_either__Pulse_Lib_Slice_slice__FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t_CDDL_Pulse_Parse_MapGroup_map_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_t_CBOR_Pulse_API_Det_Type_cbor_det_map_entry_t_CBOR_Pulse_API_Det_Type_cbor_det_map_iterator_t_COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t;

typedef struct COSE_Format_cose_key_generic_ugly_s
{
  FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__COSE_Format_aux_env29_type_1_ugly_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option__COSE_Format_aux_env29_type_1_ugly_FStar_Pervasives_Native_option__FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_aux_env29_type_1_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env29_type_1_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t
  _1;
  FStar_Pervasives_either__Pulse_Lib_Slice_slice__FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t_CDDL_Pulse_Parse_MapGroup_map_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_t_CBOR_Pulse_API_Det_Type_cbor_det_map_entry_t_CBOR_Pulse_API_Det_Type_cbor_det_map_iterator_t_COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t
  _2;
}
COSE_Format_cose_key_generic_ugly;

typedef struct COSE_Format_cose_key_generic_s
{
  COSE_Format_aux_env29_type_1_ugly intkey1;
  FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t intkey2;
  FStar_Pervasives_Native_option__COSE_Format_aux_env29_type_1_ugly intkey3;
  FStar_Pervasives_Native_option__FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_aux_env29_type_1_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env29_type_1
  intkey4;
  FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t intkey5;
  FStar_Pervasives_either__Pulse_Lib_Slice_slice__FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t_CDDL_Pulse_Parse_MapGroup_map_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_t_CBOR_Pulse_API_Det_Type_cbor_det_map_entry_t_CBOR_Pulse_API_Det_Type_cbor_det_map_iterator_t_COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t
  _x0;
}
COSE_Format_cose_key_generic;

COSE_Format_cose_key_generic
COSE_Format_cose_key_generic_right(COSE_Format_cose_key_generic_ugly x6);

COSE_Format_cose_key_generic_ugly
COSE_Format_cose_key_generic_left(COSE_Format_cose_key_generic x14);

/**
Parser for cose_key_generic
*/
COSE_Format_cose_key_generic COSE_Format_parse_cose_key_generic(cbor_det_t c);

typedef struct
FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t_s
{
  COSE_Format_evercddl_label _1;
  cbor_det_t _2;
}
FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t;

/**
Serializer for cose_key_generic
*/
size_t
COSE_Format_serialize_cose_key_generic(
  COSE_Format_cose_key_generic c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct
FStar_Pervasives_Native_tuple2__COSE_Format_cose_key_generic_Pulse_Lib_Slice_slice__uint8_t_s
{
  COSE_Format_cose_key_generic _1;
  Pulse_Lib_Slice_slice__uint8_t _2;
}
FStar_Pervasives_Native_tuple2__COSE_Format_cose_key_generic_Pulse_Lib_Slice_slice__uint8_t;

typedef struct
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_cose_key_generic_Pulse_Lib_Slice_slice__uint8_t_s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  FStar_Pervasives_Native_tuple2__COSE_Format_cose_key_generic_Pulse_Lib_Slice_slice__uint8_t v;
}
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_cose_key_generic_Pulse_Lib_Slice_slice__uint8_t;

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_cose_key_generic_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_cose_key_generic(Pulse_Lib_Slice_slice__uint8_t s);

bool
COSE_Format_is_empty_iterate_array_aux_env29_type_1(
  CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env29_type_1
  i
);

COSE_Format_aux_env29_type_1
COSE_Format_next_iterate_array_aux_env29_type_1(
  CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env29_type_1
  *pi
);

bool
COSE_Format_is_empty_iterate_map_evercddl_label_and_values(
  CDDL_Pulse_Parse_MapGroup_map_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_t_CBOR_Pulse_API_Det_Type_cbor_det_map_entry_t_CBOR_Pulse_API_Det_Type_cbor_det_map_iterator_t_COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t
  i
);

FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t
COSE_Format_next_iterate_map_evercddl_label_and_values(
  CDDL_Pulse_Parse_MapGroup_map_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_t_CBOR_Pulse_API_Det_Type_cbor_det_map_entry_t_CBOR_Pulse_API_Det_Type_cbor_det_map_iterator_t_COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t
  *pi
);

bool COSE_Format_aux_env30_validate_1(cbor_det_array_iterator_t *pi);

typedef COSE_Format_cose_key_generic COSE_Format_aux_env30_type_1_ugly;

typedef COSE_Format_cose_key_generic COSE_Format_aux_env30_type_1;

COSE_Format_cose_key_generic
COSE_Format_aux_env30_type_1_right(COSE_Format_cose_key_generic x1);

COSE_Format_cose_key_generic
COSE_Format_aux_env30_type_1_left(COSE_Format_cose_key_generic x4);

/**
Parser for aux_env30_type_1
*/
COSE_Format_cose_key_generic COSE_Format_aux_env30_parse_1(cbor_det_array_iterator_t c);

/**
Serializer for aux_env30_type_1
*/
bool
COSE_Format_aux_env30_serialize_1(
  COSE_Format_cose_key_generic c,
  Pulse_Lib_Slice_slice__uint8_t out,
  uint64_t *out_count,
  size_t *out_size
);

bool COSE_Format_validate_cose_keyset(cbor_det_t c);

typedef struct Pulse_Lib_Slice_slice__COSE_Format_cose_key_generic_s
{
  COSE_Format_cose_key_generic *elt;
  size_t len;
}
Pulse_Lib_Slice_slice__COSE_Format_cose_key_generic;

typedef struct
CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_cose_key_generic_s
{
  cbor_det_array_iterator_t cddl_array_iterator_contents;
  bool (*cddl_array_iterator_impl_validate)(cbor_det_array_iterator_t *x0);
  COSE_Format_cose_key_generic (*cddl_array_iterator_impl_parse)(cbor_det_array_iterator_t x0);
}
CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_cose_key_generic;

typedef struct COSE_Format_cose_keyset_ugly_s
{
  COSE_Format_evercddl_int_ugly_tags tag;
  union {
    Pulse_Lib_Slice_slice__COSE_Format_cose_key_generic case_Inl;
    CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_cose_key_generic
    case_Inr;
  }
  ;
}
COSE_Format_cose_keyset_ugly;

typedef enum { COSE_Format_Mkcose_keyset0, COSE_Format_Mkcose_keyset1 }
COSE_Format_cose_keyset_tags;

typedef struct COSE_Format_cose_keyset_s
{
  COSE_Format_cose_keyset_tags tag;
  union {
    Pulse_Lib_Slice_slice__COSE_Format_cose_key_generic case_Mkcose_keyset0;
    CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_cose_key_generic
    case_Mkcose_keyset1;
  }
  ;
}
COSE_Format_cose_keyset;

COSE_Format_cose_keyset COSE_Format_cose_keyset_right(COSE_Format_cose_keyset_ugly x2);

COSE_Format_cose_keyset_ugly COSE_Format_cose_keyset_left(COSE_Format_cose_keyset x8);

/**
Parser for cose_keyset
*/
COSE_Format_cose_keyset COSE_Format_parse_cose_keyset(cbor_det_t c);

/**
Serializer for cose_keyset
*/
size_t
COSE_Format_serialize_cose_keyset(
  COSE_Format_cose_keyset c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct
FStar_Pervasives_Native_tuple2__COSE_Format_cose_keyset_Pulse_Lib_Slice_slice__uint8_t_s
{
  COSE_Format_cose_keyset _1;
  Pulse_Lib_Slice_slice__uint8_t _2;
}
FStar_Pervasives_Native_tuple2__COSE_Format_cose_keyset_Pulse_Lib_Slice_slice__uint8_t;

typedef struct
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_cose_keyset_Pulse_Lib_Slice_slice__uint8_t_s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  FStar_Pervasives_Native_tuple2__COSE_Format_cose_keyset_Pulse_Lib_Slice_slice__uint8_t v;
}
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_cose_keyset_Pulse_Lib_Slice_slice__uint8_t;

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_cose_keyset_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_cose_keyset(Pulse_Lib_Slice_slice__uint8_t s);

bool
COSE_Format_is_empty_iterate_array_aux_env30_type_1(
  CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_cose_key_generic
  i
);

COSE_Format_cose_key_generic
COSE_Format_next_iterate_array_aux_env30_type_1(
  CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_cose_key_generic
  *pi
);

bool COSE_Format_aux_env31_map_constraint_1(cbor_det_map_entry_t x);

bool COSE_Format_validate_cose_key_okp(cbor_det_t c);

typedef struct
FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2_____COSE_Format_evercddl_label_ugly_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t_s
{
  COSE_Format_evercddl_label_ugly _1;
  FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t _2;
}
FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2_____COSE_Format_evercddl_label_ugly_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t;

typedef struct
FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2_____COSE_Format_evercddl_label_ugly_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t_s
{
  FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2_____COSE_Format_evercddl_label_ugly_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t
  _1;
  FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t _2;
}
FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2_____COSE_Format_evercddl_label_ugly_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t;

typedef struct COSE_Format_cose_key_okp_ugly_s
{
  FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2_____COSE_Format_evercddl_label_ugly_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t
  _1;
  FStar_Pervasives_either__Pulse_Lib_Slice_slice__FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t_CDDL_Pulse_Parse_MapGroup_map_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_t_CBOR_Pulse_API_Det_Type_cbor_det_map_entry_t_CBOR_Pulse_API_Det_Type_cbor_det_map_iterator_t_COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t
  _2;
}
COSE_Format_cose_key_okp_ugly;

typedef struct COSE_Format_cose_key_okp_s
{
  COSE_Format_evercddl_label_ugly intkeyneg1;
  FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t intkeyneg2;
  FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t intkeyneg4;
  FStar_Pervasives_either__Pulse_Lib_Slice_slice__FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t_CDDL_Pulse_Parse_MapGroup_map_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_t_CBOR_Pulse_API_Det_Type_cbor_det_map_entry_t_CBOR_Pulse_API_Det_Type_cbor_det_map_iterator_t_COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t
  _x0;
}
COSE_Format_cose_key_okp;

COSE_Format_cose_key_okp COSE_Format_cose_key_okp_right(COSE_Format_cose_key_okp_ugly x5);

COSE_Format_cose_key_okp_ugly COSE_Format_cose_key_okp_left(COSE_Format_cose_key_okp x12);

/**
Parser for cose_key_okp
*/
COSE_Format_cose_key_okp COSE_Format_parse_cose_key_okp(cbor_det_t c);

/**
Serializer for cose_key_okp
*/
size_t
COSE_Format_serialize_cose_key_okp(
  COSE_Format_cose_key_okp c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct
FStar_Pervasives_Native_tuple2__COSE_Format_cose_key_okp_Pulse_Lib_Slice_slice__uint8_t_s
{
  COSE_Format_cose_key_okp _1;
  Pulse_Lib_Slice_slice__uint8_t _2;
}
FStar_Pervasives_Native_tuple2__COSE_Format_cose_key_okp_Pulse_Lib_Slice_slice__uint8_t;

typedef struct
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_cose_key_okp_Pulse_Lib_Slice_slice__uint8_t_s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  FStar_Pervasives_Native_tuple2__COSE_Format_cose_key_okp_Pulse_Lib_Slice_slice__uint8_t v;
}
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_cose_key_okp_Pulse_Lib_Slice_slice__uint8_t;

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_cose_key_okp_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_cose_key_okp(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_cose_key(cbor_det_t c);

typedef COSE_Format_cose_key_okp COSE_Format_cose_key_ugly;

typedef COSE_Format_cose_key_okp COSE_Format_cose_key;

COSE_Format_cose_key_okp COSE_Format_cose_key_right(COSE_Format_cose_key_okp x1);

COSE_Format_cose_key_okp COSE_Format_cose_key_left(COSE_Format_cose_key_okp x4);

/**
Parser for cose_key
*/
COSE_Format_cose_key_okp COSE_Format_parse_cose_key(cbor_det_t c);

/**
Serializer for cose_key
*/
size_t
COSE_Format_serialize_cose_key(COSE_Format_cose_key_okp c, Pulse_Lib_Slice_slice__uint8_t out);

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_cose_key_okp_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_cose_key(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_aux_env34_validate_1(cbor_det_array_iterator_t *pi);

typedef COSE_Format_evercddl_label COSE_Format_aux_env34_type_1_ugly;

typedef COSE_Format_evercddl_label COSE_Format_aux_env34_type_1;

COSE_Format_evercddl_label COSE_Format_aux_env34_type_1_right(COSE_Format_evercddl_label x1);

COSE_Format_evercddl_label COSE_Format_aux_env34_type_1_left(COSE_Format_evercddl_label x4);

/**
Parser for aux_env34_type_1
*/
COSE_Format_evercddl_label COSE_Format_aux_env34_parse_1(cbor_det_array_iterator_t c);

/**
Serializer for aux_env34_type_1
*/
bool
COSE_Format_aux_env34_serialize_1(
  COSE_Format_evercddl_label c,
  Pulse_Lib_Slice_slice__uint8_t out,
  uint64_t *out_count,
  size_t *out_size
);

bool COSE_Format_aux_env34_map_constraint_2(cbor_det_map_entry_t x);

bool COSE_Format_validate_header_map(cbor_det_t c);

typedef struct FStar_Pervasives_Native_option__COSE_Format_evercddl_label_ugly_s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  COSE_Format_evercddl_label_ugly v;
}
FStar_Pervasives_Native_option__COSE_Format_evercddl_label_ugly;

typedef struct Pulse_Lib_Slice_slice__COSE_Format_evercddl_label_s
{
  COSE_Format_evercddl_label *elt;
  size_t len;
}
Pulse_Lib_Slice_slice__COSE_Format_evercddl_label;

typedef struct
CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_evercddl_label_s
{
  cbor_det_array_iterator_t cddl_array_iterator_contents;
  bool (*cddl_array_iterator_impl_validate)(cbor_det_array_iterator_t *x0);
  COSE_Format_evercddl_label (*cddl_array_iterator_impl_parse)(cbor_det_array_iterator_t x0);
}
CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_evercddl_label;

typedef struct
FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_evercddl_label_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_evercddl_label_s
{
  COSE_Format_evercddl_int_ugly_tags tag;
  union {
    Pulse_Lib_Slice_slice__COSE_Format_evercddl_label case_Inl;
    CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_evercddl_label
    case_Inr;
  }
  ;
}
FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_evercddl_label_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_evercddl_label;

typedef struct
FStar_Pervasives_Native_option__FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_evercddl_label_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_evercddl_label_s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_evercddl_label_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_evercddl_label
  v;
}
FStar_Pervasives_Native_option__FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_evercddl_label_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_evercddl_label;

typedef struct
FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_option__COSE_Format_evercddl_label_ugly_FStar_Pervasives_Native_option__FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_evercddl_label_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_evercddl_label_s
{
  FStar_Pervasives_Native_option__COSE_Format_evercddl_label_ugly _1;
  FStar_Pervasives_Native_option__FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_evercddl_label_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_evercddl_label
  _2;
}
FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_option__COSE_Format_evercddl_label_ugly_FStar_Pervasives_Native_option__FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_evercddl_label_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_evercddl_label;

typedef struct
FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_option__COSE_Format_evercddl_label_ugly_FStar_Pervasives_Native_option__FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_evercddl_label_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_evercddl_label_FStar_Pervasives_Native_option__COSE_Format_aux_env29_type_1_ugly_s
{
  FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_option__COSE_Format_evercddl_label_ugly_FStar_Pervasives_Native_option__FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_evercddl_label_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_evercddl_label
  _1;
  FStar_Pervasives_Native_option__COSE_Format_aux_env29_type_1_ugly _2;
}
FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_option__COSE_Format_evercddl_label_ugly_FStar_Pervasives_Native_option__FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_evercddl_label_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_evercddl_label_FStar_Pervasives_Native_option__COSE_Format_aux_env29_type_1_ugly;

typedef struct
FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_option__COSE_Format_evercddl_label_ugly_FStar_Pervasives_Native_option__FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_evercddl_label_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_evercddl_label_FStar_Pervasives_Native_option__COSE_Format_aux_env29_type_1_ugly_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t_s
{
  FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_option__COSE_Format_evercddl_label_ugly_FStar_Pervasives_Native_option__FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_evercddl_label_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_evercddl_label_FStar_Pervasives_Native_option__COSE_Format_aux_env29_type_1_ugly
  _1;
  FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t _2;
}
FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_option__COSE_Format_evercddl_label_ugly_FStar_Pervasives_Native_option__FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_evercddl_label_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_evercddl_label_FStar_Pervasives_Native_option__COSE_Format_aux_env29_type_1_ugly_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t;

typedef struct
FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option_____s
{
  Pulse_Lib_Slice_slice__uint8_t _1;
  FStar_Pervasives_Native_option__size_t_tags _2;
}
FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option____;

typedef struct
FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_option_____FStar_Pervasives_Native_option_____s
{
  FStar_Pervasives_Native_option__size_t_tags _1;
  FStar_Pervasives_Native_option__size_t_tags _2;
}
FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_option_____FStar_Pervasives_Native_option____;

typedef struct
FStar_Pervasives_either__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option_____FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_option_____FStar_Pervasives_Native_option_____s
{
  COSE_Format_evercddl_int_ugly_tags tag;
  union {
    FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option____
    case_Inl;
    FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_option_____FStar_Pervasives_Native_option____
    case_Inr;
  }
  ;
}
FStar_Pervasives_either__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option_____FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_option_____FStar_Pervasives_Native_option____;

typedef struct
FStar_Pervasives_either__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option_____FStar_Pervasives_either__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option_____FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_option_____FStar_Pervasives_Native_option_____s
{
  COSE_Format_evercddl_int_ugly_tags tag;
  union {
    FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option____
    case_Inl;
    FStar_Pervasives_either__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option_____FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_option_____FStar_Pervasives_Native_option____
    case_Inr;
  }
  ;
}
FStar_Pervasives_either__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option_____FStar_Pervasives_either__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option_____FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_option_____FStar_Pervasives_Native_option____;

typedef struct
FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_option__COSE_Format_evercddl_label_ugly_FStar_Pervasives_Native_option__FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_evercddl_label_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_evercddl_label_FStar_Pervasives_Native_option__COSE_Format_aux_env29_type_1_ugly_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_either__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option_____FStar_Pervasives_either__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option_____FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_option_____FStar_Pervasives_Native_option_____s
{
  FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_option__COSE_Format_evercddl_label_ugly_FStar_Pervasives_Native_option__FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_evercddl_label_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_evercddl_label_FStar_Pervasives_Native_option__COSE_Format_aux_env29_type_1_ugly_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t
  _1;
  FStar_Pervasives_either__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option_____FStar_Pervasives_either__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option_____FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_option_____FStar_Pervasives_Native_option____
  _2;
}
FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_option__COSE_Format_evercddl_label_ugly_FStar_Pervasives_Native_option__FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_evercddl_label_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_evercddl_label_FStar_Pervasives_Native_option__COSE_Format_aux_env29_type_1_ugly_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_either__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option_____FStar_Pervasives_either__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option_____FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_option_____FStar_Pervasives_Native_option____;

typedef struct COSE_Format_header_map_ugly_s
{
  FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_option__COSE_Format_evercddl_label_ugly_FStar_Pervasives_Native_option__FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_evercddl_label_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_evercddl_label_FStar_Pervasives_Native_option__COSE_Format_aux_env29_type_1_ugly_FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_either__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option_____FStar_Pervasives_either__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option_____FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_option_____FStar_Pervasives_Native_option____
  _1;
  FStar_Pervasives_either__Pulse_Lib_Slice_slice__FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t_CDDL_Pulse_Parse_MapGroup_map_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_t_CBOR_Pulse_API_Det_Type_cbor_det_map_entry_t_CBOR_Pulse_API_Det_Type_cbor_det_map_iterator_t_COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t
  _2;
}
COSE_Format_header_map_ugly;

typedef struct COSE_Format_header_map_s
{
  FStar_Pervasives_Native_option__COSE_Format_evercddl_label_ugly intkey1;
  FStar_Pervasives_Native_option__FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_evercddl_label_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_evercddl_label
  intkey2;
  FStar_Pervasives_Native_option__COSE_Format_aux_env29_type_1_ugly intkey3;
  FStar_Pervasives_Native_option__Pulse_Lib_Slice_slice__uint8_t intkey4;
  FStar_Pervasives_either__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option_____FStar_Pervasives_either__FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_option_____FStar_Pervasives_Native_tuple2__FStar_Pervasives_Native_option_____FStar_Pervasives_Native_option____
  _x0;
  FStar_Pervasives_either__Pulse_Lib_Slice_slice__FStar_Pervasives_Native_tuple2__COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t_CDDL_Pulse_Parse_MapGroup_map_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_t_CBOR_Pulse_API_Det_Type_cbor_det_map_entry_t_CBOR_Pulse_API_Det_Type_cbor_det_map_iterator_t_COSE_Format_evercddl_label_CBOR_Pulse_API_Det_Type_cbor_det_t
  _x1;
}
COSE_Format_header_map;

COSE_Format_header_map COSE_Format_header_map_right(COSE_Format_header_map_ugly x6);

COSE_Format_header_map_ugly COSE_Format_header_map_left(COSE_Format_header_map x14);

/**
Parser for header_map
*/
COSE_Format_header_map COSE_Format_parse_header_map(cbor_det_t c);

/**
Serializer for header_map
*/
size_t
COSE_Format_serialize_header_map(COSE_Format_header_map c, Pulse_Lib_Slice_slice__uint8_t out);

typedef struct
FStar_Pervasives_Native_tuple2__COSE_Format_header_map_Pulse_Lib_Slice_slice__uint8_t_s
{
  COSE_Format_header_map _1;
  Pulse_Lib_Slice_slice__uint8_t _2;
}
FStar_Pervasives_Native_tuple2__COSE_Format_header_map_Pulse_Lib_Slice_slice__uint8_t;

typedef struct
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_header_map_Pulse_Lib_Slice_slice__uint8_t_s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  FStar_Pervasives_Native_tuple2__COSE_Format_header_map_Pulse_Lib_Slice_slice__uint8_t v;
}
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_header_map_Pulse_Lib_Slice_slice__uint8_t;

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_header_map_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_header_map(Pulse_Lib_Slice_slice__uint8_t s);

bool
COSE_Format_is_empty_iterate_array_aux_env34_type_1(
  CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_evercddl_label
  i
);

COSE_Format_evercddl_label
COSE_Format_next_iterate_array_aux_env34_type_1(
  CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_evercddl_label
  *pi
);

bool COSE_Format_validate_empty_or_serialized_map(cbor_det_t c);

typedef struct COSE_Format_empty_or_serialized_map_ugly_s
{
  COSE_Format_evercddl_int_ugly_tags tag;
  union {
    COSE_Format_header_map case_Inl;
    Pulse_Lib_Slice_slice__uint8_t case_Inr;
  }
  ;
}
COSE_Format_empty_or_serialized_map_ugly;

typedef enum { COSE_Format_Mkempty_or_serialized_map0, COSE_Format_Mkempty_or_serialized_map1 }
COSE_Format_empty_or_serialized_map_tags;

typedef struct COSE_Format_empty_or_serialized_map_s
{
  COSE_Format_empty_or_serialized_map_tags tag;
  union {
    COSE_Format_header_map case_Mkempty_or_serialized_map0;
    Pulse_Lib_Slice_slice__uint8_t case_Mkempty_or_serialized_map1;
  }
  ;
}
COSE_Format_empty_or_serialized_map;

COSE_Format_empty_or_serialized_map
COSE_Format_empty_or_serialized_map_right(COSE_Format_empty_or_serialized_map_ugly x2);

COSE_Format_empty_or_serialized_map_ugly
COSE_Format_empty_or_serialized_map_left(COSE_Format_empty_or_serialized_map x8);

/**
Parser for empty_or_serialized_map
*/
COSE_Format_empty_or_serialized_map COSE_Format_parse_empty_or_serialized_map(cbor_det_t c);

/**
Serializer for empty_or_serialized_map
*/
size_t
COSE_Format_serialize_empty_or_serialized_map(
  COSE_Format_empty_or_serialized_map c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct
FStar_Pervasives_Native_tuple2__COSE_Format_empty_or_serialized_map_Pulse_Lib_Slice_slice__uint8_t_s
{
  COSE_Format_empty_or_serialized_map _1;
  Pulse_Lib_Slice_slice__uint8_t _2;
}
FStar_Pervasives_Native_tuple2__COSE_Format_empty_or_serialized_map_Pulse_Lib_Slice_slice__uint8_t;

typedef struct
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_empty_or_serialized_map_Pulse_Lib_Slice_slice__uint8_t_s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  FStar_Pervasives_Native_tuple2__COSE_Format_empty_or_serialized_map_Pulse_Lib_Slice_slice__uint8_t
  v;
}
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_empty_or_serialized_map_Pulse_Lib_Slice_slice__uint8_t;

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_empty_or_serialized_map_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_empty_or_serialized_map(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_sig_structure(cbor_det_t c);

typedef struct
FStar_Pervasives_Native_tuple2__COSE_Format_empty_or_serialized_map_FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t_s
{
  COSE_Format_empty_or_serialized_map _1;
  FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t
  _2;
}
FStar_Pervasives_Native_tuple2__COSE_Format_empty_or_serialized_map_FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t;

typedef struct
FStar_Pervasives_either__FStar_Pervasives_Native_tuple2__COSE_Format_empty_or_serialized_map_FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t_s
{
  COSE_Format_evercddl_int_ugly_tags tag;
  union {
    FStar_Pervasives_Native_tuple2__COSE_Format_empty_or_serialized_map_FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t
    case_Inl;
    FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t
    case_Inr;
  }
  ;
}
FStar_Pervasives_either__FStar_Pervasives_Native_tuple2__COSE_Format_empty_or_serialized_map_FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t;

typedef struct
FStar_Pervasives_Native_tuple2__COSE_Format_empty_or_serialized_map_FStar_Pervasives_either__FStar_Pervasives_Native_tuple2__COSE_Format_empty_or_serialized_map_FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t_s
{
  COSE_Format_empty_or_serialized_map _1;
  FStar_Pervasives_either__FStar_Pervasives_Native_tuple2__COSE_Format_empty_or_serialized_map_FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t
  _2;
}
FStar_Pervasives_Native_tuple2__COSE_Format_empty_or_serialized_map_FStar_Pervasives_either__FStar_Pervasives_Native_tuple2__COSE_Format_empty_or_serialized_map_FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t;

typedef struct COSE_Format_sig_structure_ugly_s
{
  COSE_Format_evercddl_int_ugly_tags _1;
  FStar_Pervasives_Native_tuple2__COSE_Format_empty_or_serialized_map_FStar_Pervasives_either__FStar_Pervasives_Native_tuple2__COSE_Format_empty_or_serialized_map_FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t
  _2;
}
COSE_Format_sig_structure_ugly;

typedef struct COSE_Format_sig_structure_s
{
  COSE_Format_evercddl_int_ugly_tags context;
  COSE_Format_empty_or_serialized_map body_protected;
  FStar_Pervasives_either__FStar_Pervasives_Native_tuple2__COSE_Format_empty_or_serialized_map_FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t_FStar_Pervasives_Native_tuple2__Pulse_Lib_Slice_slice__uint8_t_Pulse_Lib_Slice_slice__uint8_t
  _x0;
}
COSE_Format_sig_structure;

COSE_Format_sig_structure COSE_Format_sig_structure_right(COSE_Format_sig_structure_ugly x3);

COSE_Format_sig_structure_ugly COSE_Format_sig_structure_left(COSE_Format_sig_structure x8);

/**
Parser for sig_structure
*/
COSE_Format_sig_structure COSE_Format_parse_sig_structure(cbor_det_t c);

/**
Serializer for sig_structure
*/
size_t
COSE_Format_serialize_sig_structure(
  COSE_Format_sig_structure c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct
FStar_Pervasives_Native_tuple2__COSE_Format_sig_structure_Pulse_Lib_Slice_slice__uint8_t_s
{
  COSE_Format_sig_structure _1;
  Pulse_Lib_Slice_slice__uint8_t _2;
}
FStar_Pervasives_Native_tuple2__COSE_Format_sig_structure_Pulse_Lib_Slice_slice__uint8_t;

typedef struct
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_sig_structure_Pulse_Lib_Slice_slice__uint8_t_s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  FStar_Pervasives_Native_tuple2__COSE_Format_sig_structure_Pulse_Lib_Slice_slice__uint8_t v;
}
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_sig_structure_Pulse_Lib_Slice_slice__uint8_t;

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_sig_structure_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_sig_structure(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_cose_sign1(cbor_det_t c);

typedef struct
FStar_Pervasives_Native_tuple2__COSE_Format_empty_or_serialized_map_COSE_Format_header_map_s
{
  COSE_Format_empty_or_serialized_map _1;
  COSE_Format_header_map _2;
}
FStar_Pervasives_Native_tuple2__COSE_Format_empty_or_serialized_map_COSE_Format_header_map;

typedef struct FStar_Pervasives_either__Pulse_Lib_Slice_slice__uint8_t____s
{
  COSE_Format_evercddl_int_ugly_tags tag;
  Pulse_Lib_Slice_slice__uint8_t v;
}
FStar_Pervasives_either__Pulse_Lib_Slice_slice__uint8_t___;

typedef struct
FStar_Pervasives_Native_tuple2__FStar_Pervasives_either__Pulse_Lib_Slice_slice__uint8_t____Pulse_Lib_Slice_slice__uint8_t_s
{
  FStar_Pervasives_either__Pulse_Lib_Slice_slice__uint8_t___ _1;
  Pulse_Lib_Slice_slice__uint8_t _2;
}
FStar_Pervasives_Native_tuple2__FStar_Pervasives_either__Pulse_Lib_Slice_slice__uint8_t____Pulse_Lib_Slice_slice__uint8_t;

typedef struct COSE_Format_cose_sign1_ugly_s
{
  FStar_Pervasives_Native_tuple2__COSE_Format_empty_or_serialized_map_COSE_Format_header_map _1;
  FStar_Pervasives_Native_tuple2__FStar_Pervasives_either__Pulse_Lib_Slice_slice__uint8_t____Pulse_Lib_Slice_slice__uint8_t
  _2;
}
COSE_Format_cose_sign1_ugly;

typedef struct COSE_Format_cose_sign1_s
{
  COSE_Format_empty_or_serialized_map protected0;
  COSE_Format_header_map unprotected;
  FStar_Pervasives_either__Pulse_Lib_Slice_slice__uint8_t___ payload;
  Pulse_Lib_Slice_slice__uint8_t signature;
}
COSE_Format_cose_sign1;

COSE_Format_cose_sign1 COSE_Format_cose_sign1_right(COSE_Format_cose_sign1_ugly x4);

COSE_Format_cose_sign1_ugly COSE_Format_cose_sign1_left(COSE_Format_cose_sign1 x10);

/**
Parser for cose_sign1
*/
COSE_Format_cose_sign1 COSE_Format_parse_cose_sign1(cbor_det_t c);

/**
Serializer for cose_sign1
*/
size_t
COSE_Format_serialize_cose_sign1(COSE_Format_cose_sign1 c, Pulse_Lib_Slice_slice__uint8_t out);

typedef struct
FStar_Pervasives_Native_tuple2__COSE_Format_cose_sign1_Pulse_Lib_Slice_slice__uint8_t_s
{
  COSE_Format_cose_sign1 _1;
  Pulse_Lib_Slice_slice__uint8_t _2;
}
FStar_Pervasives_Native_tuple2__COSE_Format_cose_sign1_Pulse_Lib_Slice_slice__uint8_t;

typedef struct
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_cose_sign1_Pulse_Lib_Slice_slice__uint8_t_s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  FStar_Pervasives_Native_tuple2__COSE_Format_cose_sign1_Pulse_Lib_Slice_slice__uint8_t v;
}
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_cose_sign1_Pulse_Lib_Slice_slice__uint8_t;

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_cose_sign1_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_cose_sign1(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_cose_sign1_tagged(cbor_det_t c);

typedef COSE_Format_cose_sign1 COSE_Format_cose_sign1_tagged_ugly;

typedef COSE_Format_cose_sign1 COSE_Format_cose_sign1_tagged;

COSE_Format_cose_sign1 COSE_Format_cose_sign1_tagged_right(COSE_Format_cose_sign1 x1);

COSE_Format_cose_sign1 COSE_Format_cose_sign1_tagged_left(COSE_Format_cose_sign1 x4);

/**
Parser for cose_sign1_tagged
*/
COSE_Format_cose_sign1 COSE_Format_parse_cose_sign1_tagged(cbor_det_t c);

/**
Serializer for cose_sign1_tagged
*/
size_t
COSE_Format_serialize_cose_sign1_tagged(
  COSE_Format_cose_sign1 c,
  Pulse_Lib_Slice_slice__uint8_t out
);

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_cose_sign1_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_cose_sign1_tagged(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_cose_signature(cbor_det_t c);

typedef struct COSE_Format_cose_signature_ugly_s
{
  FStar_Pervasives_Native_tuple2__COSE_Format_empty_or_serialized_map_COSE_Format_header_map _1;
  Pulse_Lib_Slice_slice__uint8_t _2;
}
COSE_Format_cose_signature_ugly;

typedef struct COSE_Format_cose_signature_s
{
  COSE_Format_empty_or_serialized_map protected0;
  COSE_Format_header_map unprotected;
  Pulse_Lib_Slice_slice__uint8_t signature;
}
COSE_Format_cose_signature;

COSE_Format_cose_signature
COSE_Format_cose_signature_right(COSE_Format_cose_signature_ugly x3);

COSE_Format_cose_signature_ugly COSE_Format_cose_signature_left(COSE_Format_cose_signature x8);

/**
Parser for cose_signature
*/
COSE_Format_cose_signature COSE_Format_parse_cose_signature(cbor_det_t c);

/**
Serializer for cose_signature
*/
size_t
COSE_Format_serialize_cose_signature(
  COSE_Format_cose_signature c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct
FStar_Pervasives_Native_tuple2__COSE_Format_cose_signature_Pulse_Lib_Slice_slice__uint8_t_s
{
  COSE_Format_cose_signature _1;
  Pulse_Lib_Slice_slice__uint8_t _2;
}
FStar_Pervasives_Native_tuple2__COSE_Format_cose_signature_Pulse_Lib_Slice_slice__uint8_t;

typedef struct
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_cose_signature_Pulse_Lib_Slice_slice__uint8_t_s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  FStar_Pervasives_Native_tuple2__COSE_Format_cose_signature_Pulse_Lib_Slice_slice__uint8_t v;
}
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_cose_signature_Pulse_Lib_Slice_slice__uint8_t;

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_cose_signature_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_cose_signature(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_aux_env41_validate_1(cbor_det_array_iterator_t *pi);

typedef COSE_Format_cose_signature COSE_Format_aux_env41_type_1_ugly;

typedef COSE_Format_cose_signature COSE_Format_aux_env41_type_1;

COSE_Format_cose_signature COSE_Format_aux_env41_type_1_right(COSE_Format_cose_signature x1);

COSE_Format_cose_signature COSE_Format_aux_env41_type_1_left(COSE_Format_cose_signature x4);

/**
Parser for aux_env41_type_1
*/
COSE_Format_cose_signature COSE_Format_aux_env41_parse_1(cbor_det_array_iterator_t c);

/**
Serializer for aux_env41_type_1
*/
bool
COSE_Format_aux_env41_serialize_1(
  COSE_Format_cose_signature c,
  Pulse_Lib_Slice_slice__uint8_t out,
  uint64_t *out_count,
  size_t *out_size
);

bool COSE_Format_validate_cose_sign(cbor_det_t c);

typedef struct Pulse_Lib_Slice_slice__COSE_Format_cose_signature_s
{
  COSE_Format_cose_signature *elt;
  size_t len;
}
Pulse_Lib_Slice_slice__COSE_Format_cose_signature;

typedef struct
CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_cose_signature_s
{
  cbor_det_array_iterator_t cddl_array_iterator_contents;
  bool (*cddl_array_iterator_impl_validate)(cbor_det_array_iterator_t *x0);
  COSE_Format_cose_signature (*cddl_array_iterator_impl_parse)(cbor_det_array_iterator_t x0);
}
CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_cose_signature;

typedef struct
FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_cose_signature_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_cose_signature_s
{
  COSE_Format_evercddl_int_ugly_tags tag;
  union {
    Pulse_Lib_Slice_slice__COSE_Format_cose_signature case_Inl;
    CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_cose_signature
    case_Inr;
  }
  ;
}
FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_cose_signature_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_cose_signature;

typedef struct
FStar_Pervasives_Native_tuple2__FStar_Pervasives_either__Pulse_Lib_Slice_slice__uint8_t____FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_cose_signature_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_cose_signature_s
{
  FStar_Pervasives_either__Pulse_Lib_Slice_slice__uint8_t___ _1;
  FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_cose_signature_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_cose_signature
  _2;
}
FStar_Pervasives_Native_tuple2__FStar_Pervasives_either__Pulse_Lib_Slice_slice__uint8_t____FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_cose_signature_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_cose_signature;

typedef struct COSE_Format_cose_sign_ugly_s
{
  FStar_Pervasives_Native_tuple2__COSE_Format_empty_or_serialized_map_COSE_Format_header_map _1;
  FStar_Pervasives_Native_tuple2__FStar_Pervasives_either__Pulse_Lib_Slice_slice__uint8_t____FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_cose_signature_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_cose_signature
  _2;
}
COSE_Format_cose_sign_ugly;

typedef struct COSE_Format_cose_sign_s
{
  COSE_Format_empty_or_serialized_map protected0;
  COSE_Format_header_map unprotected;
  FStar_Pervasives_either__Pulse_Lib_Slice_slice__uint8_t___ payload;
  FStar_Pervasives_either__Pulse_Lib_Slice_slice__COSE_Format_cose_signature_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_cose_signature
  signatures;
}
COSE_Format_cose_sign;

COSE_Format_cose_sign COSE_Format_cose_sign_right(COSE_Format_cose_sign_ugly x4);

COSE_Format_cose_sign_ugly COSE_Format_cose_sign_left(COSE_Format_cose_sign x10);

/**
Parser for cose_sign
*/
COSE_Format_cose_sign COSE_Format_parse_cose_sign(cbor_det_t c);

/**
Serializer for cose_sign
*/
size_t
COSE_Format_serialize_cose_sign(COSE_Format_cose_sign c, Pulse_Lib_Slice_slice__uint8_t out);

typedef struct
FStar_Pervasives_Native_tuple2__COSE_Format_cose_sign_Pulse_Lib_Slice_slice__uint8_t_s
{
  COSE_Format_cose_sign _1;
  Pulse_Lib_Slice_slice__uint8_t _2;
}
FStar_Pervasives_Native_tuple2__COSE_Format_cose_sign_Pulse_Lib_Slice_slice__uint8_t;

typedef struct
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_cose_sign_Pulse_Lib_Slice_slice__uint8_t_s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  FStar_Pervasives_Native_tuple2__COSE_Format_cose_sign_Pulse_Lib_Slice_slice__uint8_t v;
}
FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_cose_sign_Pulse_Lib_Slice_slice__uint8_t;

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_cose_sign_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_cose_sign(Pulse_Lib_Slice_slice__uint8_t s);

bool
COSE_Format_is_empty_iterate_array_aux_env41_type_1(
  CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_cose_signature
  i
);

COSE_Format_cose_signature
COSE_Format_next_iterate_array_aux_env41_type_1(
  CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_cose_signature
  *pi
);

bool COSE_Format_validate_cose_sign_tagged(cbor_det_t c);

typedef COSE_Format_cose_sign COSE_Format_cose_sign_tagged_ugly;

typedef COSE_Format_cose_sign COSE_Format_cose_sign_tagged;

COSE_Format_cose_sign COSE_Format_cose_sign_tagged_right(COSE_Format_cose_sign x1);

COSE_Format_cose_sign COSE_Format_cose_sign_tagged_left(COSE_Format_cose_sign x4);

/**
Parser for cose_sign_tagged
*/
COSE_Format_cose_sign COSE_Format_parse_cose_sign_tagged(cbor_det_t c);

/**
Serializer for cose_sign_tagged
*/
size_t
COSE_Format_serialize_cose_sign_tagged(
  COSE_Format_cose_sign c,
  Pulse_Lib_Slice_slice__uint8_t out
);

FStar_Pervasives_Native_option__FStar_Pervasives_Native_tuple2__COSE_Format_cose_sign_Pulse_Lib_Slice_slice__uint8_t
COSE_Format_validate_and_parse_cose_sign_tagged(Pulse_Lib_Slice_slice__uint8_t s);

typedef uint64_t COSE_Format_spect_evercddl_uint;

typedef uint64_t COSE_Format_spect_nint;


#define COSE_Format_H_DEFINED
#endif /* COSE_Format_H */
