<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <OtherFlags>--nowarn:0086 --nowarn:0025 --nowarn:0044 --langversion:5.0 --mlcompatibility</OtherFlags>
    <WarnOn>3390;$(WarnOn)</WarnOn>
    <Name>everparse</Name>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <EnableUnmanagedDebugging>true</EnableUnmanagedDebugging>
    <UseVSHostingProcess>true</UseVSHostingProcess>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="3d\Version.fs" />
    <Compile Include="prims.fs" />
    <Compile Include="FStar_Pervasives_Native.fs" />
    <Compile Include="Hashing_Op.fs" />
    <Compile Include="PackageHashes.fs" />
    <Compile Include="Wrapper.fs" />
  </ItemGroup>
</Project>
