

#ifndef EverParquet_H
#define EverParquet_H

#include "krmllib.h"

#define Parquet_Spec_Toplevel_Types_BOOLEAN 0
#define Parquet_Spec_Toplevel_Types_INT32 1
#define Parquet_Spec_Toplevel_Types_INT64 2
#define Parquet_Spec_Toplevel_Types_INT96 3
#define Parquet_Spec_Toplevel_Types_FLOAT 4
#define Parquet_Spec_Toplevel_Types_DOUBLE 5
#define Parquet_Spec_Toplevel_Types_BYTE_ARRAY 6
#define Parquet_Spec_Toplevel_Types_FIXED_LEN_BYTE_ARRAY 7

typedef uint8_t Parquet_Spec_Toplevel_Types_physical_type;

#define Parquet_Spec_Toplevel_Types_DEPRECATED_UTF8 0
#define Parquet_Spec_Toplevel_Types_DEPRECATED_MAP 1
#define Parquet_Spec_Toplevel_Types_DEPRECATED_MAP_KEY_VALUE 2
#define Parquet_Spec_Toplevel_Types_DEPRECATED_LIST 3
#define Parquet_Spec_Toplevel_Types_DEPRECATED_ENUM 4
#define Parquet_Spec_Toplevel_Types_DEPRECATED_DECIMAL 5
#define Parquet_Spec_Toplevel_Types_DEPRECATED_DATE 6
#define Parquet_Spec_Toplevel_Types_DEPRECATED_TIME_MILLIS 7
#define Parquet_Spec_Toplevel_Types_DEPRECATED_TIME_MICROS 8
#define Parquet_Spec_Toplevel_Types_DEPRECATED_TIMESTAMP_MILLIS 9
#define Parquet_Spec_Toplevel_Types_DEPRECATED_TIMESTAMP_MICROS 10
#define Parquet_Spec_Toplevel_Types_DEPRECATED_UINT_8 11
#define Parquet_Spec_Toplevel_Types_DEPRECATED_UINT_16 12
#define Parquet_Spec_Toplevel_Types_DEPRECATED_UINT_32 13
#define Parquet_Spec_Toplevel_Types_DEPRECATED_UINT_64 14
#define Parquet_Spec_Toplevel_Types_DEPRECATED_INT_8 15
#define Parquet_Spec_Toplevel_Types_DEPRECATED_INT_16 16
#define Parquet_Spec_Toplevel_Types_DEPRECATED_INT_32 17
#define Parquet_Spec_Toplevel_Types_DEPRECATED_INT_64 18
#define Parquet_Spec_Toplevel_Types_DEPRECATED_JSON 19
#define Parquet_Spec_Toplevel_Types_DEPRECATED_BSON 20
#define Parquet_Spec_Toplevel_Types_DEPRECATED_INTERVAL 21

typedef uint8_t Parquet_Spec_Toplevel_Types_converted_type;

#define Parquet_Spec_Toplevel_Types_REQUIRED 0
#define Parquet_Spec_Toplevel_Types_OPTIONAL 1
#define Parquet_Spec_Toplevel_Types_REPEATED 2

typedef uint8_t Parquet_Spec_Toplevel_Types_field_repetition_type;

#define Parquet_Spec_Toplevel_Types_PLAIN 0
#define Parquet_Spec_Toplevel_Types_GROUP_VAR_INT 1
#define Parquet_Spec_Toplevel_Types_PLAIN_DICTIONARY 2
#define Parquet_Spec_Toplevel_Types_RLE 3
#define Parquet_Spec_Toplevel_Types_BIT_PACKED 4
#define Parquet_Spec_Toplevel_Types_DELTA_BINARY_PACKED 5
#define Parquet_Spec_Toplevel_Types_DELTA_LENGTH_BYTE_ARRAY 6
#define Parquet_Spec_Toplevel_Types_DELTA_BYTE_ARRAY 7
#define Parquet_Spec_Toplevel_Types_RLE_DICTIONARY 8
#define Parquet_Spec_Toplevel_Types_BYTE_STREAM_SPLIT 9

typedef uint8_t Parquet_Spec_Toplevel_Types_encoding;

#define Parquet_Spec_Toplevel_Types_UNCOMPRESSED 0
#define Parquet_Spec_Toplevel_Types_SNAPPY 1
#define Parquet_Spec_Toplevel_Types_GZIP 2
#define Parquet_Spec_Toplevel_Types_LZO 3
#define Parquet_Spec_Toplevel_Types_BROTLI 4
#define Parquet_Spec_Toplevel_Types_LZ4 5
#define Parquet_Spec_Toplevel_Types_ZSTD 6
#define Parquet_Spec_Toplevel_Types_LZ4_RAW 7

typedef uint8_t Parquet_Spec_Toplevel_Types_compression_codec;

#define Parquet_Spec_Toplevel_Types_DATA_PAGE 0
#define Parquet_Spec_Toplevel_Types_INDEX_PAGE 1
#define Parquet_Spec_Toplevel_Types_DICTIONARY_PAGE 2
#define Parquet_Spec_Toplevel_Types_DATA_PAGE_V2 3

typedef uint8_t Parquet_Spec_Toplevel_Types_page_type;

#define Parquet_Spec_Toplevel_Types_UNORDERED 0
#define Parquet_Spec_Toplevel_Types_ASCENDING 1
#define Parquet_Spec_Toplevel_Types_DESCENDING 2

typedef uint8_t Parquet_Spec_Toplevel_Types_boundary_order;

#define Parquet_Spec_Toplevel_Types_SPHERICAL 0
#define Parquet_Spec_Toplevel_Types_VINCENTY 1
#define Parquet_Spec_Toplevel_Types_THOMAS 2
#define Parquet_Spec_Toplevel_Types_ANDOYER 3
#define Parquet_Spec_Toplevel_Types_KARNEY 4

typedef uint8_t Parquet_Spec_Toplevel_Types_edge_interpolation_algorithm;

#define FStar_Pervasives_Native_None 0
#define FStar_Pervasives_Native_Some 1

typedef uint8_t FStar_Pervasives_Native_option____;

typedef struct Parquet_Spec_Toplevel_Types_bounding_box_s
{
  FStar_Pervasives_Native_option____ zmin;
  FStar_Pervasives_Native_option____ zmax;
  FStar_Pervasives_Native_option____ mmin;
  FStar_Pervasives_Native_option____ mmax;
}
Parquet_Spec_Toplevel_Types_bounding_box;

typedef struct Parquet_Spec_Toplevel_Types_decimal_type_s
{
  int32_t scale;
  int32_t precision;
}
Parquet_Spec_Toplevel_Types_decimal_type;

#define Parquet_Spec_Toplevel_Types_MILLIS 0
#define Parquet_Spec_Toplevel_Types_MICROS 1
#define Parquet_Spec_Toplevel_Types_NANOS 2

typedef uint8_t Parquet_Spec_Toplevel_Types_time_unit;

typedef struct Parquet_Spec_Toplevel_Types_timestamp_type_s
{
  bool isAdjustedToUTC;
  Parquet_Spec_Toplevel_Types_time_unit unit;
}
Parquet_Spec_Toplevel_Types_timestamp_type;

typedef struct Parquet_Spec_Toplevel_Types_time_type_s
{
  bool isAdjustedToUTC1;
  Parquet_Spec_Toplevel_Types_time_unit unit1;
}
Parquet_Spec_Toplevel_Types_time_type;

typedef struct Parquet_Spec_Toplevel_Types_int_type_s
{
  int8_t bitWidth;
  bool isSigned;
}
Parquet_Spec_Toplevel_Types_int_type;

typedef struct FStar_Pervasives_Native_option__int8_t_s
{
  FStar_Pervasives_Native_option____ tag;
  int8_t v;
}
FStar_Pervasives_Native_option__int8_t;

typedef struct FStar_Pervasives_Native_option__Prims_string_s
{
  FStar_Pervasives_Native_option____ tag;
  Prims_string v;
}
FStar_Pervasives_Native_option__Prims_string;

typedef struct
FStar_Pervasives_Native_option__Parquet_Spec_Toplevel_Types_edge_interpolation_algorithm_s
{
  FStar_Pervasives_Native_option____ tag;
  Parquet_Spec_Toplevel_Types_edge_interpolation_algorithm v;
}
FStar_Pervasives_Native_option__Parquet_Spec_Toplevel_Types_edge_interpolation_algorithm;

typedef struct Parquet_Spec_Toplevel_Types_geography_type_s
{
  FStar_Pervasives_Native_option__Prims_string crs1;
  FStar_Pervasives_Native_option__Parquet_Spec_Toplevel_Types_edge_interpolation_algorithm
  algorithm;
}
Parquet_Spec_Toplevel_Types_geography_type;

#define Parquet_Spec_Toplevel_Types_STRING 0
#define Parquet_Spec_Toplevel_Types_MAP 1
#define Parquet_Spec_Toplevel_Types_LIST 2
#define Parquet_Spec_Toplevel_Types_ENUM 3
#define Parquet_Spec_Toplevel_Types_DECIMAL 4
#define Parquet_Spec_Toplevel_Types_DATE 5
#define Parquet_Spec_Toplevel_Types_TIME 6
#define Parquet_Spec_Toplevel_Types_TIMESTAMP 7
#define Parquet_Spec_Toplevel_Types_INTEGER 8
#define Parquet_Spec_Toplevel_Types_UNKNOWN 9
#define Parquet_Spec_Toplevel_Types_JSON 10
#define Parquet_Spec_Toplevel_Types_BSON 11
#define Parquet_Spec_Toplevel_Types_UUID 12
#define Parquet_Spec_Toplevel_Types_FLOAT16 13
#define Parquet_Spec_Toplevel_Types_VARIANT 14
#define Parquet_Spec_Toplevel_Types_GEOMETRY 15
#define Parquet_Spec_Toplevel_Types_GEOGRAPHY 16

typedef uint8_t Parquet_Spec_Toplevel_Types_logical_type_tags;

typedef struct Parquet_Spec_Toplevel_Types_logical_type_s
{
  Parquet_Spec_Toplevel_Types_logical_type_tags tag;
  union {
    Parquet_Spec_Toplevel_Types_decimal_type case_DECIMAL;
    Parquet_Spec_Toplevel_Types_time_type case_TIME;
    Parquet_Spec_Toplevel_Types_timestamp_type case_TIMESTAMP;
    Parquet_Spec_Toplevel_Types_int_type case_INTEGER;
    FStar_Pervasives_Native_option__int8_t case_VARIANT;
    FStar_Pervasives_Native_option__Prims_string case_GEOMETRY;
    Parquet_Spec_Toplevel_Types_geography_type case_GEOGRAPHY;
  }
  ;
}
Parquet_Spec_Toplevel_Types_logical_type;

typedef struct FStar_Pervasives_Native_option__Parquet_Spec_Toplevel_Types_physical_type_s
{
  FStar_Pervasives_Native_option____ tag;
  Parquet_Spec_Toplevel_Types_physical_type v;
}
FStar_Pervasives_Native_option__Parquet_Spec_Toplevel_Types_physical_type;

typedef struct FStar_Pervasives_Native_option__int32_t_s
{
  FStar_Pervasives_Native_option____ tag;
  int32_t v;
}
FStar_Pervasives_Native_option__int32_t;

typedef struct
FStar_Pervasives_Native_option__Parquet_Spec_Toplevel_Types_field_repetition_type_s
{
  FStar_Pervasives_Native_option____ tag;
  Parquet_Spec_Toplevel_Types_field_repetition_type v;
}
FStar_Pervasives_Native_option__Parquet_Spec_Toplevel_Types_field_repetition_type;

typedef struct FStar_Pervasives_Native_option__Parquet_Spec_Toplevel_Types_converted_type_s
{
  FStar_Pervasives_Native_option____ tag;
  Parquet_Spec_Toplevel_Types_converted_type v;
}
FStar_Pervasives_Native_option__Parquet_Spec_Toplevel_Types_converted_type;

typedef struct FStar_Pervasives_Native_option__Parquet_Spec_Toplevel_Types_logical_type_s
{
  FStar_Pervasives_Native_option____ tag;
  Parquet_Spec_Toplevel_Types_logical_type v;
}
FStar_Pervasives_Native_option__Parquet_Spec_Toplevel_Types_logical_type;

typedef struct Parquet_Spec_Toplevel_Types_schema_element_s
{
  FStar_Pervasives_Native_option__Parquet_Spec_Toplevel_Types_physical_type type_;
  FStar_Pervasives_Native_option__int32_t type_length;
  FStar_Pervasives_Native_option__Parquet_Spec_Toplevel_Types_field_repetition_type
  repetition_type;
  Prims_string name;
  FStar_Pervasives_Native_option__int32_t num_children;
  FStar_Pervasives_Native_option__Parquet_Spec_Toplevel_Types_converted_type converted_type;
  FStar_Pervasives_Native_option__int32_t scale1;
  FStar_Pervasives_Native_option__int32_t precision1;
  FStar_Pervasives_Native_option__int32_t field_id;
  FStar_Pervasives_Native_option__Parquet_Spec_Toplevel_Types_logical_type logical_type;
}
Parquet_Spec_Toplevel_Types_schema_element;

typedef struct FStar_Pervasives_Native_option__bool_s
{
  FStar_Pervasives_Native_option____ tag;
  bool v;
}
FStar_Pervasives_Native_option__bool;

typedef struct Parquet_Spec_Toplevel_Types_dictionary_page_header_s
{
  int32_t num_values1;
  Parquet_Spec_Toplevel_Types_encoding encoding;
  FStar_Pervasives_Native_option__bool is_sorted;
}
Parquet_Spec_Toplevel_Types_dictionary_page_header;

#define Parquet_Spec_Toplevel_Types_BLOCK 0

typedef uint8_t Parquet_Spec_Toplevel_Types_bloom_filter_algorithm;

#define Parquet_Spec_Toplevel_Types_XXHASH 0

typedef uint8_t Parquet_Spec_Toplevel_Types_bloom_filter_hash;

#define Parquet_Spec_Toplevel_Types_UN_COMPRESSED 0

typedef uint8_t Parquet_Spec_Toplevel_Types_bloom_filter_compression;

typedef struct Parquet_Spec_Toplevel_Types_bloom_filter_header_s
{
  int32_t numBytes;
  Parquet_Spec_Toplevel_Types_bloom_filter_algorithm algorithm1;
  Parquet_Spec_Toplevel_Types_bloom_filter_hash hash;
  Parquet_Spec_Toplevel_Types_bloom_filter_compression compression;
}
Parquet_Spec_Toplevel_Types_bloom_filter_header;

typedef struct Parquet_Spec_Toplevel_Types_key_value_s
{
  Prims_string key;
  FStar_Pervasives_Native_option__Prims_string value;
}
Parquet_Spec_Toplevel_Types_key_value;

typedef struct Parquet_Spec_Toplevel_Types_sorting_column_s
{
  int32_t column_idx;
  bool descending;
  bool nulls_first;
}
Parquet_Spec_Toplevel_Types_sorting_column;

typedef struct Parquet_Spec_Toplevel_Types_page_encoding_stats_s
{
  Parquet_Spec_Toplevel_Types_page_type page_type;
  Parquet_Spec_Toplevel_Types_encoding encoding2;
  int32_t count;
}
Parquet_Spec_Toplevel_Types_page_encoding_stats;

#define Parquet_Spec_Toplevel_Types_TYPE_ORDER 0

typedef uint8_t Parquet_Spec_Toplevel_Types_column_order;

typedef struct Parquet_Spec_Toplevel_Types_page_location_s
{
  int64_t offset;
  int32_t compressed_page_size1;
  int64_t first_row_index;
}
Parquet_Spec_Toplevel_Types_page_location;

typedef struct Parquet_Spec_Toplevel_Types_aes_gcm_v1_s
{
  FStar_Pervasives_Native_option__Prims_string aad_prefix;
  FStar_Pervasives_Native_option__Prims_string aad_file_unique;
  FStar_Pervasives_Native_option__bool supply_aad_prefix;
}
Parquet_Spec_Toplevel_Types_aes_gcm_v1;

typedef struct Parquet_Spec_Toplevel_Types_aes_gcm_ctr_v1_s
{
  FStar_Pervasives_Native_option__Prims_string aad_prefix1;
  FStar_Pervasives_Native_option__Prims_string aad_file_unique1;
  FStar_Pervasives_Native_option__bool supply_aad_prefix1;
}
Parquet_Spec_Toplevel_Types_aes_gcm_ctr_v1;

#define Parquet_Spec_Toplevel_Types_AES_GCM_V1 0
#define Parquet_Spec_Toplevel_Types_AES_GCM_CTR_V1 1

typedef uint8_t Parquet_Spec_Toplevel_Types_encryption_algorithm_tags;

typedef struct Parquet_Spec_Toplevel_Types_encryption_algorithm_s
{
  Parquet_Spec_Toplevel_Types_encryption_algorithm_tags tag;
  union {
    Parquet_Spec_Toplevel_Types_aes_gcm_v1 case_AES_GCM_V1;
    Parquet_Spec_Toplevel_Types_aes_gcm_ctr_v1 case_AES_GCM_CTR_V1;
  }
  ;
}
Parquet_Spec_Toplevel_Types_encryption_algorithm;

typedef struct Parquet_Spec_Toplevel_Types_file_crypto_meta_data_s
{
  Parquet_Spec_Toplevel_Types_encryption_algorithm encryption_algorithm1;
  FStar_Pervasives_Native_option__Prims_string key_metadata1;
}
Parquet_Spec_Toplevel_Types_file_crypto_meta_data;

typedef uint8_t Parquet_Pulse_Toplevel_byte;

typedef struct Parquet_Pulse_Toplevel_bytes_s
{
  uint8_t *data;
  size_t len;
}
Parquet_Pulse_Toplevel_bytes;

typedef Parquet_Spec_Toplevel_Types_physical_type Parquet_Pulse_Toplevel_physical_type;

typedef Parquet_Spec_Toplevel_Types_converted_type Parquet_Pulse_Toplevel_converted_type;

typedef Parquet_Spec_Toplevel_Types_field_repetition_type
Parquet_Pulse_Toplevel_field_repetition_type;

typedef Parquet_Spec_Toplevel_Types_encoding Parquet_Pulse_Toplevel_encoding;

typedef Parquet_Spec_Toplevel_Types_compression_codec Parquet_Pulse_Toplevel_compression_codec;

typedef Parquet_Spec_Toplevel_Types_page_type Parquet_Pulse_Toplevel_page_type;

typedef Parquet_Spec_Toplevel_Types_boundary_order Parquet_Pulse_Toplevel_boundary_order;

typedef Parquet_Spec_Toplevel_Types_edge_interpolation_algorithm
Parquet_Pulse_Toplevel_edge_interpolation_algorithm;

typedef int64_t Parquet_Pulse_Toplevel_int64;

typedef int32_t Parquet_Pulse_Toplevel_int32;

typedef int16_t Parquet_Pulse_Toplevel_int16;

typedef int8_t Parquet_Pulse_Toplevel_int8;

typedef struct FStar_Pervasives_Native_option__int64_t_s
{
  FStar_Pervasives_Native_option____ tag;
  int64_t v;
}
FStar_Pervasives_Native_option__int64_t;

typedef struct Parquet_Pulse_Vec_vec__int64_t_s
{
  int64_t *data;
  size_t len;
}
Parquet_Pulse_Vec_vec__int64_t;

typedef struct FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_int64_t_s
{
  FStar_Pervasives_Native_option____ tag;
  Parquet_Pulse_Vec_vec__int64_t v;
}
FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_int64_t;

typedef struct Parquet_Pulse_Toplevel_size_statistics_s
{
  FStar_Pervasives_Native_option__int64_t unencoded_byte_array_data_bytes;
  FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_int64_t repetition_level_histogram;
  FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_int64_t definition_level_histogram;
}
Parquet_Pulse_Toplevel_size_statistics;

typedef Parquet_Spec_Toplevel_Types_bounding_box Parquet_Pulse_Toplevel_bounding_box;

typedef struct FStar_Pervasives_Native_option__Parquet_Spec_Toplevel_Types_bounding_box_s
{
  FStar_Pervasives_Native_option____ tag;
  Parquet_Spec_Toplevel_Types_bounding_box v;
}
FStar_Pervasives_Native_option__Parquet_Spec_Toplevel_Types_bounding_box;

typedef struct Parquet_Pulse_Vec_vec__int32_t_s
{
  int32_t *data;
  size_t len;
}
Parquet_Pulse_Vec_vec__int32_t;

typedef struct FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_int32_t_s
{
  FStar_Pervasives_Native_option____ tag;
  Parquet_Pulse_Vec_vec__int32_t v;
}
FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_int32_t;

typedef struct Parquet_Pulse_Toplevel_geospatial_statistics_s
{
  FStar_Pervasives_Native_option__Parquet_Spec_Toplevel_Types_bounding_box bbox;
  FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_int32_t geospatial_types;
}
Parquet_Pulse_Toplevel_geospatial_statistics;

typedef struct FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_uint8_t_s
{
  FStar_Pervasives_Native_option____ tag;
  Parquet_Pulse_Toplevel_bytes v;
}
FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_uint8_t;

typedef struct Parquet_Pulse_Toplevel_statistics_s
{
  FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_uint8_t max;
  FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_uint8_t min;
  FStar_Pervasives_Native_option__int64_t null_count;
  FStar_Pervasives_Native_option__int64_t distinct_count;
  FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_uint8_t max_value;
  FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_uint8_t min_value;
  FStar_Pervasives_Native_option__bool is_max_value_exact;
  FStar_Pervasives_Native_option__bool is_min_value_exact;
}
Parquet_Pulse_Toplevel_statistics;

typedef void *Parquet_Pulse_Toplevel_string_type;

typedef void *Parquet_Pulse_Toplevel_uuid_type;

typedef void *Parquet_Pulse_Toplevel_map_type;

typedef void *Parquet_Pulse_Toplevel_list_type;

typedef void *Parquet_Pulse_Toplevel_enum_type;

typedef void *Parquet_Pulse_Toplevel_date_type;

typedef void *Parquet_Pulse_Toplevel_float16_type;

typedef void *Parquet_Pulse_Toplevel_null_type;

typedef void *Parquet_Pulse_Toplevel_json_type;

typedef void *Parquet_Pulse_Toplevel_bson_type;

typedef Parquet_Spec_Toplevel_Types_decimal_type Parquet_Pulse_Toplevel_decimal_type;

typedef void *Parquet_Pulse_Toplevel_milli_seconds;

typedef void *Parquet_Pulse_Toplevel_micro_seconds;

typedef void *Parquet_Pulse_Toplevel_nano_seconds;

typedef Parquet_Spec_Toplevel_Types_time_unit Parquet_Pulse_Toplevel_time_unit;

typedef Parquet_Spec_Toplevel_Types_timestamp_type Parquet_Pulse_Toplevel_timestamp_type;

typedef Parquet_Spec_Toplevel_Types_time_type Parquet_Pulse_Toplevel_time_type;

typedef Parquet_Spec_Toplevel_Types_int_type Parquet_Pulse_Toplevel_int_type;

typedef FStar_Pervasives_Native_option__int8_t Parquet_Pulse_Toplevel_variant_type;

typedef FStar_Pervasives_Native_option__Prims_string Parquet_Pulse_Toplevel_geometry_type;

typedef Parquet_Spec_Toplevel_Types_geography_type Parquet_Pulse_Toplevel_geography_type;

typedef Parquet_Spec_Toplevel_Types_logical_type Parquet_Pulse_Toplevel_logical_type;

typedef Parquet_Spec_Toplevel_Types_schema_element Parquet_Pulse_Toplevel_schema_element;

typedef struct FStar_Pervasives_Native_option__Parquet_Pulse_Toplevel_statistics_s
{
  FStar_Pervasives_Native_option____ tag;
  Parquet_Pulse_Toplevel_statistics v;
}
FStar_Pervasives_Native_option__Parquet_Pulse_Toplevel_statistics;

typedef struct Parquet_Pulse_Toplevel_data_page_header_s
{
  int32_t num_values;
  Parquet_Spec_Toplevel_Types_encoding encoding_;
  Parquet_Spec_Toplevel_Types_encoding definition_level_encoding;
  Parquet_Spec_Toplevel_Types_encoding repetition_level_encoding;
  FStar_Pervasives_Native_option__Parquet_Pulse_Toplevel_statistics statistics;
}
Parquet_Pulse_Toplevel_data_page_header;

typedef void *Parquet_Pulse_Toplevel_index_page_header;

typedef Parquet_Spec_Toplevel_Types_dictionary_page_header
Parquet_Pulse_Toplevel_dictionary_page_header;

typedef struct Parquet_Pulse_Toplevel_data_page_header_v2_s
{
  int32_t num_values1;
  int32_t num_nulls;
  int32_t num_rows;
  Parquet_Spec_Toplevel_Types_encoding encoding;
  int32_t definition_levels_byte_length;
  int32_t repetition_levels_byte_length;
  FStar_Pervasives_Native_option__bool is_compressed;
  FStar_Pervasives_Native_option__Parquet_Pulse_Toplevel_statistics statistics1;
}
Parquet_Pulse_Toplevel_data_page_header_v2;

typedef void *Parquet_Pulse_Toplevel_split_block_algorithm;

typedef Parquet_Spec_Toplevel_Types_bloom_filter_algorithm
Parquet_Pulse_Toplevel_bloom_filter_algorithm;

typedef void *Parquet_Pulse_Toplevel_xx_hash;

typedef Parquet_Spec_Toplevel_Types_bloom_filter_hash Parquet_Pulse_Toplevel_bloom_filter_hash;

typedef void *Parquet_Pulse_Toplevel_uncompressed;

typedef Parquet_Spec_Toplevel_Types_bloom_filter_compression
Parquet_Pulse_Toplevel_bloom_filter_compression;

typedef Parquet_Spec_Toplevel_Types_bloom_filter_header
Parquet_Pulse_Toplevel_bloom_filter_header;

typedef struct FStar_Pervasives_Native_option__Parquet_Pulse_Toplevel_data_page_header_s
{
  FStar_Pervasives_Native_option____ tag;
  Parquet_Pulse_Toplevel_data_page_header v;
}
FStar_Pervasives_Native_option__Parquet_Pulse_Toplevel_data_page_header;

typedef struct
FStar_Pervasives_Native_option__Parquet_Spec_Toplevel_Types_dictionary_page_header_s
{
  FStar_Pervasives_Native_option____ tag;
  Parquet_Spec_Toplevel_Types_dictionary_page_header v;
}
FStar_Pervasives_Native_option__Parquet_Spec_Toplevel_Types_dictionary_page_header;

typedef struct FStar_Pervasives_Native_option__Parquet_Pulse_Toplevel_data_page_header_v2_s
{
  FStar_Pervasives_Native_option____ tag;
  Parquet_Pulse_Toplevel_data_page_header_v2 v;
}
FStar_Pervasives_Native_option__Parquet_Pulse_Toplevel_data_page_header_v2;

typedef struct Parquet_Pulse_Toplevel_page_header_s
{
  Parquet_Spec_Toplevel_Types_page_type ptype;
  int32_t uncompressed_page_size;
  int32_t compressed_page_size;
  FStar_Pervasives_Native_option__int32_t crc;
  FStar_Pervasives_Native_option__Parquet_Pulse_Toplevel_data_page_header data_page_header;
  FStar_Pervasives_Native_option____ index_page_header;
  FStar_Pervasives_Native_option__Parquet_Spec_Toplevel_Types_dictionary_page_header
  dictionary_page_header;
  FStar_Pervasives_Native_option__Parquet_Pulse_Toplevel_data_page_header_v2 data_page_header_v2;
}
Parquet_Pulse_Toplevel_page_header;

typedef Parquet_Spec_Toplevel_Types_key_value Parquet_Pulse_Toplevel_key_value;

typedef Parquet_Spec_Toplevel_Types_sorting_column Parquet_Pulse_Toplevel_sorting_column;

typedef Parquet_Spec_Toplevel_Types_page_encoding_stats
Parquet_Pulse_Toplevel_page_encoding_stats;

typedef struct Parquet_Pulse_Vec_vec__Parquet_Spec_Toplevel_Types_encoding_s
{
  Parquet_Spec_Toplevel_Types_encoding *data;
  size_t len;
}
Parquet_Pulse_Vec_vec__Parquet_Spec_Toplevel_Types_encoding;

typedef struct Parquet_Pulse_Vec_vec__Prims_string_s
{
  Prims_string *data;
  size_t len;
}
Parquet_Pulse_Vec_vec__Prims_string;

typedef struct Parquet_Pulse_Vec_vec__Parquet_Spec_Toplevel_Types_key_value_s
{
  Parquet_Spec_Toplevel_Types_key_value *data;
  size_t len;
}
Parquet_Pulse_Vec_vec__Parquet_Spec_Toplevel_Types_key_value;

typedef struct
FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_Parquet_Spec_Toplevel_Types_key_value_s
{
  FStar_Pervasives_Native_option____ tag;
  Parquet_Pulse_Vec_vec__Parquet_Spec_Toplevel_Types_key_value v;
}
FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_Parquet_Spec_Toplevel_Types_key_value;

typedef struct Parquet_Pulse_Vec_vec__Parquet_Spec_Toplevel_Types_page_encoding_stats_s
{
  Parquet_Spec_Toplevel_Types_page_encoding_stats *data;
  size_t len;
}
Parquet_Pulse_Vec_vec__Parquet_Spec_Toplevel_Types_page_encoding_stats;

typedef struct
FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_Parquet_Spec_Toplevel_Types_page_encoding_stats_s
{
  FStar_Pervasives_Native_option____ tag;
  Parquet_Pulse_Vec_vec__Parquet_Spec_Toplevel_Types_page_encoding_stats v;
}
FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_Parquet_Spec_Toplevel_Types_page_encoding_stats;

typedef struct FStar_Pervasives_Native_option__Parquet_Pulse_Toplevel_size_statistics_s
{
  FStar_Pervasives_Native_option____ tag;
  Parquet_Pulse_Toplevel_size_statistics v;
}
FStar_Pervasives_Native_option__Parquet_Pulse_Toplevel_size_statistics;

typedef struct FStar_Pervasives_Native_option__Parquet_Pulse_Toplevel_geospatial_statistics_s
{
  FStar_Pervasives_Native_option____ tag;
  Parquet_Pulse_Toplevel_geospatial_statistics v;
}
FStar_Pervasives_Native_option__Parquet_Pulse_Toplevel_geospatial_statistics;

typedef struct Parquet_Pulse_Toplevel_column_meta_data_s
{
  Parquet_Spec_Toplevel_Types_physical_type physical_type;
  Parquet_Pulse_Vec_vec__Parquet_Spec_Toplevel_Types_encoding encodings;
  Parquet_Pulse_Vec_vec__Prims_string path_in_schema;
  Parquet_Spec_Toplevel_Types_compression_codec codec;
  int64_t num_values2;
  int64_t total_uncompressed_size;
  int64_t total_compressed_size;
  FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_Parquet_Spec_Toplevel_Types_key_value
  key_value_metadata;
  int64_t data_page_offset;
  FStar_Pervasives_Native_option__int64_t index_page_offset;
  FStar_Pervasives_Native_option__int64_t dictionary_page_offset;
  FStar_Pervasives_Native_option__Parquet_Pulse_Toplevel_statistics statistics2;
  FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_Parquet_Spec_Toplevel_Types_page_encoding_stats
  encoding_stats;
  FStar_Pervasives_Native_option__int64_t bloom_filter_offset;
  FStar_Pervasives_Native_option__int32_t bloom_filter_length;
  FStar_Pervasives_Native_option__Parquet_Pulse_Toplevel_size_statistics size_statistics;
  FStar_Pervasives_Native_option__Parquet_Pulse_Toplevel_geospatial_statistics
  geospatial_statistics;
}
Parquet_Pulse_Toplevel_column_meta_data;

typedef void *Parquet_Pulse_Toplevel_encryption_with_footer_key;

typedef struct Parquet_Pulse_Toplevel_encryption_with_column_key_s
{
  Parquet_Pulse_Vec_vec__Prims_string path_in_schema1;
  FStar_Pervasives_Native_option__Prims_string key_metadata;
}
Parquet_Pulse_Toplevel_encryption_with_column_key;

#define Parquet_Pulse_Toplevel_ENCRYPTION_WITH_FOOTER_KEY 0
#define Parquet_Pulse_Toplevel_ENCRYPTION_WITH_COLUMN_KEY 1

typedef uint8_t Parquet_Pulse_Toplevel_column_crypto_meta_data_tags;

typedef struct Parquet_Pulse_Toplevel_column_crypto_meta_data_s
{
  Parquet_Pulse_Toplevel_column_crypto_meta_data_tags tag;
  Parquet_Pulse_Toplevel_encryption_with_column_key _0;
}
Parquet_Pulse_Toplevel_column_crypto_meta_data;

bool
Parquet_Pulse_Toplevel_uu___is_ENCRYPTION_WITH_FOOTER_KEY(
  Parquet_Pulse_Toplevel_column_crypto_meta_data projectee
);

bool
Parquet_Pulse_Toplevel_uu___is_ENCRYPTION_WITH_COLUMN_KEY(
  Parquet_Pulse_Toplevel_column_crypto_meta_data projectee
);

typedef struct FStar_Pervasives_Native_option__Parquet_Pulse_Toplevel_column_meta_data_s
{
  FStar_Pervasives_Native_option____ tag;
  Parquet_Pulse_Toplevel_column_meta_data v;
}
FStar_Pervasives_Native_option__Parquet_Pulse_Toplevel_column_meta_data;

typedef struct FStar_Pervasives_Native_option__Parquet_Pulse_Toplevel_column_crypto_meta_data_s
{
  FStar_Pervasives_Native_option____ tag;
  Parquet_Pulse_Toplevel_column_crypto_meta_data v;
}
FStar_Pervasives_Native_option__Parquet_Pulse_Toplevel_column_crypto_meta_data;

typedef struct Parquet_Pulse_Toplevel_column_chunk_s
{
  FStar_Pervasives_Native_option__Prims_string file_path;
  int64_t file_offset;
  FStar_Pervasives_Native_option__Parquet_Pulse_Toplevel_column_meta_data meta_data;
  FStar_Pervasives_Native_option__int64_t offset_index_offset;
  FStar_Pervasives_Native_option__int32_t offset_index_length;
  FStar_Pervasives_Native_option__int64_t column_index_offset;
  FStar_Pervasives_Native_option__int32_t column_index_length;
  FStar_Pervasives_Native_option__Parquet_Pulse_Toplevel_column_crypto_meta_data crypto_metadata;
  FStar_Pervasives_Native_option__Prims_string encrypted_column_metadata;
}
Parquet_Pulse_Toplevel_column_chunk;

typedef struct Parquet_Pulse_Vec_vec__Parquet_Pulse_Toplevel_column_chunk_s
{
  Parquet_Pulse_Toplevel_column_chunk *data;
  size_t len;
}
Parquet_Pulse_Vec_vec__Parquet_Pulse_Toplevel_column_chunk;

typedef struct Parquet_Pulse_Vec_vec__Parquet_Spec_Toplevel_Types_sorting_column_s
{
  Parquet_Spec_Toplevel_Types_sorting_column *data;
  size_t len;
}
Parquet_Pulse_Vec_vec__Parquet_Spec_Toplevel_Types_sorting_column;

typedef struct
FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_Parquet_Spec_Toplevel_Types_sorting_column_s
{
  FStar_Pervasives_Native_option____ tag;
  Parquet_Pulse_Vec_vec__Parquet_Spec_Toplevel_Types_sorting_column v;
}
FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_Parquet_Spec_Toplevel_Types_sorting_column;

typedef struct FStar_Pervasives_Native_option__int16_t_s
{
  FStar_Pervasives_Native_option____ tag;
  int16_t v;
}
FStar_Pervasives_Native_option__int16_t;

typedef struct Parquet_Pulse_Toplevel_row_group_s
{
  Parquet_Pulse_Vec_vec__Parquet_Pulse_Toplevel_column_chunk columns;
  int64_t total_byte_size;
  int64_t num_rows1;
  FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_Parquet_Spec_Toplevel_Types_sorting_column
  sorting_columns;
  FStar_Pervasives_Native_option__int64_t file_offset1;
  FStar_Pervasives_Native_option__int64_t total_compressed_size1;
  FStar_Pervasives_Native_option__int16_t ordinal;
}
Parquet_Pulse_Toplevel_row_group;

typedef void *Parquet_Pulse_Toplevel_type_defined_order;

typedef Parquet_Spec_Toplevel_Types_column_order Parquet_Pulse_Toplevel_column_order;

typedef Parquet_Spec_Toplevel_Types_page_location Parquet_Pulse_Toplevel_page_location;

typedef struct Parquet_Pulse_Vec_vec__Parquet_Spec_Toplevel_Types_page_location_s
{
  Parquet_Spec_Toplevel_Types_page_location *data;
  size_t len;
}
Parquet_Pulse_Vec_vec__Parquet_Spec_Toplevel_Types_page_location;

typedef struct Parquet_Pulse_Toplevel_offset_index_s
{
  Parquet_Pulse_Vec_vec__Parquet_Spec_Toplevel_Types_page_location page_locations;
  FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_int64_t unencoded_byte_array_data_bytes1;
}
Parquet_Pulse_Toplevel_offset_index;

typedef struct Parquet_Pulse_Vec_vec__bool_s
{
  bool *data;
  size_t len;
}
Parquet_Pulse_Vec_vec__bool;

typedef struct Parquet_Pulse_Toplevel_column_index_s
{
  Parquet_Pulse_Vec_vec__bool null_pages;
  Parquet_Pulse_Vec_vec__Prims_string min_values;
  Parquet_Pulse_Vec_vec__Prims_string max_values;
  Parquet_Spec_Toplevel_Types_boundary_order boundary_order;
  FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_int64_t null_counts;
  FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_int64_t repetition_level_histograms;
  FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_int64_t definition_level_histograms;
}
Parquet_Pulse_Toplevel_column_index;

typedef Parquet_Spec_Toplevel_Types_aes_gcm_v1 Parquet_Pulse_Toplevel_aes_gcm_v1;

typedef Parquet_Spec_Toplevel_Types_aes_gcm_ctr_v1 Parquet_Pulse_Toplevel_aes_gcm_ctr_v1;

typedef Parquet_Spec_Toplevel_Types_encryption_algorithm
Parquet_Pulse_Toplevel_encryption_algorithm;

typedef struct Parquet_Pulse_Vec_vec__Parquet_Spec_Toplevel_Types_schema_element_s
{
  Parquet_Spec_Toplevel_Types_schema_element *data;
  size_t len;
}
Parquet_Pulse_Vec_vec__Parquet_Spec_Toplevel_Types_schema_element;

typedef struct Parquet_Pulse_Vec_vec__Parquet_Pulse_Toplevel_row_group_s
{
  Parquet_Pulse_Toplevel_row_group *data;
  size_t len;
}
Parquet_Pulse_Vec_vec__Parquet_Pulse_Toplevel_row_group;

typedef struct Parquet_Pulse_Vec_vec__Parquet_Spec_Toplevel_Types_column_order_s
{
  Parquet_Spec_Toplevel_Types_column_order *data;
  size_t len;
}
Parquet_Pulse_Vec_vec__Parquet_Spec_Toplevel_Types_column_order;

typedef struct
FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_Parquet_Spec_Toplevel_Types_column_order_s
{
  FStar_Pervasives_Native_option____ tag;
  Parquet_Pulse_Vec_vec__Parquet_Spec_Toplevel_Types_column_order v;
}
FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_Parquet_Spec_Toplevel_Types_column_order;

typedef struct
FStar_Pervasives_Native_option__Parquet_Spec_Toplevel_Types_encryption_algorithm_s
{
  FStar_Pervasives_Native_option____ tag;
  Parquet_Spec_Toplevel_Types_encryption_algorithm v;
}
FStar_Pervasives_Native_option__Parquet_Spec_Toplevel_Types_encryption_algorithm;

typedef struct Parquet_Pulse_Toplevel_file_meta_data_s
{
  int32_t version;
  Parquet_Pulse_Vec_vec__Parquet_Spec_Toplevel_Types_schema_element schema;
  int64_t num_rows2;
  Parquet_Pulse_Vec_vec__Parquet_Pulse_Toplevel_row_group row_groups;
  FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_Parquet_Spec_Toplevel_Types_key_value
  key_value_metadata1;
  FStar_Pervasives_Native_option__Prims_string created_by;
  FStar_Pervasives_Native_option__Parquet_Pulse_Vec_vec_Parquet_Spec_Toplevel_Types_column_order
  column_orders;
  FStar_Pervasives_Native_option__Parquet_Spec_Toplevel_Types_encryption_algorithm
  encryption_algorithm;
  FStar_Pervasives_Native_option__Prims_string footer_signing_key_metadata;
}
Parquet_Pulse_Toplevel_file_meta_data;

typedef Parquet_Spec_Toplevel_Types_file_crypto_meta_data
Parquet_Pulse_Toplevel_file_crypto_meta_data;

typedef struct Pulse_Lib_Slice_slice__uint8_t_s
{
  uint8_t *elt;
  size_t len;
}
Pulse_Lib_Slice_slice__uint8_t;

bool Parquet_Pulse_Toplevel0_validate_is_PAR1(Pulse_Lib_Slice_slice__uint8_t input);

extern bool
Parquet_Pulse_Toplevel0_validate_footer(Pulse_Lib_Slice_slice__uint8_t uu___, size_t *x0);

extern Parquet_Pulse_Toplevel_file_meta_data
Parquet_Pulse_Toplevel0_read_footer(Pulse_Lib_Slice_slice__uint8_t uu___);

FStar_Pervasives_Native_option__int64_t
Parquet_Pulse_Toplevel0_compute_cols_size(
  bool *poverflow,
  Parquet_Pulse_Vec_vec__Parquet_Pulse_Toplevel_column_chunk cc,
  int64_t bound
);

bool
Parquet_Pulse_Toplevel0_impl_column_size_nonnegative(Parquet_Pulse_Toplevel_column_chunk cc);

int64_t
Parquet_Pulse_Toplevel0_impl_offset_of_column_chunk(Parquet_Pulse_Toplevel_column_meta_data cc);

bool
Parquet_Pulse_Toplevel0_impl_validate_column_chunk_offsets_ok(
  Parquet_Pulse_Toplevel_column_chunk cc
);

bool
Parquet_Pulse_Toplevel0_impl_validate_column_chunk_idx_ok(
  Parquet_Pulse_Toplevel_column_chunk cc
);

bool
Parquet_Pulse_Toplevel0_impl_validate_column_chunk(Parquet_Pulse_Toplevel_column_chunk cc);

int64_t
Parquet_Pulse_Toplevel0_impl_column_chunk_offset(Parquet_Pulse_Toplevel_column_chunk cc);

int64_t Parquet_Pulse_Toplevel0_impl_column_chunk_size(Parquet_Pulse_Toplevel_column_chunk cc);

bool
Parquet_Pulse_Toplevel0_impl_column_chunk_some_meta_data(
  Parquet_Pulse_Toplevel_column_chunk cc
);

bool
Parquet_Pulse_Toplevel0_impl_validate_row_group_sorted_ok(Parquet_Pulse_Toplevel_row_group rg);

bool Parquet_Pulse_Toplevel0_impl_validate_row_group_aux(Parquet_Pulse_Toplevel_row_group rg);

FStar_Pervasives_Native_option__int64_t
Parquet_Pulse_Toplevel0_impl_first_column_offset(Parquet_Pulse_Toplevel_row_group rg);

typedef struct K___int64_t_int64_t_s
{
  int64_t fst;
  int64_t snd;
}
K___int64_t_int64_t;

typedef struct FStar_Pervasives_Native_option___int64_t___int64_t__s
{
  FStar_Pervasives_Native_option____ tag;
  K___int64_t_int64_t v;
}
FStar_Pervasives_Native_option___int64_t___int64_t_;

FStar_Pervasives_Native_option___int64_t___int64_t_
Parquet_Pulse_Toplevel0_impl_rg_range(
  Parquet_Pulse_Toplevel_row_group rg,
  FStar_Pervasives_Native_option__int64_t csz
);

bool
Parquet_Pulse_Toplevel0_impl_disjoint(
  FStar_Pervasives_Native_option___int64_t___int64_t_ rg,
  FStar_Pervasives_Native_option___int64_t___int64_t_ rg1
);

bool
Parquet_Pulse_Toplevel0_impl_rg_disjoint(
  FStar_Pervasives_Native_option___int64_t___int64_t_ rg,
  size_t n,
  FStar_Pervasives_Native_option___int64_t___int64_t_ *crg,
  size_t i
);

bool
Parquet_Pulse_Toplevel0_impl_validate_file_meta_data_aux(
  int64_t data_size,
  Parquet_Pulse_Vec_vec__Parquet_Pulse_Toplevel_row_group l
);

bool
Parquet_Pulse_Toplevel0_impl_validate_file_meta_data(
  size_t footer_start,
  Parquet_Pulse_Toplevel_file_meta_data md
);

extern bool
Parquet_Pulse_Toplevel0_validate_page_header(Pulse_Lib_Slice_slice__uint8_t uu___, size_t *x0);

extern Parquet_Pulse_Toplevel_page_header
Parquet_Pulse_Toplevel0_read_page_header(Pulse_Lib_Slice_slice__uint8_t uu___);

bool
Parquet_Pulse_Toplevel0_impl_validate_page_data(
  Pulse_Lib_Slice_slice__uint8_t ph,
  Pulse_Lib_Slice_slice__uint8_t data
);

bool
Parquet_Pulse_Toplevel0_validate_page(Pulse_Lib_Slice_slice__uint8_t input, size_t *poffset);

bool
Parquet_Pulse_Toplevel0_validate_jump_page(
  size_t offset_sz,
  size_t size_sz,
  Pulse_Lib_Slice_slice__uint8_t data,
  Parquet_Spec_Toplevel_Types_page_location pl,
  Pulse_Lib_Slice_slice__uint8_t input
);

bool
Parquet_Pulse_Toplevel0_impl_validate_page_location_all(
  Pulse_Lib_Slice_slice__uint8_t data,
  Parquet_Spec_Toplevel_Types_page_location pl
);

bool
Parquet_Pulse_Toplevel0_impl_validate_offset_index_all_aux(
  Pulse_Lib_Slice_slice__uint8_t data,
  Parquet_Pulse_Toplevel_offset_index oi
);

bool
Parquet_Pulse_Toplevel0_impl_validate_offset_index_first_loc(
  Parquet_Pulse_Toplevel_column_chunk cc,
  Parquet_Pulse_Toplevel_offset_index oi
);

int64_t
Parquet_Pulse_Toplevel0_page_location_access_offset(
  Parquet_Spec_Toplevel_Types_page_location pl
);

bool
Parquet_Pulse_Toplevel0_option_offset_in_page_locations(
  FStar_Pervasives_Native_option__int64_t o,
  Parquet_Pulse_Vec_vec__Parquet_Spec_Toplevel_Types_page_location pl
);

bool
Parquet_Pulse_Toplevel0_impl_validate_offset_index_cc_page_offsets(
  Parquet_Pulse_Toplevel_column_chunk cc,
  Parquet_Pulse_Toplevel_offset_index oi
);

bool
Parquet_Pulse_Toplevel0_impl_validate_offset_index_col_size(
  Parquet_Pulse_Toplevel_column_chunk cc,
  Parquet_Pulse_Toplevel_offset_index oi
);

int64_t
Parquet_Pulse_Toplevel0_impl_page_location_offset(Parquet_Spec_Toplevel_Types_page_location pl);

int64_t
Parquet_Pulse_Toplevel0_impl_page_location_size(Parquet_Spec_Toplevel_Types_page_location pl);

bool
Parquet_Pulse_Toplevel0_impl_validate_offset_index(
  Parquet_Pulse_Toplevel_column_chunk cc,
  Parquet_Pulse_Toplevel_offset_index oi
);

bool
Parquet_Pulse_Toplevel0_impl_validate_offset_index_all(
  Parquet_Pulse_Toplevel_column_chunk cc,
  Pulse_Lib_Slice_slice__uint8_t data,
  Parquet_Pulse_Toplevel_offset_index oi
);

extern bool
Parquet_Pulse_Toplevel0_validate_offset_index(Pulse_Lib_Slice_slice__uint8_t uu___, size_t *x0);

extern Parquet_Pulse_Toplevel_offset_index
Parquet_Pulse_Toplevel0_read_offset_index(Pulse_Lib_Slice_slice__uint8_t uu___);

bool
Parquet_Pulse_Toplevel0_impl_validate_offset_index_all0(
  Pulse_Lib_Slice_slice__uint8_t data,
  Parquet_Pulse_Toplevel_column_chunk cc,
  Pulse_Lib_Slice_slice__uint8_t x
);

bool
Parquet_Pulse_Toplevel0_validate_jump_offset_index(
  size_t offset_sz,
  size_t length_sz,
  Pulse_Lib_Slice_slice__uint8_t data,
  Parquet_Pulse_Toplevel_column_chunk cc,
  Pulse_Lib_Slice_slice__uint8_t input
);

bool
Parquet_Pulse_Toplevel0_impl_validate_all_validate_column_chunk(
  Pulse_Lib_Slice_slice__uint8_t data,
  Parquet_Pulse_Toplevel_column_chunk cc
);

bool
Parquet_Pulse_Toplevel0_impl_validate_all_validate_row_group(
  Pulse_Lib_Slice_slice__uint8_t data,
  Parquet_Pulse_Toplevel_row_group rg
);

bool
Parquet_Pulse_Toplevel0_validate_header_magic_number(Pulse_Lib_Slice_slice__uint8_t input);

bool
Parquet_Pulse_Toplevel0_impl_validate_all0(
  Parquet_Pulse_Toplevel_file_meta_data fmd,
  Pulse_Lib_Slice_slice__uint8_t data
);

bool
Parquet_Pulse_Toplevel0_impl_validate_all(
  uint32_t len,
  Pulse_Lib_Slice_slice__uint8_t y,
  Pulse_Lib_Slice_slice__uint8_t x
);

bool
Parquet_Pulse_Toplevel0_validate_parquet(Pulse_Lib_Slice_slice__uint8_t input, size_t *poffset);


#define EverParquet_H_DEFINED
#endif /* EverParquet_H */
