/*
  Copyright 2025 Microsoft Research

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

/* Endianness support for code generated by `3d --pulse`.

   Under `--pulse` a probe copy buffer is a *pointer* to a descriptor holding
   the base pointer, the length and the position cell of the buffer backend's
   input stream. The descriptor struct itself, `EVERPARSE_COPY_BUFFER_DESCR`,
   is emitted by KaRaMeL into `EverParse.h`; `EVERPARSE_COPY_BUFFER_T` is a
   pointer to it, rather than the opaque `void*` of the Low* backend.

   The indirection is what lets a probe callback repoint a copy buffer at the
   probed bytes instead of copying into it, as in-place probing does in Low*.

   Defining the guard below before including `EverParseEndianness.h`
   suppresses the legacy `void*` typedef, so that the two do not clash. */

#ifndef EverParsePulseEndianness_H
#define EverParsePulseEndianness_H

#define EVERPARSE_COPY_BUFFER_T_DEFINED

/* Declared, not defined: `EverParse.h` carries the definition, and is included
   after this header by generated wrappers. A pointer to an incomplete struct
   type is all that is needed here. */
struct EVERPARSE_COPY_BUFFER_DESCR_s;
typedef struct EVERPARSE_COPY_BUFFER_DESCR_s *EVERPARSE_COPY_BUFFER_T;

#include "EverParseEndianness.h"

#endif
