/*
  Copyright 2025 Microsoft Research

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

/* Endianness support for code generated by `3d --pulse`.

   Nothing specific to `--pulse` is needed here any more: as in the Low*
   backend, a probe copy buffer is an opaque `void*` handle, and the client
   provides `EverParseStreamOf`, `EverParseStreamLen` and `EverParseStreamPos`
   to project it. The first two are exactly the Low* hooks; the third returns
   the position cell that Pulse validators carry inside the stream and that
   Low* validators instead take as an argument.

   This header is kept as the single `-add-include` for the `EverParse` bundle
   under `--pulse`, so that anything the Pulse backend does need later has a
   place to go. */

#ifndef EverParsePulseEndianness_H
#define EverParsePulseEndianness_H

#include "EverParseEndianness.h"
#include <stddef.h>

/* The three copy-buffer projections a client has to implement in order to use
   probes. KaRaMeL does emit these declarations, but into `internal/EverParse.h`,
   which client code is not meant to include; repeating them here is what gives
   a client's definitions the same signature checking the Low* backend provides
   by declaring `EverParseStreamOf`/`EverParseStreamLen` in `EverParse.h`. */
extern uint8_t *EverParseStreamOf(EVERPARSE_COPY_BUFFER_T x);
extern size_t EverParseStreamLen(EVERPARSE_COPY_BUFFER_T x);
extern size_t *EverParseStreamPos(EVERPARSE_COPY_BUFFER_T x);

#endif
