/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: krml -I ../../src/lowparse -skip-compilation -tmpdir ../unittests.snapshot -bundle LowParse.\* -drop FStar.Tactics.\* -drop FStar.Reflection.\* T10.fst T11.fst T11_z.fst T12.fst T12_z.fst T13.fst T13_x.fst T14.fst T14_x.fst T15_body.fst T15.fst T16.fst T16_x.fst T17.fst T17_x_a.fst T17_x_b.fst T18.fst T18_x_a.fst T18_x_b.fst T19.fst T1.fst T20.fst T21.fst T22_body_a.fst T22_body_b.fst T22.fst T23.fst T24.fst T24_y.fst T25_bpayload.fst T25.fst T25_payload.fst T26.fst T27.fst T28.fst T29.fst T2.fst T30.fst T31.fst T32.fst T33.fst T34.fst T35.fst T36.fst T3.fst T4.fst T5.fst T6.fst T6le.fst T7.fst T8.fst T8_z.fst T9_b.fst T9.fst Tag2.fst Tag.fst Tagle.fst -warn-error +9
  F* version: 74c6d2a5
  KreMLin version: 1bd260eb
 */

#include "T24_y.h"

uint32_t T24_y_t24_y_validator(LowParse_Slice_slice input, uint32_t pos)
{
  uint32_t pos1 = LowParse_Low_BCVLI_validate_bcvli(input, pos);
  if (LOWPARSE_LOW_BASE_VALIDATOR_MAX_LENGTH < pos1)
    return pos1;
  else
  {
    uint32_t n1 = LowParse_Low_BCVLI_read_bcvli(input, pos);
    if (n1 < (uint32_t)12U || (uint32_t)32U < n1)
      return LOWPARSE_LOW_BASE_VALIDATOR_ERROR_GENERIC;
    else
    {
      uint32_t bpos1 = pos1;
      uint32_t br = n1;
      while (true)
      {
        uint32_t r = br;
        bool ite;
        if (r == (uint32_t)0U)
          ite = true;
        else
        {
          uint32_t pos11 = bpos1;
          uint32_t pos2;
          if (input.len - pos11 < (uint32_t)2U)
            pos2 = LOWPARSE_LOW_BASE_VALIDATOR_ERROR_NOT_ENOUGH_DATA;
          else
            pos2 = pos11 + (uint32_t)2U;
          br = r - (uint32_t)1U;
          bpos1 = pos2;
          ite = LOWPARSE_LOW_BASE_VALIDATOR_MAX_LENGTH < pos2;
        }
        if (ite)
          break;
      }
      uint32_t res = bpos1;
      return res;
    }
  }
}

uint32_t T24_y_t24_y_jumper(LowParse_Slice_slice input, uint32_t pos)
{
  uint32_t pos1 = LowParse_Low_BCVLI_jump_bcvli(input, pos);
  uint32_t n1 = LowParse_Low_BCVLI_read_bcvli(input, pos);
  uint32_t bpos1 = pos1;
  uint32_t br = n1;
  while (true)
  {
    uint32_t r = br;
    bool ite;
    if (r == (uint32_t)0U)
      ite = true;
    else
    {
      uint32_t pos11 = bpos1;
      uint32_t pos2 = pos11 + (uint32_t)2U;
      br = r - (uint32_t)1U;
      bpos1 = pos2;
      ite = false;
    }
    if (ite)
      break;
  }
  uint32_t res = bpos1;
  return res;
}

