/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: krml -I ../../src/lowparse -skip-compilation -tmpdir ../unittests.snapshot -bundle LowParse.\* -drop FStar.Tactics.\* -drop FStar.Reflection.\* T10.fst T11.fst T11_z.fst T12.fst T12_z.fst T13.fst T13_x.fst T14.fst T14_x.fst T15_body.fst T15.fst T16.fst T16_x.fst T17.fst T17_x_a.fst T17_x_b.fst T18.fst T18_x_a.fst T18_x_b.fst T19.fst T1.fst T20.fst T21.fst T22_body_a.fst T22_body_b.fst T22.fst T23.fst T24.fst T24_y.fst T25_bpayload.fst T25.fst T25_payload.fst T26.fst T27.fst T28.fst T29.fst T2.fst T30.fst T31.fst T32.fst T33.fst T34.fst T35.fst T36.fst T3.fst T4.fst T5.fst T6.fst T6le.fst T7.fst T8.fst T8_z.fst T9_b.fst T9.fst Tag2.fst Tag.fst Tagle.fst -warn-error +9
  F* version: 74c6d2a5
  KreMLin version: 1bd260eb
 */

#include "kremlib.h"
#ifndef __T8_H
#define __T8_H

#include "T5.h"
#include "LowParse.h"
#include "T8_z.h"
#include "T4.h"
#include "T11_z.h"


typedef struct T8_t8_s
{
  Prims_list__FStar_Bytes_bytes *x;
  Prims_list__FStar_Bytes_bytes *y;
  Prims_list__FStar_Bytes_bytes *z;
  uint16_t x1;
  uint16_t x2;
  uint16_t x3;
  uint16_t x4;
  uint16_t x5;
  uint16_t x6;
  uint32_t x7;
}
T8_t8;

Prims_list__FStar_Bytes_bytes *T8___proj__Mkt8__item__x(T8_t8 projectee);

Prims_list__FStar_Bytes_bytes *T8___proj__Mkt8__item__y(T8_t8 projectee);

Prims_list__FStar_Bytes_bytes *T8___proj__Mkt8__item__z(T8_t8 projectee);

uint16_t T8___proj__Mkt8__item__x1(T8_t8 projectee);

uint16_t T8___proj__Mkt8__item__x2(T8_t8 projectee);

uint16_t T8___proj__Mkt8__item__x3(T8_t8 projectee);

uint16_t T8___proj__Mkt8__item__x4(T8_t8 projectee);

uint16_t T8___proj__Mkt8__item__x5(T8_t8 projectee);

uint16_t T8___proj__Mkt8__item__x6(T8_t8 projectee);

uint32_t T8___proj__Mkt8__item__x7(T8_t8 projectee);

uint32_t T8_t8_validator(LowParse_Slice_slice input, uint32_t pos);

uint32_t T8_t8_jumper(LowParse_Slice_slice input, uint32_t pos);

uint32_t T8_accessor_t8_x(LowParse_Slice_slice input, uint32_t pos);

uint32_t T8_accessor_t8_y(LowParse_Slice_slice input, uint32_t pos);

uint32_t T8_accessor_t8_z(LowParse_Slice_slice input, uint32_t pos);

uint32_t T8_accessor_t8_x1(LowParse_Slice_slice input, uint32_t pos);

uint32_t T8_accessor_t8_x2(LowParse_Slice_slice input, uint32_t pos);

uint32_t T8_accessor_t8_x3(LowParse_Slice_slice input, uint32_t pos);

uint32_t T8_accessor_t8_x4(LowParse_Slice_slice input, uint32_t pos);

uint32_t T8_accessor_t8_x5(LowParse_Slice_slice input, uint32_t pos);

uint32_t T8_accessor_t8_x6(LowParse_Slice_slice input, uint32_t pos);

uint32_t T8_accessor_t8_x7(LowParse_Slice_slice input, uint32_t pos);

#define __T8_H_DEFINED
#endif
