module Boolean

(* This file has been automatically generated by EverParse. *)
open FStar.Bytes
module U8 = FStar.UInt8
module U16 = FStar.UInt16
module U32 = FStar.UInt32
module U64 = FStar.UInt64
module LP = LowParse.Spec.Base
module LS = LowParse.SLow.Base
module LPI = LowParse.Spec.AllIntegers
module LL = LowParse.Low.Base
module L = FStar.List.Tot
module B = LowStar.Buffer
module BY = FStar.Bytes
module HS = FStar.HyperStack
module HST = FStar.HyperStack.ST


type boolean =
  | FALSE
  | TRUE

let string_of_boolean = function
  | FALSE -> "FALSE"
  | TRUE -> "TRUE"

inline_for_extraction noextract let boolean_parser_kind = LP.strong_parser_kind 1 1 None

noextract val boolean_parser: LP.parser boolean_parser_kind boolean

noextract val boolean_serializer: LP.serializer boolean_parser

noextract val boolean_bytesize (x:boolean) : GTot nat

noextract val boolean_bytesize_eq (x:boolean) : Lemma (boolean_bytesize x == Seq.length (LP.serialize boolean_serializer x))

val boolean_parser32: LS.parser32 boolean_parser

val boolean_serializer32: LS.serializer32 boolean_serializer

val boolean_size32: LS.size32 boolean_serializer

val boolean_validator: LL.validator boolean_parser

let boolean_jumper: LL.jumper boolean_parser = LL.jump_constant_size boolean_parser 1ul ()

val boolean_reader: LL.leaf_reader boolean_parser

val boolean_writer: LL.leaf_writer_strong boolean_serializer

val boolean_lserializer: LL.serializer32 boolean_serializer

val boolean_bytesize_eqn (x: boolean) : Lemma (boolean_bytesize x == 1) [SMTPat (boolean_bytesize x)]

