all: verify

EVERCBOR_SRC_PATH = $(realpath ../..)
INCLUDE_PATHS += $(realpath ..)

include $(EVERCBOR_SRC_PATH)/pulse.Makefile

ALREADY_CACHED := *,-CBOR.Pulse,

include $(EVERCBOR_SRC_PATH)/common.Makefile

