name: Build everparse package (MacOS)
on:
  push:
    branches-ignore:
    - _**
  pull_request:
  workflow_dispatch:
    inputs:
      fstar_repo:
        description: F* repository (use org/repo for Github repos)
        default: 'FStarLang/FStar'
        type: string
        required: true
      fstar_ref:
        description: F* ref (branch, or tag, or commit hash)
        default: 'master'
        type: string
        required: true
      karamel_repo:
        description: Karamel repository (use org/repo for Github repos)
        default: 'FStarLang/karamel'
        type: string
        required: true
      karamel_ref:
        description: Karamel ref (branch, or tag, or commit hash)
        default: 'master'
        type: string
        required: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
